import fs from 'node:fs';

const prior = JSON.parse(fs.readFileSync(new URL('./screening_2025_database_fulltext_batch04.json', import.meta.url)));
const columns = prior.metadata.extraction_columns;
const dimensions = prior.metadata.quality_dimensions;

function record(values) {
  const out = Object.fromEntries(columns.map((column) => [column, values[column] ?? 'not reported']));
  const extra = Object.keys(values).filter((key) => !columns.includes(key));
  if (extra.length || Object.keys(out).length !== 52) throw new Error(`invalid record ${values['Paper ID']}: ${extra.join(',')}`);
  return out;
}

const evidence_records = [
  record({
    'Paper ID': 'abramson_et_al_2025_qualitative_research_ai_pragmatic',
    'Full citation': 'Abramson, Corey M., Tara Prendergast, Zhuofan Li, and Daniel Dohan. 2025. Qualitative Research in an Era of AI: A Pragmatic Approach to Data Analysis, Workflow, and Computation. arXiv:2509.12503v5; accepted/forthcoming in Annual Review of Sociology 52 (2026). OSF version DOI: 10.31235/osf.io/7bsgy_v4.',
    Title: 'Qualitative Research in an Era of AI: A Pragmatic Approach to Data Analysis, Workflow, and Computation',
    Authors: 'Corey M. Abramson; Tara Prendergast; Zhuofan Li; Daniel Dohan',
    Year: 2025,
    Venue: 'arXiv preprint; accepted/forthcoming in Annual Review of Sociology 52 (2026)',
    'Publication type': 'methodological review/guidance with illustrative computational-ethnography workflow',
    'Peer-reviewed status': 'accepted/forthcoming; inspected preprint, not final version of record',
    'Publication history notes': 'arXiv v5 posted 2025-09-15 and updated 2025-11-12; SocArXiv/OSF versions are the same family; latest OSF v4. Count once.',
    URL: 'https://arxiv.org/abs/2509.12503',
    DOI: '10.31235/osf.io/7bsgy_v4 (OSF version; journal DOI not yet assigned)',
    'Citation count, source, and retrieval date': 'OpenAlex: 1 for OSF work and 0 for arXiv record, checked 2026-08-24',
    'Core or adjacent classification': 'adjacent',
    'Relationship/dependence family': 'DISCERN and prior Abramson/Li computational-ethnography work supply some performance claims; no independent current LLM evaluation',
    'Research objective': 'Offer a pragmatic typology—streamlining, scaling, hybrid work, sociology of computation, and rejection—and illustrate it using DISCERN.',
    'Claimed qualitative methodology': 'pragmatic methodological review and computational ethnography workflow',
    'Actual operationalized methodology': 'Conceptual synthesis plus an illustrative longitudinal health-sociology workflow; no formal current-paper evaluation of LLM-generated codes or themes.',
    'Inductive, deductive, or hybrid': 'hybrid; human theory/method leads, computational tools index, retrieve, and scale stable categories',
    Domain: 'older adults, dementia, care partners, and health sociology',
    'Dataset name': 'DISCERN, a five-year NIH project across three U.S. states',
    'Public or restricted data': 'restricted',
    'Number of documents': '119 interviews plus more than 300 day-long site visits; exact analyzable-file count not reported',
    'Number of participants': 'not reported',
    'Approximate corpus size': 'large longitudinal fieldwork corpus; exact words/pages not reported',
    'Document length': 'not reported',
    Language: 'not fully reported; fieldworkers preserve original language and are fluent where required',
    'Sensitive-data status': 'highly sensitive health and participant data',
    'Model family': 'regex/dictionaries; BERT/RoBERTa/Gemma-2-2B embeddings or local classifiers in described/related workflows; Claude/GPT/Gemini only for manuscript editing',
    'Exact model/version': 'not adequately reported; no commercial model received study data',
    'Prompting strategy': 'Commercial models limited to language/citation/error editing; qualitative-analysis prompts not applicable/reported.',
    'Fine-tuning or adaptation': 'local fine-tuned classifiers described; exact training configuration absent',
    'Single-agent or multi-agent': 'hybrid human-computational pipeline, not multi-agent',
    'Agent roles': 'machines index, retrieve, classify stable categories, and assist pattern discovery; humans interpret',
    'Human role': 'Primary analysts develop nuanced codes, audit labels, examine disconfirming evidence, and maintain reflexive interpretation.',
    'Unit of analysis': 'source-linked paragraphs/passages and indexed qualitative materials',
    'Generated outputs': 'indexes, codes/classifiers, memos, embeddings, network and pattern maps',
    'Evidence/provenance mechanism': 'Stable paragraph IDs, positional metadata, and links back to raw context provide strong procedural provenance.',
    Baselines: 'No current-paper formal baseline; manual workflow and prior published work are discussed.',
    'Number of runs or seeds': 'not reported',
    'Automatic metrics': 'None clearly attributable to the current DISCERN evaluation; F1 around .80 is mentioned from prior/related work.',
    'Human-evaluation design': 'Weekly review, memoing, disconfirming-case analysis, and reflexive meetings; not a formal comparative evaluation.',
    'Number and expertise of evaluators': 'research team; count and expertise by task incompletely reported',
    'Inter-rater reliability': 'Krippendorff α around .80 is mentioned from prior/related work, not clearly the present case.',
    'Statistical analysis': 'none',
    'Principal results': 'Human-machine agreement around .80, less than one-third manual time, and “months” saved are not cleanly separated from prior work and are not controlled current-paper estimates.',
    'Efficiency or cost results': 'Qualitative time-saving claims only; no measured cost/compute.',
    'Ethics and privacy treatment': 'IRB-governed restricted data, vetted transcription, anonymization/pseudonyms, separated identifiers, secure REDCap/Box/wiki/Git, local models, and no commercial study-data transfer; protocol/consent wording absent.',
    'Reproducibility resources': 'Teaching/code/templates repository https://github.com/Computational-Ethnography-Lab/teaching, version dated 2025-11-01; original data unavailable under IRB.',
    'Author-reported limitations': 'Methods and theory must precede tools; small samples may not benefit; local models and documentation still require expertise.',
    'Additional validity concerns': 'Current-versus-prior evaluation provenance is ambiguous; exact models/configurations and controlled comparisons are absent; commercial tools were used during manuscript production.',
    'Relationship to prior papers': 'Related Abramson/Li computational-ethnography work supplies some metrics; do not treat those figures as an independent evaluation here.',
    'Relevance to the proposed ARR project': 'Strong design guidance on stable source IDs, local processing, negative/minority cases, version logs, and limiting automation to stable/indexical tasks.'
  }),
  record({
    'Paper ID': 'zhang_et_al_2025_rosannotator',
    'Full citation': 'Zhang, Yan, Haoqi Li, Ramtin Tabatabaei, and Wafa Johal. 2025. ROSAnnotator: A Web Application for ROSBag Data Analysis in Human-Robot Interaction. 2025 20th ACM/IEEE International Conference on Human-Robot Interaction, 1099–1103. https://doi.org/10.1109/HRI61500.2025.10974254.',
    Title: 'ROSAnnotator: A Web Application for ROSBag Data Analysis in Human-Robot Interaction',
    Authors: 'Yan Zhang; Haoqi Li; Ramtin Tabatabaei; Wafa Johal',
    Year: 2025,
    Venue: 'ACM/IEEE HRI 2025, pages 1099–1103',
    'Publication type': 'peer-reviewed conference system/demo paper',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'arXiv:2501.07051v1 posted 2025-01-13; VOR published 2025-03-04. One family.',
    URL: 'https://doi.org/10.1109/HRI61500.2025.10974254',
    DOI: '10.1109/HRI61500.2025.10974254',
    'Citation count, source, and retrieval date': 'OpenAlex: 3, checked 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'arXiv/VOR ROSAnnotator family; no duplicate system report located',
    'Research objective': 'Provide an accessible web application for synchronized ROSBag exploration, annotation, transcription, and LLM-assisted coding.',
    'Claimed qualitative methodology': 'qualitative multimodal annotation and analysis',
    'Actual operationalized methodology': 'Engineering implementation/demo supporting manual and automated segment coding; no empirical validity or usability study.',
    'Inductive, deductive, or hybrid': 'supports deductive codebooks and free-text/hybrid annotation',
    Domain: 'human-robot interaction',
    'Dataset name': 'no fixed evaluation dataset',
    'Public or restricted data': 'user supplied; variable',
    'Number of documents': 'not applicable/not reported',
    'Number of participants': 'not applicable/not reported',
    'Approximate corpus size': 'not applicable/not reported',
    'Document length': 'not applicable/not reported',
    Language: 'variable/not reported',
    'Sensitive-data status': 'potentially high for audio/video HRI recordings',
    'Model family': 'OpenAI multimodal/API models and configurable Hugging Face access',
    'Exact model/version': 'not reported, including transcription and multimodal snapshots',
    'Prompting strategy': 'Default and user-modifiable prompts; complete defaults/configuration not adequately documented in the paper.',
    'Fine-tuning or adaptation': 'none reported',
    'Single-agent or multi-agent': 'single-model calls inside a web application',
    'Agent roles': 'transcription, code assignment, and multimodal-segment interpretation',
    'Human role': 'Uploads codebook, initiates operations, and may inspect/edit output; verification is not mandatory.',
    'Unit of analysis': 'synchronized time interval/multimodal segment',
    'Generated outputs': 'codes, annotation tiers, transcripts, occurrence/frequency/duration/latency statistics, and CSV',
    'Evidence/provenance mechanism': 'Annotations remain tied to synchronized ROSBag intervals.',
    Baselines: 'none',
    'Number of runs or seeds': 'none reported',
    'Automatic metrics': 'none',
    'Human-evaluation design': 'none',
    'Number and expertise of evaluators': 'none',
    'Inter-rater reliability': 'not applicable',
    'Statistical analysis': 'none',
    'Principal results': 'Functional capability only; no evidence of coding accuracy, thematic validity, usability, or stability.',
    'Efficiency or cost results': 'not measured',
    'Ethics and privacy treatment': 'Face frames can be removed locally before external video transfer; audio transcription remains external and voice/body/location/transcript/contextual identifiers remain exposed. Redaction may remove analytically important nonverbal context.',
    'Reproducibility resources': 'https://github.com/CHRI-Lab/ROSAnnotator; Docker image roughly 20 GB; no benchmark data/output archive',
    'Author-reported limitations': 'Automatic annotation is not robust for nuanced HRI; commercial cost; external-audio privacy; built-ins focus on audio/video topics.',
    'Additional validity concerns': 'No exact model/configuration, empirical validation, mandatory review, or redaction-effect evaluation.',
    'Relationship to prior papers': 'standalone ROSAnnotator tool family',
    'Relevance to the proposed ARR project': 'Useful provenance/infrastructure example, but it must be classified as unvalidated rather than evidence that automated coding works.'
  }),
  record({
    'Paper ID': 'sakib_et_al_2025_shortcut_sdoh',
    'Full citation': 'Sakib, Fardin Ahsan, Ziwei Zhu, Karen Trister Grace, Meliha Yetisgen, and Ozlem Uzuner. 2025. Spurious Correlations and Beyond: Understanding and Mitigating Shortcut Learning in SDOH Extraction with Large Language Models. arXiv:2506.00134v1.',
    Title: 'Spurious Correlations and Beyond: Understanding and Mitigating Shortcut Learning in SDOH Extraction with Large Language Models',
    Authors: 'Fardin Ahsan Sakib; Ziwei Zhu; Karen Trister Grace; Meliha Yetisgen; Ozlem Uzuner',
    Year: 2025,
    Venue: 'arXiv:2506.00134v1',
    'Publication type': 'preprint empirical NLP study',
    'Peer-reviewed status': 'not established',
    'Publication history notes': 'v1 submitted 2025-05-30; no later VOR located',
    URL: 'https://arxiv.org/abs/2506.00134',
    DOI: 'not assigned',
    'Citation count, source, and retrieval date': 'OpenAlex: 0, checked 2026-08-24',
    'Core or adjacent classification': 'adjacent',
    'Relationship/dependence family': 'SHAC/MIMIC benchmark family; not a duplicate qualitative-analysis paper',
    'Research objective': 'Identify and mitigate shortcut learning in drug-status extraction from social-history notes.',
    'Claimed qualitative methodology': 'SDOH information extraction with shortcut analysis',
    'Actual operationalized methodology': 'Fixed-label span/status classification with subgroup false-positive rates and trigger-deletion experiments.',
    'Inductive, deductive, or hybrid': 'deductive',
    Domain: 'clinical NLP / social determinants of health',
    'Dataset name': 'SHAC/MIMIC-III social-history note sections with demographics',
    'Public or restricted data': 'controlled/restricted',
    'Number of documents': '4,405 deidentified sections reported; wording is ambiguous whether this is all SHAC or the MIMIC subset',
    'Number of participants': 'not reported',
    'Approximate corpus size': '4,405 sections; split denominators incomplete',
    'Document length': 'not reported',
    Language: 'apparently English; not explicitly reported',
    'Sensitive-data status': 'deidentified but sensitive clinical/drug-use/gender/alcohol/smoking data',
    'Model family': 'Llama and Qwen',
    'Exact model/version': 'Llama-3.1-70B, Llama-3.1-8B, Llama-3-Med42-70B, Qwen-72B; checkpoints/inference stack incomplete',
    'Prompting strategy': 'zero-shot, three-example ICL, chain-of-thought, shortcut warning, and up to eight examples; prompts in appendix',
    'Fine-tuning or adaptation': 'Llama-3.1-8B LoRA SFT, rank 64, dropout .1, learning rate 2e-4, batch 4, five epochs, FP16',
    'Single-agent or multi-agent': 'single-model alternatives',
    'Agent roles': 'span extraction and temporal-status classification',
    'Human role': 'inherited reference annotations only; no current human-in-loop interpretation',
    'Unit of analysis': 'social-history note section and drug-status mention',
    'Generated outputs': 'trigger span and current/past/none status',
    'Evidence/provenance mechanism': 'Predictions link to note sections/triggers; no qualitative source-audit interface.',
    Baselines: 'multiple model/prompt conditions and SFT',
    'Number of runs or seeds': 'no stochastic replicates/seeds reported',
    'Automatic metrics': 'false-positive rate, primarily for none/unknown, stratified by cues and gender',
    'Human-evaluation design': 'none current; SHAC labels inherited',
    'Number and expertise of evaluators': 'SHAC annotators not characterized in this paper',
    'Inter-rater reliability': 'not reported',
    'Statistical analysis': 'descriptive rates only; no uncertainty intervals or tests',
    'Principal results': 'Llama-70B zero-shot false-positive rates were 66.21% for alcohol-positive, 61.11% smoking-positive, and 73.26% both; chain-of-thought reduced them to 33.79%, 25.93%, and 34.88%. Llama-8B SFT reduced the both-cue FPR from 81.40% to 40.70%. Trigger deletion reduced but did not eliminate errors; gender effects varied.',
    'Efficiency or cost results': 'LoRA training about three hours on two A100s; inference around 100 GPU-hours on two A100s',
    'Ethics and privacy treatment': 'Controlled deidentified data on secure university systems under DUAs/IRB processes; exact protocol IDs absent; authors discuss stigma risk.',
    'Reproducibility resources': 'No code/data release; SHAC controlled; prompts and hyperparameters partial.',
    'Author-reported limitations': 'One corpus, open models only, causal mechanism unresolved, generative setting only, and incomplete mitigations.',
    'Additional validity concerns': 'Trigger deletion is not a matched causal intervention; subgroup denominators absent; FPR-only hides false negatives; binary gender/site/documentation confounding; mitigation may overfit discovered shortcuts.',
    'Relationship to prior papers': 'SHAC/MIMIC benchmark lineage',
    'Relevance to the proposed ARR project': 'Strong adjacent rationale for subgroup audits, matched counterfactuals, denominators/CIs, multiple metrics, and speaker/participant-cue checks.'
  }),
  record({
    'Paper ID': 'de_paoli_fawzi_2025_tallmesh',
    'Full citation': 'De Paoli, Stefano, and Alex Fawzi. 2025. TALLMesh: A Simple Application for Performing Thematic Analysis with Large Language Models. arXiv:2504.13892v1.',
    Title: 'TALLMesh: A Simple Application for Performing Thematic Analysis with Large Language Models',
    Authors: 'Stefano De Paoli; Alex Fawzi',
    Year: 2025,
    Venue: 'arXiv:2504.13892v1',
    'Publication type': 'draft preprint system paper',
    'Peer-reviewed status': 'not established; manuscript labeled Draft',
    'Publication history notes': 'v1 submitted 2025-04-05; no archival VOR located',
    URL: 'https://arxiv.org/abs/2504.13892',
    DOI: 'not assigned',
    'Citation count, source, and retrieval date': 'OpenAlex: 2, checked 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'Tool implements De Paoli’s earlier 2024 workflow; distinct software artifact, not an independent empirical validation.',
    'Research objective': 'Create a no-code Streamlit application implementing an LLM thematic-analysis workflow.',
    'Claimed qualitative methodology': 'thematic analysis with human-in-loop refinement',
    'Actual operationalized methodology': 'Sequential per-document code generation, LLM code deduplication, theme grouping, and a second pass forcing unassigned-code allocation; tool description without outcome validation.',
    'Inductive, deductive, or hybrid': 'nominally inductive; optional prompts/codebooks make it hybrid',
    Domain: 'generic qualitative text',
    'Dataset name': 'no substantive evaluation dataset',
    'Public or restricted data': 'not applicable',
    'Number of documents': 'not reported',
    'Number of participants': 'informal Abertay user testing mentioned; n not reported',
    'Approximate corpus size': 'not reported',
    'Document length': 'not reported',
    Language: 'not reported',
    'Sensitive-data status': 'variable user-supplied qualitative data',
    'Model family': 'OpenAI/Azure GPT',
    'Exact model/version': 'defaults mention GPT-4, GPT-4o, GPT-4o-mini; snapshots absent',
    'Prompting strategy': 'preset/editable prompts; temperature/top-p configurable',
    'Fine-tuning or adaptation': 'none; DSPy reducer proposed as future work',
    'Single-agent or multi-agent': 'sequential single-LLM pipeline',
    'Agent roles': 'open coder, code reducer/deduplicator, theme grouper, and forced assigner of unassigned codes',
    'Human role': 'Configures project/prompts and may inspect/edit; review is afforded but not mandatory.',
    'Unit of analysis': 'document/passage and generated code',
    'Generated outputs': 'code-description-quote CSV, accumulated codebook, themes, visualizations, unique/total-code ratio',
    'Evidence/provenance mechanism': 'Quotes retained at code stage; theme-level outputs can lose quote/source links.',
    Baselines: 'none',
    'Number of runs or seeds': 'none; determinism at zero temperature/top-p is asserted but not tested',
    'Automatic metrics': 'unique-to-total-code ratio presented as thematic saturation; not validated',
    'Human-evaluation design': 'think-aloud/Miro feedback for interface changes only',
    'Number and expertise of evaluators': 'not reported',
    'Inter-rater reliability': 'none',
    'Statistical analysis': 'none',
    'Principal results': 'Functional workflow/interface description only; no coding/theme quality, stability, or comparative result.',
    'Efficiency or cost results': 'unmeasured',
    'Ethics and privacy treatment': 'Generic advice to check institutional requirements and use Azure/GDPR-compatible deployments; direct OpenAI risks not evaluated.',
    'Reproducibility resources': 'https://github.com/sdptn/TALLMesh_multi_page; application/prompts available, no benchmark/expected outputs',
    'Author-reported limitations': 'Documentation/training needed, reducer needs improvement, and open models/broader testing are future work.',
    'Additional validity concerns': 'Forced theme assignment suppresses unassigned/negative cases; deduplication and saturation ratio unvalidated; dissemination to roughly 100 scholars is not evaluation.',
    'Relationship to prior papers': 'De Paoli 2024 workflow lineage',
    'Relevance to the proposed ARR project': 'Representative end-to-end architecture; motivates source-linked themes, negative/unassigned states, reducer validation, stability tests, and defensible stopping criteria.'
  }),
  record({
    'Paper ID': 'borchers_et_al_2026_temperature_persona_consensus',
    'Full citation': 'Borchers, Conrad, Bahar Shahrokhian, Francesco Balzan, Elham Tajik, Sreecharan Sankaranarayanan, and Sebastian Simon. 2026. Temperature and Persona Shape LLM Agent Consensus With Minimal Accuracy Gains in Qualitative Coding. Proceedings of the 19th International Conference on Educational Data Mining, 280–292. https://doi.org/10.5281/zenodo.21039879.',
    Title: 'Temperature and Persona Shape LLM Agent Consensus With Minimal Accuracy Gains in Qualitative Coding',
    Authors: 'Conrad Borchers; Bahar Shahrokhian; Francesco Balzan; Elham Tajik; Sreecharan Sankaranarayanan; Sebastian Simon',
    Year: 2026,
    Venue: 'Proceedings of the 19th International Conference on Educational Data Mining, pages 280–292',
    'Publication type': 'peer-reviewed full conference paper',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'arXiv:2507.11198v1 posted 2025-07-15, v2 2026-05-10; EDM 2026 VOR preferred. Count once.',
    URL: 'https://doi.org/10.5281/zenodo.21039879',
    DOI: '10.5281/zenodo.21039879',
    'Citation count, source, and retrieval date': 'OpenAlex: 2 for arXiv and 0 for new VOR, checked 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': '2025 arXiv/2026 EDM family; reuses Barany et al. educational dialogue dataset/reference coding',
    'Research objective': 'Test whether same-model multi-agent deliberation improves coding accuracy and how temperature/persona affect consensus.',
    'Claimed qualitative methodology': 'LLM-agent qualitative coding',
    'Actual operationalized methodology': 'Fixed eight-code binary multilabel classification with same-model deliberation; identifying this with thematic analysis is methodologically debatable.',
    'Inductive, deductive, or hybrid': 'deductive',
    Domain: 'ninth-grade Algebra I virtual tutoring',
    'Dataset name': '579 dialogue segments from three transcripts derived from four prior 60-minute sessions',
    'Public or restricted data': 'restricted/on request',
    'Number of documents': 'three session transcripts used; four existed in the source study, with one exclusion unexplained',
    'Number of participants': 'not reported',
    'Approximate corpus size': '579 segments',
    'Document length': 'source sessions approximately 60 minutes; segment lengths not reported',
    Language: 'apparently English; not reported',
    'Sensitive-data status': 'minors’ educational dialogue; verbatim data restricted',
    'Model family': 'Llama, OpenHermes, WizardLM, Phi, Mistral, and DeepSeek',
    'Exact model/version': 'Llama-3.2-3B, OpenHermes-V2-7B, WizardLM-2-7B, Phi-3-14B, Mistral-Small-3.2-24B-Instruct-2506, DeepSeek-R1-32B via Ollama; several tags/checkpoints incomplete',
    'Prompting strategy': 'Full utterance, eight-code codebook, and conversation history; balanced/bold/empathetic personas; up to two critique rounds; one schema-failure re-prompt.',
    'Fine-tuning or adaptation': 'none',
    'Single-agent or multi-agent': 'two same-model coders plus critique; neutral consensus agent resolves residual disagreement',
    'Agent roles': 'coder A, coder B, critic/deliberator, and fallback consensus agent',
    'Human role': 'No deployment-time intervention; humans supply adjudicated reference labels and inspect selected deliberation traces.',
    'Unit of analysis': 'utterance × code binary decision',
    'Generated outputs': 'eight binary labels, consensus categories, CSV, and deliberation traces',
    'Evidence/provenance mechanism': 'Dialogue and deliberation traces retained; final labels link to utterances.',
    Baselines: 'neutral single-agent control and adjudicated human labels',
    'Number of runs or seeds': 'six models × three temperatures × six persona pairings; no explicit stochastic replicates/seeds',
    'Automatic metrics': 'percent agreement against human labels and consensus-type counts',
    'Human-evaluation design': 'Inherited trained double-coded/adjudicated reference plus qualitative analysis of selected agent conversations.',
    'Number and expertise of evaluators': 'source annotators plus two current qualitative trace coders',
    'Inter-rater reliability': 'Source described only as high; current text conflicts between independent double coding and 75 nonoverlapping cases, so no defensible current IRR.',
    'Statistical analysis': 'GLMM with random utterance/code effects, odds ratios/95% CIs, and 432 exploratory paired contrasts with BH adjustment',
    'Principal results': 'Final/single agreement: DeepSeek 90.0/89.9; Llama 81.6/85.5; Mistral 89.3/89.7; OpenHermes 84.9/85.8; Phi 89.5/89.6; Wizard 85.6/87.2. Only 5/432 contrasts favored MAS, all one OpenHermes subset; 65 favored single agents. Higher temperature often delayed/reduced consensus; traces contained contradictions, hallucinated facts, and invented codes.',
    'Efficiency or cost results': 'About two hours on an M1 for some experiments; DeepSeek about 60 seconds/datapoint on an A100; total compute/cost absent and MAS adds calls.',
    'Ethics and privacy treatment': 'No IRB, consent, deidentification, or child-data statement despite minors’ transcripts.',
    'Reproducibility resources': 'https://github.com/conradborchers/llm-ta-consensus/ includes code/prompts/results; codebook/data on request',
    'Author-reported limitations': 'One dataset/mature codebook, deductive only, same-model agents, persona dependence, and no cross-model teams.',
    'Additional validity concerns': 'Reported 77,273 decisions do not reconcile with full factorial 6×18×579×8=500,256; exclusions/denominator unexplained. Raw agreement is prevalence-sensitive; no F1, sensitivity, balanced accuracy, or code-prevalence analysis.',
    'Relationship to prior papers': 'Barany et al. dataset/reference-coding dependency; one arXiv/EDM family',
    'Relevance to the proposed ARR project': 'High-value negative finding that same-model consensus is not accuracy; require denominator reconciliation, prevalence-aware metrics, plural humans, privacy reporting, and trace audits.'
  }),
  record({
    'Paper ID': 'rodriguez_et_al_2026_text_chunking_urban',
    'Full citation': 'Rodriguez, Joshua, Om Sanan, Guillermo Vizarreta-Luna, and Steven A. Conrad. 2026. Text Chunking in Human-AI Teaming of Document Classification for Urban Systems Management Using Large Language Models. IET Smart Cities 8(1). https://doi.org/10.1049/smc2.70023.',
    Title: 'Text Chunking in Human-AI Teaming of Document Classification for Urban Systems Management Using Large Language Models',
    Authors: 'Joshua Rodriguez; Om Sanan; Guillermo Vizarreta-Luna; Steven A. Conrad',
    Year: 2026,
    Venue: 'IET Smart Cities 8(1)',
    'Publication type': 'peer-reviewed journal experiment',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'arXiv:2504.00274v1 posted 2025-03-31 under a shorter title; 2026 VOR is preferred. One family.',
    URL: 'https://doi.org/10.1049/smc2.70023',
    DOI: '10.1049/smc2.70023',
    'Citation count, source, and retrieval date': 'OpenAlex: 1 for arXiv and 0 for VOR, checked 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': '2025 arXiv/2026 VOR duplicate family',
    'Research objective': 'Determine whether chunking improves reliable document classification in an urban-system literature review.',
    'Claimed qualitative methodology': 'human-AI document coding/teamwork',
    'Actual operationalized methodology': 'Repeated 17-dimension binary classification of ten scientific papers.',
    'Inductive, deductive, or hybrid': 'deductive',
    Domain: 'urban water and digital twins',
    'Dataset name': 'ten public scientific papers and 17 expert-derived dimensions',
    'Public or restricted data': 'public',
    'Number of documents': '10',
    'Number of participants': 'three nonexpert human coders',
    'Approximate corpus size': '170 document-dimension labels; approximately 86% positive',
    'Document length': 'paper word lengths not reported',
    Language: 'apparently English; not explicit',
    'Sensitive-data status': 'nonsensitive published literature',
    'Model family': 'OpenAI GPT/o-series',
    'Exact model/version': 'GPT-4o, GPT-4o-mini, o1-mini; snapshots not reported',
    'Prompting strategy': 'One dimension at a time, presence/absence plus two supporting pieces of evidence; fresh/reset call per prompt.',
    'Fine-tuning or adaptation': 'none',
    'Single-agent or multi-agent': 'single-model repeated classification',
    'Agent roles': 'whole-paper classifier or 500-word-chunk classifier',
    'Human role': 'Three nonexperts independently code; majority becomes reference.',
    'Unit of analysis': 'document × dimension; chunking uses nonoverlapping 500-word chunks and document-level OR aggregation',
    'Generated outputs': 'true/false plus evidence text',
    'Evidence/provenance mechanism': 'Evidence requested but not evaluated; label-centric analysis.',
    Baselines: 'human majority, whole-document versus chunked strategies, and three models',
    'Number of runs or seeds': '15 iterations per configuration; seeds/settings not reported',
    'Automatic metrics': 'internal percent agreement/mode; accuracy, precision, recall versus majority; Fleiss κ',
    'Human-evaluation design': 'three nonexpert coders; no domain-expert gold adjudication',
    'Number and expertise of evaluators': 'three nonexpert coders',
    'Inter-rater reliability': 'human Fleiss κ=.434',
    'Statistical analysis': 'Kruskal-Wallis, Mann-Whitney, and Wilcoxon tests; multiple-comparison control not reported',
    'Principal results': 'Whole/chunk accuracy: GPT-4o 74.12/87.65; mini 77.65/84.12; o1 72.35/87.06. Recall rose with chunking. Internal percent agreement rose while within-model κ often fell due to prevalence. Adding GPT-4o as a fourth rater reduced human κ .434→.407; mini produced .437.',
    'Efficiency or cost results': 'No measured time/cost despite efficiency framing.',
    'Ethics and privacy treatment': 'Public papers; no human-subject corpus concern.',
    'Reproducibility resources': 'https://github.com/josh-rodriguez-csu/ChunkingforLLMs with data/code',
    'Author-reported limitations': 'Small document sample and rapidly changing models.',
    'Additional validity concerns': 'OR aggregation confounds chunk count/document length; 86% positive prevalence inflates agreement/accuracy and negative performance is weak; nonexpert reference; ten papers are pseudoreplicated across dimensions/runs; parser was developed/tested on same outputs; κ>.4 is incorrectly called statistical significance.',
    'Relationship to prior papers': 'arXiv/VOR family only',
    'Relevance to the proposed ARR project': 'Useful chunking/stability case; require prevalence-aware metrics, independent labels, unit-matched aggregation, parser validation, and corrected inference.'
  }),
  record({
    'Paper ID': 'king_et_al_2025_frontier_privacy_policies',
    'Full citation': 'King, Jennifer, Kevin Klyman, Emily Capstick, Tiffany Saade, and Victoria Hsieh. 2025. User Privacy and Large Language Models: An Analysis of Frontier Developers’ Privacy Policies. Proceedings of the AAAI/ACM Conference on AI, Ethics, and Society 8(2): 1465–1477. https://doi.org/10.1609/aies.v8i2.36646.',
    Title: 'User Privacy and Large Language Models: An Analysis of Frontier Developers’ Privacy Policies',
    Authors: 'Jennifer King; Kevin Klyman; Emily Capstick; Tiffany Saade; Victoria Hsieh',
    Year: 2025,
    Venue: 'Proceedings of the AAAI/ACM Conference on AI, Ethics, and Society 8(2): 1465–1477',
    'Publication type': 'peer-reviewed policy-content analysis',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'arXiv:2509.05382v1 posted 2025-09-05; VOR 2025-10-15. One family.',
    URL: 'https://doi.org/10.1609/aies.v8i2.36646',
    DOI: '10.1609/aies.v8i2.36646',
    'Citation count, source, and retrieval date': 'OpenAlex: 12, checked 2026-08-24',
    'Core or adjacent classification': 'adjacent',
    'Relationship/dependence family': 'arXiv/VOR policy-analysis family',
    'Research objective': 'Compare user-privacy policies of six major frontier-model developers.',
    'Claimed qualitative methodology': 'qualitative policy analysis',
    'Actual operationalized methodology': 'Human-only coded comparison of policy documents.',
    'Inductive, deductive, or hybrid': 'hybrid: inductive categories informed by CCPA and AI-specific concepts',
    Domain: 'platform privacy and governance',
    'Dataset name': '28 policies/subpolicies/FAQs for Amazon Nova, Anthropic Claude, Google Gemini, Meta AI, Microsoft Copilot, OpenAI ChatGPT',
    'Public or restricted data': 'public web documents',
    'Number of documents': '28',
    'Number of participants': 'not applicable',
    'Approximate corpus size': '28 documents',
    'Document length': 'not reported',
    Language: 'English',
    'Sensitive-data status': 'public text; subject concerns sensitive user data',
    'Model family': 'no LLM used analytically',
    'Exact model/version': 'not applicable',
    'Prompting strategy': 'not applicable',
    'Fine-tuning or adaptation': 'not applicable',
    'Single-agent or multi-agent': 'human-only analysis',
    'Agent roles': 'not applicable',
    'Human role': 'Complete coding and review.',
    'Unit of analysis': 'policy provision/document',
    'Generated outputs': 'yes/no/not-specified matrix for collection, use, training, retention, children, and related practices',
    'Evidence/provenance mechanism': 'Source/reference URLs and access dates supplied.',
    Baselines: 'cross-company comparison only',
    'Number of runs or seeds': 'not applicable',
    'Automatic metrics': 'descriptive counts/matrix',
    'Human-evaluation design': 'Coding divided among team members; each portion reviewed by another.',
    'Number and expertise of evaluators': 'author team; allocation incomplete',
    'Inter-rater reliability': 'none',
    'Statistical analysis': 'none',
    'Principal results': 'Policies are fragmented/inconsistent, with default-training and potentially indefinite-retention risks. Table treatment of Amazon as not specified appears inconsistent with the blanket prose claim that all six train on chats by default.',
    'Efficiency or cost results': 'not applicable',
    'Ethics and privacy treatment': 'Public-document study with strong substantive ethical analysis.',
    'Reproducibility resources': 'Exact sources/access dates, but no codebook, coded matrix repository, or archived snapshots.',
    'Author-reported limitations': 'Six U.S.-focused firms, heterogeneous business models, incomplete subpolicies/model cards, and point-in-time analysis.',
    'Additional validity concerns': 'Policies changed during the study; moving pages undermine reproducibility; some aggregate prose overstates table evidence.',
    'Relationship to prior papers': 'arXiv/VOR same family',
    'Relevance to the proposed ARR project': 'Record service tier, settings, policy date, opt-out/training terms, DPA, retention, and processing geography; do not infer confidentiality from model name.'
  }),
  record({
    'Paper ID': 'relins_et_al_2025_police_vulnerability',
    'Full citation': 'Relins, Sam, Daniel Birks, and Charlie Lloyd. 2025. Using Instruction-Tuned Large Language Models to Identify Indicators of Vulnerability in Police Incident Narratives. Journal of Quantitative Criminology 41(4): 647–684. https://doi.org/10.1007/s10940-025-09611-z.',
    Title: 'Using Instruction-Tuned Large Language Models to Identify Indicators of Vulnerability in Police Incident Narratives',
    Authors: 'Sam Relins; Daniel Birks; Charlie Lloyd',
    Year: 2025,
    Venue: 'Journal of Quantitative Criminology 41(4): 647–684',
    'Publication type': 'peer-reviewed open-access journal empirical study',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'Published online 2025-06-17; PMCID PMC12612022; PMID 41245815.',
    URL: 'https://doi.org/10.1007/s10940-025-09611-z',
    DOI: '10.1007/s10940-025-09611-z',
    'Citation count, source, and retrieval date': 'OpenAlex: 2, checked 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'standalone Boston FIO vulnerability-classification pipeline/study',
    'Research objective': 'Identify mental ill health, substance misuse, alcohol dependence, and homelessness in police narratives.',
    'Claimed qualitative methodology': 'scalable qualitative coding using instruction-tuned LLMs',
    'Actual operationalized methodology': 'Four-label ordinal/binary classification with repeated inference, consensus, and evidence extraction.',
    'Inductive, deductive, or hybrid': 'deductive',
    Domain: 'policing and vulnerability',
    'Dataset name': 'Boston Police Department FIO narratives, June 2015–December 2023',
    'Public or restricted data': 'public PDDL-derived records with OSF release',
    'Number of documents': '32,218 unique narratives after deduplication/minimum-length filter; 4,000 model sample; 500-case human/GPT-4o evaluation subset',
    'Number of participants': 'unknown represented people',
    'Approximate corpus size': '32,218 narratives',
    'Document length': 'median 81 words',
    Language: 'apparently English',
    'Sensitive-data status': 'high: police contact, vulnerability, race, sex, health, housing, and substance use',
    'Model family': 'Meta Llama and OpenAI GPT',
    'Exact model/version': 'Llama nominally 8B/70B and GPT-4o; snapshots absent; paper inconsistently labels Llama sizes 7B/80B elsewhere',
    'Prompting strategy': 'Verbatim codebook, chain-of-thought/evidence quotation, iteratively refined custom prompt, and up to three reparsing attempts.',
    'Fine-tuning or adaptation': 'prompt engineering only',
    'Single-agent or multi-agent': 'repeated single-model inference with majority consensus',
    'Agent roles': 'vulnerability classifier and evidence extractor',
    'Human role': 'Three authors create codebook; two nonexpert annotators label evaluation data; team adjudicates.',
    'Unit of analysis': 'police narrative × vulnerability',
    'Generated outputs': 'positive/inconclusive/negative status, evidence, entropy, and consensus',
    'Evidence/provenance mechanism': 'Evidence quotations tied to narratives; public release redacted.',
    Baselines: 'two Llama scales/prompts, GPT-4o, and adjudicated human labels',
    'Number of runs or seeds': 'ten labels per Llama narrative; seed/decoding settings not reported',
    'Automatic metrics': 'ordinal MSE; collapsed precision/recall/F1; confusion matrices; entropy; consensus calibration',
    'Human-evaluation design': '500 enriched narratives × four vulnerabilities independently labeled then adjudicated',
    'Number and expertise of evaluators': 'two nonexpert annotators plus author adjudicators',
    'Inter-rater reliability': 'not reported',
    'Statistical analysis': '10,000-bootstrap CIs; counterfactual GLMM with random narrative effects, average marginal effects, Holm correction',
    'Principal results': 'Custom-8B/GPT-4o F1: mental health .58/.70; homelessness .75/.71; substance .67/.81; alcohol .68/.72. Unanimous-negative precision generally 95–100% over roughly half to two-thirds of narratives. Counterfactual race/sex effects were usually small but nonzero, including GPT-4o Black alcohol −2.81 percentage points and male +1.99.',
    'Efficiency or cost results': 'Weeks/months reduction claimed without measured labor/cost; GPT-4o sample restricted by API cost.',
    'Ethics and privacy treatment': 'Institution deemed public secondary data not requiring review; records redacted; representational/privacy risk remains high.',
    'Reproducibility resources': 'OSF https://osf.io/har9m/ and code https://github.com/samrelins/vulnerability_classifier_pipeline',
    'Author-reported limitations': 'One jurisdiction, uncertain generalization, prompt/model dependence.',
    'Additional validity concerns': 'Evaluation set purposively enriched using tested Custom-70B predictions; no population estimates; nonexpert gold/no IRR; inconclusive collapsed positive; exact models absent; counterfactual edits unvalidated; consensus can stabilize systematic bias.',
    'Relationship to prior papers': 'no duplicate located',
    'Relevance to the proposed ARR project': 'Important repeated-inference/entropy/counterfactual case; require independent sampling, expert references, matched perturbations, prevalence metrics, and site/officer/boilerplate confound checks.'
  }),
  record({
    'Paper ID': 'shanwetter_levit_saban_2025_cancer_llm_qualitative',
    'Full citation': 'Shanwetter Levit, Neta, and Mor Saban. 2025. When Investigator Meets Large Language Models: A Qualitative Analysis of Cancer Patient Decision-Making Journeys. npj Digital Medicine 8: 336. https://doi.org/10.1038/s41746-025-01747-3.',
    Title: 'When Investigator Meets Large Language Models: A Qualitative Analysis of Cancer Patient Decision-Making Journeys',
    Authors: 'Neta Shanwetter Levit; Mor Saban',
    Year: 2025,
    Venue: 'npj Digital Medicine 8: 336',
    'Publication type': 'peer-reviewed journal qualitative-comparative study',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'Published 2025-06-05; PMCID PMC12141523; PMID 40473767.',
    URL: 'https://doi.org/10.1038/s41746-025-01747-3',
    DOI: '10.1038/s41746-025-01747-3',
    'Citation count, source, and retrieval date': 'OpenAlex: 12, checked 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'standalone 33-interview cancer decision-making comparison',
    'Research objective': 'Compare investigator and LLM interpretations of cancer-patient decision-making journeys.',
    'Claimed qualitative methodology': 'qualitative thematic analysis with zero-shot LLM comparison',
    'Actual operationalized methodology': 'Human constant-comparative analysis versus per-transcript LLM theme extraction and unexplained corpus-level synthesis; prompts were refined after early quotation failures.',
    'Inductive, deductive, or hybrid': 'human analysis inductive; LLM nominally zero-shot inductive',
    Domain: 'oncology and patient decision-making',
    'Dataset name': '33 patient interviews',
    'Public or restricted data': 'restricted/not shared',
    'Number of documents': '33 interviews: seven pilot and 26 later',
    'Number of participants': '33 (22 women, 11 men; mean age 56.78, SD 17, range 28–83)',
    'Approximate corpus size': 'word count not reported',
    'Document length': '20–60 minutes each',
    Language: 'Likely Hebrew because Ivrit.AI transcription was used, but transcript/input language and translation are not reported.',
    'Sensitive-data status': 'highly sensitive cancer and personal decision data',
    'Model family': 'OpenAI GPT and Google Gemini',
    'Exact model/version': 'ChatGPT-4o and noncanonical “Gemini Advance Pro1.5”; no snapshots/dates/routes/settings',
    'Prompting strategy': 'Each anonymized transcript prompted for main themes and two quotations; early paraphrase/misattribution prompted several refinements/interventions.',
    'Fine-tuning or adaptation': 'none',
    'Single-agent or multi-agent': 'independent single-model analyses',
    'Agent roles': 'per-transcript theme/quotation extractor and corpus-level synthesizer',
    'Human role': 'Lead trained analyst performs full analysis; second researcher reviews framework; humans inspect/correct final quotations.',
    'Unit of analysis': 'interview transcript, excerpt, and theme',
    'Generated outputs': 'Human five-theme framework, ChatGPT six themes, Gemini three themes, and representative quotations.',
    'Evidence/provenance mechanism': 'Requested quotations, but early misattribution/paraphrase and no shareable transcripts make provenance unauditable.',
    Baselines: 'human analysis and cross-model comparison',
    'Number of runs or seeds': 'not reported; no stability assessment',
    'Automatic metrics': 'none for cross-analysis validity',
    'Human-evaluation design': 'Author comparison of conceptual overlap and quotation checking.',
    'Number and expertise of evaluators': 'lead trained oncology qualitative researcher and second reviewer',
    'Inter-rater reliability': 'Cohen κ=.85 claimed for human work, but unit/subset/independence/calculation missing; “reviewed framework” may not justify κ.',
    'Statistical analysis': 'descriptive demographics and κ only',
    'Principal results': 'Human analysis emphasized emotional coping, trust, support, information/decisions, and quality of life. ChatGPT emphasized emotional/physical impacts, providers, internet/information, family, timeline, and autonomy; Gemini produced emotional meaning, physical/side effects, and second-opinion themes. Authors judge humans deeper and LLMs more logistical; some Gemini quotations weaken construct coherence.',
    'Efficiency or cost results': '“Weeks” human versus “days” LLM plus checking; no measured hours/cost.',
    'Ethics and privacy treatment': 'Tel Aviv IRB 0008350-4, informed consent, withdrawal rights, anonymization; no disclosure of consent for proprietary transfer, API retention, DPA, or cross-border processing.',
    'Reproducibility resources': 'Transcripts unavailable; protocols/prompts reportedly on request; no code/output archive.',
    'Author-reported limitations': 'Zero-shot variability, fabrication, no cross-analysis prompting, recall bias, and limited diversity.',
    'Additional validity concerns': 'Language/translation omitted; no blinding; interviewer familiarity advantages humans; iterative human corpus analysis is not task-matched to vague per-transcript LLM process; no participant validation; “zero-shot” conflicts with corrective iteration.',
    'Relationship to prior papers': 'no duplicate located',
    'Relevance to the proposed ARR project': 'Require task alignment, model/version and multilingual reporting, source verification, participant/domain-expert validation, and explicit API consent/governance.'
  }),
  record({
    'Paper ID': 'zhang_et_al_2025_harnessing_ai_qualitative_research',
    'Full citation': 'Zhang, He, Chuhao Wu, Jingyi Xie, Yao Lyu, Jie Cai, and John M. Carroll. 2025. Harnessing the Power of AI in Qualitative Research: Exploring, Using and Redesigning ChatGPT. Computers in Human Behavior: Artificial Humans 4: 100144. https://doi.org/10.1016/j.chbah.2025.100144.',
    Title: 'Harnessing the Power of AI in Qualitative Research: Exploring, Using and Redesigning ChatGPT',
    Authors: 'He Zhang; Chuhao Wu; Jingyi Xie; Yao Lyu; Jie Cai; John M. Carroll',
    Year: 2025,
    Venue: 'Computers in Human Behavior: Artificial Humans 4: 100144',
    'Publication type': 'peer-reviewed journal user/co-design study',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'Earlier arXiv:2309.10771, titled Redefining Qualitative Analysis in the AI Era, v1 2023-09-19/v3 2024-05-28; journal VOR May 2025. One renamed family.',
    URL: 'https://doi.org/10.1016/j.chbah.2025.100144',
    DOI: '10.1016/j.chbah.2025.100144',
    'Citation count, source, and retrieval date': 'OpenAlex: 80, checked 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'arXiv 2309.10771 and 2025 journal VOR are one renamed family',
    'Research objective': 'Determine how prompt design affects ChatGPT thematic analysis and researcher attitudes, and develop a prompt framework.',
    'Claimed qualitative methodology': 'reflexive thematic analysis plus participatory prompt redesign',
    'Actual operationalized methodology': 'Exploratory think-aloud/coaching sessions: participants self-prompted up to five times, then researchers advised iterative refinement until satisfaction; recordings underwent human RTA.',
    'Inductive, deductive, or hybrid': 'hybrid/inductive',
    Domain: 'qualitative-research methods and HCI',
    'Dataset name': '17 session recordings/transcripts plus one shared remote-work focus-group transcript',
    'Public or restricted data': 'not shared',
    'Number of documents': '17 session records and one task transcript',
    'Number of participants': '17 total: four pilot and 13 formal; 12 women/5 men; ages 20–32; formal sample mostly doctoral researchers',
    'Approximate corpus size': 'not reported',
    'Document length': 'pilot sessions 1–1.5 hours; formal durations not reported',
    Language: 'ChatGPT interactions English; research-interview language not reported',
    'Sensitive-data status': 'participant recordings potentially sensitive; task-transcript provenance/sensitivity unknown',
    'Model family': 'OpenAI GPT',
    'Exact model/version': 'ChatGPT/GPT-3.5; snapshot/date absent; informal GPT-4 check undocumented',
    'Prompting strategy': 'Variable participant prompts plus coached refinements: background, process/method, input/output format, role, prioritization, traceability, and praise.',
    'Fine-tuning or adaptation': 'none',
    'Single-agent or multi-agent': 'single model in human-AI collaboration',
    'Agent roles': 'coding/theme generator and quote/table/rationale producer',
    'Human role': 'Prompts, judges, revises, and is expected to double-check; researchers coach participants.',
    'Unit of analysis': 'task-transcript passage and interaction/session',
    'Generated outputs': 'codes, themes, quotations, tables, rationales, and prompt framework',
    'Evidence/provenance mechanism': 'Prompts encourage excerpts/participant source; self-generated rationales are incorrectly treated as transparency/interpretability.',
    Baselines: 'participants’ initial versus coached prompts, without controlled order/counterbalancing/blinding',
    'Number of runs or seeds': 'up to five initial attempts plus variable refinements; no seeds',
    'Automatic metrics': 'none',
    'Human-evaluation design': 'subjective participant satisfaction, trust, and attitude change',
    'Number and expertise of evaluators': '13 formal participants; researcher team codes session data',
    'Inter-rater reliability': 'none; weekly consensus/reflexive meetings',
    'Statistical analysis': 'none',
    'Principal results': 'Participants reported improved perceived transparency/usability and shifted from skepticism toward acceptance; no objective efficacy result.',
    'Efficiency or cost results': 'perceived time savings only',
    'Ethics and privacy treatment': 'University IRB approval, consent, and US$10 compensation; no protocol ID or commercial-data-transfer discussion.',
    'Reproducibility resources': 'No data, complete interaction logs, prompts, code, or model snapshot.',
    'Author-reported limitations': 'One corpus, limited diversity, roughly one-hour exposure, coding focus, and evolving models.',
    'Additional validity concerns': 'Coached order/demand effects; iterate-until-satisfaction; “significant” wording without tests; many users novice/junior; trust conflated with validity; task-corpus provenance absent.',
    'Relationship to prior papers': 'one arXiv/journal renamed family',
    'Relevance to the proposed ARR project': 'Useful prompting/human-role framework, but trust can rise without validated accuracy; separate usability/trust from validity.'
  }),
  record({
    'Paper ID': 'chen_et_al_2025_processes_matter_open_coding',
    'Full citation': 'Chen, John, Alexandros Lotsos, Grace Wang, Lexie Zhao, Bruce Sherin, Uri Wilensky, and Michael S. Horn. 2025. Processes Matter: How ML/GAI Approaches Could Support Open Qualitative Coding of Online Discourse Datasets. CSCL 2025 Proceedings, 415–418. https://doi.org/10.22318/cscl2025.114185.',
    Title: 'Processes Matter: How ML/GAI Approaches Could Support Open Qualitative Coding of Online Discourse Datasets',
    Authors: 'John Chen; Alexandros Lotsos; Grace Wang; Lexie Zhao; Bruce Sherin; Uri Wilensky; Michael S. Horn',
    Year: 2025,
    Venue: 'CSCL 2025 Proceedings, pages 415–418',
    'Publication type': 'peer-reviewed short conference paper',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'Conference paper and longer arXiv:2504.02887v1 (2025-04-02) are one family.',
    URL: 'https://doi.org/10.22318/cscl2025.114185',
    DOI: '10.22318/cscl2025.114185',
    'Citation count, source, and retrieval date': 'OpenAlex: 1, checked 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'Reuses TA-1334/Chen et al. 2024 Prompts Matter 127-message corpus and codebooks; distinct contribution-analysis paper, not independent replication; code-merging line precedes 2026 Findings paper.',
    'Research objective': 'Evaluate whether and how machine open-coding processes contribute grounded, useful insights beyond human coders.',
    'Claimed qualitative methodology': 'open qualitative coding/grounded-theory support',
    'Actual operationalized methodology': 'Secondary comparison of previously generated human/GPT-4o codebooks, algorithmic code merging, and human contribution/grounding analysis.',
    'Inductive, deductive, or hybrid': 'inductive open coding',
    Domain: 'online educational-design discourse',
    'Dataset name': 'Physics Lab community first-two-month discourse sampled around timestamp peaks',
    'Public or restricted data': 'status unclear; reused research corpus',
    'Number of documents': '127 messages',
    'Number of participants': 'not reported',
    'Approximate corpus size': '340 human codes; 652 machine codes overall; detailed analysis emphasizes 240 item and 282 verb-phrase codes',
    'Document length': 'not reported',
    Language: 'apparently English',
    'Sensitive-data status': 'educational/community discourse, possibly involving youth; anonymization/consent not described here',
    'Model family': 'OpenAI GPT',
    'Exact model/version': 'GPT-4o-2024-05-13 for source outputs; robustness models/settings incompletely enumerated',
    'Prompting strategy': 'Research question, context, and role; no codebook/examples.',
    'Fine-tuning or adaptation': 'none',
    'Single-agent or multi-agent': 'alternative coding workflows plus algorithm/LLM merging; not agents',
    'Agent roles': 'code generator, description generator, embedding/cluster merger, and contribution assessor',
    'Human role': 'Four coders generate baseline codes; researchers assess merged-code grounding and contribution.',
    'Unit of analysis': 'message, code, and merged code',
    'Generated outputs': 'open codes, merged code space, groundedness/broadness labels, unique coverage, and contribution categories',
    'Evidence/provenance mechanism': 'Codes link to messages/examples; evaluators write analytical memos and counterexamples.',
    Baselines: 'four human coders with/without context and five machine workflows',
    'Number of runs or seeds': 'Base generation appears once; appendix mentions six models, five temperatures, and five GPT-4o temperature-.5 repetitions “across 15 runs,” but arithmetic/design are unclear.',
    'Automatic metrics': 'code counts, grounded/overbroad rates, unique coverage, contribution categories, and merge-agreement κ',
    'Human-evaluation design': 'Groundedness/broadness review and blind evaluation of 81 sampled merged codes with contribution/grounding memos.',
    'Number and expertise of evaluators': 'two main code evaluators plus author-team reconciliation',
    'Inter-rater reliability': 'Three-round κ .54, .67, .76; overall .68. Individual agreement with algorithm .78 and .56; one evaluator knew the algorithm.',
    'Statistical analysis': 'descriptive counts and κ; no inferential comparison',
    'Principal results': 'Machine workflows were mostly grounded. Among 57 unique codes in 81 reviewed merged codes, 17 were human-only, 10 shared by both item methods, 10 item-only, 20 verb-only. Twenty made substantial contributions: eight human, two item, ten verb. Humans contributed more conversational dynamics; machines more content coverage.',
    'Efficiency or cost results': 'not reported',
    'Ethics and privacy treatment': 'No IRB, consent, youth/community privacy, or governance statement.',
    'Reproducibility resources': 'Detailed arXiv paper; resources depend on prior/related papers; no standalone repository linked.',
    'Author-reported limitations': 'Single dataset/question, random subset of merged codes, and rapidly evolving models.',
    'Additional validity concerns': 'Subjective author-team contribution judgments; only 81/315 merged codes; evaluator familiarity; unclear robustness arithmetic; no participant/minority coverage analysis.',
    'Relationship to prior papers': 'Dependent reuse of Prompts Matter corpus/codebooks; distinct contribution analysis, not independent dataset replication.',
    'Relevance to the proposed ARR project': 'Strong plurality-aware evaluation: assess unique/substantial contributions, not only agreement; supports parallel co-coder designs and content-versus-conversational-dynamics coverage.'
  }),
  record({
    'Paper ID': 'wei_et_al_2026_childbirth_parenthood_discourse',
    'Full citation': 'Wei, Zheng, Yunqi Li, Yucheng He, Yuelu Li, Xian Xu, Huamin Qu, Pan Hui, and Muzhi Zhou. 2026. Unpacking Discourses on Childbirth and Parenthood in Popular Social Media Platforms Across China, Japan, and South Korea. Proceedings of the International AAAI Conference on Web and Social Media 20(1): 2466–2483. https://doi.org/10.1609/icwsm.v20i1.42761.',
    Title: 'Unpacking Discourses on Childbirth and Parenthood in Popular Social Media Platforms Across China, Japan, and South Korea',
    Authors: 'Zheng Wei; Yunqi Li; Yucheng He; Yuelu Li; Xian Xu; Huamin Qu; Pan Hui; Muzhi Zhou',
    Year: 2026,
    Venue: 'Proceedings of the International AAAI Conference on Web and Social Media 20(1): 2466–2483',
    'Publication type': 'peer-reviewed full conference paper',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'arXiv:2510.06788v1 posted 2025-10-08 and marked accepted at ICWSM 2026; VOR published 2026-05-25. One family.',
    URL: 'https://doi.org/10.1609/icwsm.v20i1.42761',
    DOI: '10.1609/icwsm.v20i1.42761',
    'Citation count, source, and retrieval date': 'OpenAlex: 0, checked 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': '2025 arXiv/2026 ICWSM VOR family',
    'Research objective': 'Compare childbirth/parenthood discourse and stance across China, Japan, and South Korea.',
    'Claimed qualitative methodology': 'hybrid grounded theory and thematic analysis, topic modeling, sentiment classification, and regression',
    'Actual operationalized methodology': 'BERTopic/HDBSCAN clustering followed by human filtering/merging into literature-derived dimensions; hosted Qwen fixed sentiment; video metadata coding and regressions.',
    'Inductive, deductive, or hybrid': 'hybrid, with induction constrained by five preselected dimensions',
    Domain: 'fertility, childbirth, parenthood, gender, and social-media discourse',
    'Dataset name': 'Douyin China and TikTok Japan/Korea childbirth/parenthood corpus',
    'Public or restricted data': 'public posts/comments; full data not released',
    'Number of documents': '668 videos and 219,127 retained comments from 597,105 collected; China 105/74,828, Japan 317/82,887, Korea 246/61,412',
    'Number of participants': 'unique users not reported',
    'Approximate corpus size': '219,127 retained comments; 68,974 comments/24% removed as off-topic after clustering',
    'Document length': 'not reported',
    Language: 'Simplified Chinese, Japanese, and Korean; originals preserved, cross-country theme alignment in English',
    'Sensitive-data status': 'fertility, gender/family attitudes, possible demographics, and Chinese provincial IP-geolocation metadata',
    'Model family': 'BERTopic transformer/HDBSCAN and Alibaba Qwen',
    'Exact model/version': 'Paper says Tongyi Qianwen/Qwen 72B while repository calls hosted Qwen-turbo; embedding model, service snapshot, decoding, and most libraries not reported.',
    'Prompting strategy': 'Six sentiment-prompt refinement rounds on 1,000 comments/language; prompts include video stance/context, while repository passes but does not use title/source arguments.',
    'Fine-tuning or adaptation': 'prompt refinement only',
    'Single-agent or multi-agent': 'sequential topic-model/human-theme/LLM-sentiment pipeline',
    'Agent roles': 'cluster generator, human cluster/theme interpreter, and fixed sentiment labeler',
    'Human role': 'One language-specific coder labels videos, senior reviews 10%; three coders merge clusters; senior family-studies scholar/team align themes; humans validate 1,000 sentiment cases/language.',
    'Unit of analysis': 'video, comment, topic cluster, and theme',
    'Generated outputs': 'clusters, country themes, five dimensions, representative comments, sentiment labels, and regressions',
    'Evidence/provenance mechanism': 'One BERTopic representative document per theme plus topic-tree outputs; full quote/source coverage incomplete.',
    Baselines: 'human sentiment checks; RoBERTa mentioned as worse without comparative results; no topic-model baseline',
    'Number of runs or seeds': 'none reported; stability asserted without repeated-run evidence',
    'Automatic metrics': 'topic counts, κ for theme merging, sentiment accuracy/macro-F1, distributions, regression coefficients/p-values',
    'Human-evaluation design': 'Video-code spot-check, independent cluster merging, and sentiment checks on 1,000 comments/country.',
    'Number and expertise of evaluators': 'one primary video coder/language plus senior checker; three theme coders; sentiment evaluator count/expertise not reported',
    'Inter-rater reliability': 'Average κ=.82 for theme merging; unit, per-country values, and calculation incomplete; no video/sentiment IRR.',
    'Statistical analysis': 'multinomial logit with year fixed effects; multiple-comparison control and clustered errors unclear',
    'Principal results': 'Values dominated China (57.37%); Utility/Cost dominated Japan (34.51/27.01%) and Korea (51.27/16.00%). Anti/pro/neutral: China 50.12/19.98/29.54, Japan 30.03/28.66/41.05, Korea 31.16/32.88/35.57. Independent sentiment accuracy: China 88.4%, Japan 90.2%, Korea 97.7%.',
    'Efficiency or cost results': 'Crawling: 10 hours/day for 15 days China and 19 days Japan/Korea; model compute/API cost not reported.',
    'Ethics and privacy treatment': 'VOR says published content only, usernames removed, photos/videos not saved, geolocation unlikely identifying, with no IRB/consent. Earlier arXiv’s “IRB XXXX” and claimed 10% sample release were removed—a material revision.',
    'Reproducibility resources': 'https://github.com/YuchengHE-CHN/ICWSM-Unpacking-Discourses-on-Childbirth-and-Parenthood includes code/prompts/partial translated outputs, not full data. Code prints API key; only Chinese prompt hard-coded; label semantics conflict across files/paper.',
    'Author-reported limitations': 'Commenters not populations, demographics absent, coarse geolocation, and stochastic/language bias.',
    'Additional validity concerns': '24% cluster removal may erase minority discourse; one coder/language; translation alignment; tuning/validation overfit; platform/period/algorithm confounds; stance-conditioned prompt leakage; nested comments treated independently.',
    'Relationship to prior papers': 'arXiv/VOR one family',
    'Relevance to the proposed ARR project': 'Major multilingual hybrid case; require outlier-preserving evaluation, independent cross-language review, platform controls, source coverage, versioned prompts/models, clustered inference, and repository security checks.'
  }),
];

function qualityVector(paperId, title, classification, vector, rationales) {
  if (vector.length !== 12 || rationales.length !== 12) throw new Error(`quality vector ${paperId}`);
  const scoreMap = Object.fromEntries(dimensions.map((dimension, index) => [dimension, { score: vector[index], rationale: rationales[index] }]));
  return {
    'Paper ID': paperId,
    Title: title,
    'Core or adjacent classification': classification,
    'Dimension scores': scoreMap,
    Total: vector.reduce((a, b) => a + b, 0),
    'Interpretation caution': 'Audit aid only; totals are not study rankings and every dimension must be read with its evidence.'
  };
}

const quality_scores = [
  qualityVector('abramson_et_al_2025_qualitative_research_ai_pragmatic', 'Qualitative Research in an Era of AI: A Pragmatic Approach to Data Analysis, Workflow, and Computation', 'adjacent', [2,2,1,1,1,1,2,2,1,2,2,2], [
    'Pragmatic typology and method-first position are clear.', 'Longitudinal health corpus is appropriate to workflow guidance.', 'Computational pipeline is described but exact models/configurations are incomplete.', 'Manual/prior-work comparisons exist without a clean current baseline.', 'Ongoing team audit is strong but not a formal evaluation.', 'Prior F1 is relevant but provenance-separated poorly.', 'Disconfirming cases and reflexive interpretation are explicit.', 'Stable source/paragraph identifiers are exemplary.', 'Some prior reliability evidence, not a current controlled rerun study.', 'Strong restricted-data/local-processing governance.', 'Teaching/code/templates are public; original data properly restricted.', 'Claims are generally cautious and methodologically proportionate.'
  ]),
  qualityVector('zhang_et_al_2025_rosannotator', 'ROSAnnotator: A Web Application for ROSBag Data Analysis in Human-Robot Interaction', 'core', [1,0,1,0,0,0,0,1,0,1,2,1], [
    'Annotation functions are clear; qualitative method is underspecified.', 'No evaluation dataset.', 'Architecture is described; exact models/prompts are absent.', 'No baseline.', 'No human evaluation.', 'No automatic validity metric.', 'No plurality assessment.', 'Time-linked ROS intervals provide partial provenance.', 'No reruns/seeds.', 'Some local face-frame protection but external audio/privacy gaps.', 'Public code and Docker artifact.', 'Capability claims are limited, though automation implications remain unevaluated.'
  ]),
  qualityVector('sakib_et_al_2025_shortcut_sdoh', 'Spurious Correlations and Beyond: Understanding and Mitigating Shortcut Learning in SDOH Extraction with Large Language Models', 'adjacent', [1,2,1,1,1,1,0,1,0,2,1,1], [
    'Fixed extraction task is clear but not open qualitative interpretation.', 'Large controlled clinical corpus suits shortcut analysis.', 'Prompts/SFT details partial; exact checkpoints incomplete.', 'Multiple models/prompts/SFT provide useful baselines.', 'Inherited annotations only.', 'FPR is useful but incomplete without other error rates/uncertainty.', 'Alternative interpretations are not in scope.', 'Triggers link predictions to notes.', 'No stochastic replication.', 'Secure controlled-data governance and stigma risks are addressed.', 'Prompts/hyperparameters partial; no release.', 'Shortcut warning is warranted; some causal language exceeds deletion design.'
  ]),
  qualityVector('de_paoli_fawzi_2025_tallmesh', 'TALLMesh: A Simple Application for Performing Thematic Analysis with Large Language Models', 'core', [2,0,2,0,0,0,0,1,0,1,2,1], [
    'Pipeline stages and interface are clear.', 'No substantive evaluation dataset.', 'Open code and editable prompts give strong implementation transparency.', 'No baseline.', 'No outcome evaluation.', 'Unique-code ratio is not a validated quality/saturation metric.', 'Forced assignment can suppress plurality.', 'Quotes are retained at code stage but weakened at themes.', 'No stability test.', 'Generic governance advice only.', 'Application and prompts are public.', 'Tool claims are mostly descriptive; saturation/determinism implications overreach.'
  ]),
  qualityVector('borchers_et_al_2026_temperature_persona_consensus', 'Temperature and Persona Shape LLM Agent Consensus With Minimal Accuracy Gains in Qualitative Coding', 'core', [2,2,2,2,1,1,1,2,2,0,2,2], [
    'Factorial coding/agent design is clearly described.', 'Dialogue/codebook corpus fits the deductive question.', 'Models/prompts/results public, with some tag gaps.', 'Human reference and single-agent controls are strong.', 'Reference/trace evaluator reporting is inconsistent.', 'Agreement is relevant but prevalence-aware performance is missing.', 'Persona/trace differences expose some plurality.', 'Utterance-linked traces provide strong auditability.', 'Temperature/persona/model variations are extensive, though seeds absent.', 'No child-data ethics statement.', 'Repository includes prompts, code, and results.', 'Negative conclusion is appropriately strong and cautious.'
  ]),
  qualityVector('rodriguez_et_al_2026_text_chunking_urban', 'Text Chunking in Human-AI Teaming of Document Classification for Urban Systems Management Using Large Language Models', 'core', [1,1,1,1,1,1,0,1,2,2,2,0], [
    'Binary coding task is clear but qualitative framing is loose.', 'Ten papers are small and prevalence-skewed.', 'Core conditions reported; snapshots/parser details incomplete.', 'Whole/chunk/models/humans compared, but reference is weak.', 'Three nonexperts provide labels without expert adjudication.', 'Metrics are relevant yet prevalence and pseudoreplication distort them.', 'No interpretive plurality.', 'Evidence requested but not assessed.', 'Fifteen iterations per configuration are a strength.', 'Public nonsensitive papers.', 'Data/code repository is public.', 'Chunking and κ claims overstate the weak/prevalence-confounded design.'
  ]),
  qualityVector('king_et_al_2025_frontier_privacy_policies', 'User Privacy and Large Language Models: An Analysis of Frontier Developers’ Privacy Policies', 'adjacent', [2,2,1,1,1,1,1,2,0,2,1,2], [
    'Policy-analysis approach and categories are clear.', 'Six major providers/28 documents suit the mapping question.', 'Sources/dates clear; codebook and snapshots unavailable.', 'Cross-provider comparison only.', 'Team cross-review without formal reliability.', 'Descriptive matrix is suitable.', 'Heterogeneous policy wording is preserved partly.', 'URLs/access dates provide good provenance.', 'Point-in-time only; no stability test.', 'Substantive privacy analysis is strong.', 'No archived policy/coded repository.', 'Conclusions mostly proportionate, with one table/prose inconsistency.'
  ]),
  qualityVector('relins_et_al_2025_police_vulnerability', 'Using Instruction-Tuned Large Language Models to Identify Indicators of Vulnerability in Police Incident Narratives', 'core', [2,2,1,1,1,1,1,2,2,1,2,1], [
    'Deductive vulnerability coding is clear.', 'Large real-world police corpus supports classification claims.', 'Prompts/pipeline public; exact models/settings inconsistent.', 'Several models/prompts and human reference, though evaluation is enriched.', 'Two nonexperts/adjudication without IRR is limited.', 'F1/CIs/entropy are useful; collapsed labels/prevalence complicate validity.', 'Inconclusive category and evidence retain some ambiguity.', 'Evidence quotes tied to narratives.', 'Ten repeated labels and entropy analysis are strong.', 'Public-data determination/redaction reported; representational harms remain.', 'OSF and GitHub available.', 'Claims of scale/efficiency exceed biased test sampling and unmeasured labor.'
  ]),
  qualityVector('shanwetter_levit_saban_2025_cancer_llm_qualitative', 'When Investigator Meets Large Language Models: A Qualitative Analysis of Cancer Patient Decision-Making Journeys', 'core', [1,2,0,1,1,0,1,1,0,1,1,1], [
    'Human method clearer than the vague per-transcript LLM synthesis.', 'Authentic 33-interview oncology corpus.', 'Model names/configuration/language route are inadequate.', 'Human and two models compared but tasks are mismatched.', 'Two knowledgeable authors inspect outputs; no blinding/independence.', 'No automatic cross-theme validity metric.', 'Human/model differences are discussed.', 'Quotation provenance failed early and cannot be audited.', 'No reruns/stability.', 'IRB/consent/anonymization reported, but proprietary transfer governance absent.', 'Prompts on request; no data/code/output archive.', 'Human-depth conclusion is plausible but design confounds prevent strong comparison.'
  ]),
  qualityVector('zhang_et_al_2025_harnessing_ai_qualitative_research', 'Harnessing the Power of AI in Qualitative Research: Exploring, Using and Redesigning ChatGPT', 'core', [1,1,1,1,1,0,1,1,0,1,0,0], [
    'Participant workflow is described; claimed RTA and objective efficacy are unclear.', 'One shared transcript and 17 sessions support usability, not validity.', 'Prompt factors reported; full logs/version/settings absent.', 'Initial-versus-coached order is uncontrolled.', 'Participant satisfaction is rich but demand-prone.', 'No objective metric.', 'Some researcher attitudes/interpretations preserved.', 'Source excerpts requested; rationales are not true interpretability.', 'Variable retries without stability design.', 'IRB/consent reported; model-transfer details absent.', 'No reusable artifacts.', 'Trust/usability and “significant” improvement language exceed evidence.'
  ]),
  qualityVector('chen_et_al_2025_processes_matter_open_coding', 'Processes Matter: How ML/GAI Approaches Could Support Open Qualitative Coding of Online Discourse Datasets', 'core', [2,1,1,1,2,1,2,2,1,0,1,2], [
    'Open-coding/contribution analysis is clearly framed.', 'One small reused corpus limits transfer.', 'Model/workflow mostly reported; robustness arithmetic unclear.', 'Four humans and five workflows provide comparison, with dataset dependence.', 'Blind sampled code review and memos are unusually strong.', 'Counts/κ fit merging but no inferential uncertainty.', 'Unique contributions and conversational/content differences center plurality.', 'Codes link to messages/examples and counterexamples.', 'Some model/temperature repeats; design accounting incomplete.', 'No youth/community ethics statement.', 'Long paper exists; standalone repository absent.', 'Conclusions carefully distinguish contribution from agreement.'
  ]),
  qualityVector('wei_et_al_2026_childbirth_parenthood_discourse', 'Unpacking Discourses on Childbirth and Parenthood in Popular Social Media Platforms Across China, Japan, and South Korea', 'core', [2,1,2,1,1,1,1,1,0,1,1,1], [
    'Hybrid topic/human-theme/sentiment pipeline is clear.', 'Large multilingual corpus, but platforms/countries are confounded.', 'Repository exposes code/prompts and also serious paper/code contradictions.', 'Human checks exist; no topic-model alternative and weak sentiment baseline.', 'Human review exists but one coder/language and incomplete evaluator details.', 'Accuracy/F1/κ/regression are useful with clustering/tuning caveats.', 'Cross-country themes preserve some diversity; 24% removal threatens outliers.', 'Representative documents only; full source coverage incomplete.', 'No repeated-run stability despite claim.', 'Deidentification discussed, but IRB/preprint-VOR revision is concerning.', 'Repository partial and leaks API key; models/prompts inconsistent.', 'Cross-country claims exceed platform and nested-data controls.'
  ])
];

const full_text_decisions = [
  ['TA-0795', 'include_adjacent', 'Methodological/privacy/provenance guidance with illustrative workflow; no direct current LLM code/theme evaluation.'],
  ['TA-0809', 'include_core', 'Direct LLM-assisted qualitative annotation tool; retained as unvalidated infrastructure.'],
  ['TA-0827', 'include_adjacent', 'Fixed-label clinical extraction outside open interpretation, but shortcut/subgroup evidence directly informs validity.'],
  ['TA-0837', 'include_core', 'Direct end-to-end LLM thematic-analysis system paper.'],
  ['TA-0838', 'include_core', 'Direct controlled same-model agent consensus study; current 2026 EDM VOR represents 2025 preprint family.'],
  ['TA-0840', 'include_core', 'Direct repeated document-coding/chunking study; current 2026 journal VOR represents 2025 preprint family.'],
  ['TA-0873', 'include_adjacent', 'Human policy analysis directly informs privacy/retention/training governance.'],
  ['TA-0876', 'include_core', 'Direct repeated deductive qualitative coding of police narratives, with methodological-incongruence caveat.'],
  ['TA-0883', 'include_core', 'Direct human-versus-LLM thematic comparison on oncology interviews.'],
  ['TA-1121', 'include_core', 'One renamed arXiv/journal family; direct prompt/usability study for ChatGPT thematic coding.'],
  ['TA-1332', 'include_core', 'Distinct contribution-analysis paper reusing TA-1334 corpus/codebooks; not an independent dataset replication.'],
  ['TA-1354', 'exclude_after_full_text', 'LLMs perform only fixed sentiment classification; thematic analysis of 100 tweets is wholly manual.'],
  ['TA-1355', 'include_core', 'BERTopic directly structures comments for human themes and Qwen supplies sentiment; current 2026 ICWSM VOR represents 2025 preprint family.']
].map(([screen_id, decision, reason]) => ({ screen_id, decision, reason, full_text_inspected: true }));

const output = {
  metadata: {
    title: '2025 database-candidate full-text assessment batch 05 plus cross-stream handoffs',
    generated_utc: new Date().toISOString(),
    source_screen: 'research/screening_2025_resolution.json and root cross-stream handoff',
    screen_ids: full_text_decisions.map((item) => item.screen_id),
    retrieved_count: 13,
    assessed_count: 13,
    include_core_count: 9,
    include_adjacent_count: 3,
    exclude_count: 1,
    merge_status: 'candidate-only; do not merge until parent review',
    version_note: 'TA-0838, TA-0840 and TA-1355 are extracted once under their current 2026 peer-reviewed VORs; TA-1121 uses the 2025 renamed journal VOR; TA-1332 is distinct but dependent reuse of TA-1334 data/codebooks. TA-1354 is excluded after full text and has no evidence/quality record.',
    extraction_columns: columns,
    extraction_column_count: columns.length,
    quality_dimensions: dimensions,
    quality_scoring: prior.metadata.quality_scoring
  },
  full_text_decisions,
  evidence_records,
  quality_scores
};

if (evidence_records.length !== 12 || quality_scores.length !== 12) throw new Error('batch counts');
if (evidence_records.some((item) => Object.keys(item).length !== 52)) throw new Error('52-field failure');
if (quality_scores.some((item) => Object.keys(item['Dimension scores']).length !== 12)) throw new Error('12-dimension failure');

fs.writeFileSync(new URL('./screening_2025_database_fulltext_batch05.json', import.meta.url), `${JSON.stringify(output, null, 2)}\n`);
