import fs from 'node:fs';

const prior = JSON.parse(fs.readFileSync(new URL('./screening_2025_database_fulltext_batch04.json', import.meta.url)));
const columns = prior.metadata.extraction_columns;
const dimensions = prior.metadata.quality_dimensions;

function record(values) {
  const out = Object.fromEntries(columns.map((column) => [column, values[column] ?? 'not reported']));
  const extra = Object.keys(values).filter((key) => !columns.includes(key));
  if (extra.length || Object.keys(out).length !== 52) throw new Error(`invalid evidence record: ${extra.join(', ')}`);
  return out;
}

function quality(paperId, title, classification, scores) {
  const names = Object.keys(scores);
  if (names.length !== 12 || dimensions.some((dimension) => !names.includes(dimension))) {
    throw new Error(`invalid quality score: ${paperId}`);
  }
  return {
    'Paper ID': paperId,
    Title: title,
    'Core or adjacent classification': classification,
    'Dimension scores': scores,
    Total: Object.values(scores).reduce((sum, item) => sum + item.score, 0),
    'Interpretation caution': 'Audit aid only; totals are not study rankings and every dimension must be read with its evidence.'
  };
}

const evidence_records = [
  record({
    'Paper ID': 'cook_et_al_2025_ai_qda_promises_pitfalls',
    'Full citation': "Cook, David A., Shiphra Ginsburg, Adam P. Sawatsky, Ayelet Kuper, and Jonathan D. D'Angelo. 2025. Artificial Intelligence to Support Qualitative Data Analysis: Promises, Approaches, Pitfalls. Academic Medicine 100(10): 1134–1149. https://doi.org/10.1097/ACM.0000000000006134.",
    Title: 'Artificial Intelligence to Support Qualitative Data Analysis: Promises, Approaches, Pitfalls',
    Authors: "David A. Cook; Shiphra Ginsburg; Adam P. Sawatsky; Ayelet Kuper; Jonathan D. D'Angelo",
    Year: 2025,
    Venue: 'Academic Medicine 100(10): 1134–1149',
    'Publication type': 'peer-reviewed journal article combining an exploratory case report, limited scoping review, and critical appraisal',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'Received 2024-10-04; revised through 2025-04-04; accepted 2025-04-14; published online 2025-06-25; October 2025 issue.',
    URL: 'https://academic.oup.com/academicmedicine/article/100/10/1134/8361603',
    DOI: '10.1097/ACM.0000000000006134',
    'Citation count, source, and retrieval date': 'not collected; official publisher full HTML inspected 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'standalone case experiment plus scoping review; no duplicate report identified in the 2025 screen',
    'Research objective': 'Critically appraise how AI can support qualitative data analysis through an out-of-the-box ChatGPT-4 experiment, a limited scoping review, and methodological/ethical synthesis.',
    'Claimed qualitative methodology': 'qualitative data analysis case report plus scoping review of AI-supported QDA',
    'Actual operationalized methodology': 'The authors iteratively prompted ChatGPT-4 in February 2024 to reanalyze three existing narrative datasets and documented task successes/failures; separately, one reviewer searched six sources in February/May 2024, screened 483 items, and extracted 130 included publications.',
    'Inductive, deductive, or hybrid': 'hybrid attempted QDA functions (inductive themes, counting, summarization, quotation support) plus descriptive evidence mapping',
    Domain: 'health professions education / qualitative research methodology',
    'Dataset name': 'three existing narrative datasets: medical-student goals, physician survey comments, and Environmental Data Initiative qualitative-data-reuse interviews',
    'Public or restricted data': 'mixed; dataset 3 came from an open repository, while datasets 1–2 were existing author-held/unpublished narrative data',
    'Number of documents': '30 student response pairs; 211 physician free-text responses; 3 interview transcripts selected from a 30-interview repository dataset',
    'Number of participants': '30 third-year medical students; 211 physicians; 3 interviewed researchers in the analyzed subset',
    'Approximate corpus size': '1,380 words; 7,419 words; 19,207 words, respectively',
    'Document length': 'dataset 3 transcripts were approximately 6,000 words each; exact lengths for individual short responses not reported',
    Language: 'English for the case experiment; review included any language and used automated translation for Spanish, Tagalog, and Chinese papers',
    'Sensitive-data status': 'existing narrative human-participant data; the article discusses confidentiality risks but does not report transmitting direct identifiers',
    'Model family': 'OpenAI GPT',
    'Exact model/version': 'ChatGPT-4 as available in February 2024; API snapshot, temperature, seed, and system configuration not reported',
    'Prompting strategy': 'iterative natural-language prompts moving from multistep whole-task requests to progressively clarified/simplified requests; verbatim prompts are in Supplemental Digital Appendix 1',
    'Fine-tuning or adaptation': 'none',
    'Single-agent or multi-agent': 'single general-purpose chatbot',
    'Agent roles': 'summarizer, inductive theme generator, keyword/theme counter, sentiment labeler, quotation selector, and attempted visualizer/cross-theme analyst',
    'Human role': 'authors selected data/tasks, iteratively revised prompts, manually checked outputs against source texts, judged usefulness, conducted the review, and retained interpretive responsibility',
    'Unit of analysis': 'short narrative response, interview transcript, proposed theme/code, and supporting quotation',
    'Generated outputs': 'summaries, themes/categories, prevalence counts, sentiment labels, quotations, word-cloud attempts, and task-specific narrative outputs',
    'Evidence/provenance mechanism': 'Authors manually compared generated outputs with input data and report concrete failures; the supplement preserves prompts, but no machine-readable output-to-source audit package was verified.',
    Baselines: 'source texts and author judgment; no independent human thematic analysis was systematically scored against the model for all tasks',
    'Number of runs or seeds': 'multiple iterative prompts and repeat attempts; exact run count and seeds not reported; authors observed widely divergent rerun outputs',
    'Automatic metrics': 'none for the case experiment; the scoping review reports descriptive counts/percentages',
    'Human-evaluation design': 'informal expert inspection of output accuracy, task fulfillment, quotation support, and utility; not a blinded or preregistered evaluation',
    'Number and expertise of evaluators': 'five author-methodologists/medical educators; task-by-task evaluator assignment and independent ratings not reported',
    'Inter-rater reliability': 'not calculated for the ChatGPT experiment; scoping-review screening/extraction was performed by one author',
    'Statistical analysis': 'descriptive counts only; no inferential testing',
    'Principal results': 'Brief summaries were accurate, but initial prompts failed for all other attempted tasks. Iteration rescued some counting/summarization tasks, while thematic analysis, highlighting, word-tree diagrams, and cross-theme insights remained unsatisfactory. Errors included impossible counts, unsupported/reused quotations, superficial catch-all categories, hallucinated word-cloud terms, failed instruction following, and unstable reruns. The review retained 130 of 483 records, including 104 original studies.',
    'Efficiency or cost results': 'no timed or monetary comparison; the context-window forced selection of only 3 of 30 long interviews',
    'Ethics and privacy treatment': 'Substantial discussion of consent, confidentiality, commercial model retention, reidentification, fraud, workforce effects, and preserving a human in the loop; case-study ethics approval/consent status for reuse is not separately reported in the article text inspected.',
    'Reproducibility resources': 'Supplemental Digital Appendices include prompts, review details, and the included-study list; dataset 3 is repository-sourced, but complete experiment outputs/code/model settings were not provided.',
    'Author-reported limitations': 'Authors call the case experiment extemporaneous and attribute failure partly to their limited prompt sophistication; the review had one reviewer, limited extraction, and possible omissions; model capabilities change rapidly.',
    'Additional validity concerns': 'No independent blinded reference analysis or quantitative scoring, author-selected tasks/subsets, uncertain run accounting, and an unspecified ChatGPT-4 snapshot limit performance inference. The review’s broad definition of AI/QDA is wider than this review’s LLM-centered scope.',
    'Relationship to prior papers': 'Synthesizes 130 earlier AI-QDA publications and directly tests three previously collected datasets; not an independent reanalysis benchmark family with a fixed gold standard.',
    'Relevance to the proposed ARR project': 'High-value negative evidence: require atomic prompts, source-linked outputs, explicit context-window accounting, reruns, deterministic arithmetic checks, and expert human adjudication before treating fluent output as analysis.'
  }),
  record({
    'Paper ID': 'zambrano_et_al_2025_data_theory_codebook',
    'Full citation': 'Zambrano, Andres Felipe, Jiayi Zhang, Jaclyn Ocumpaugh, Xiner Liu, Luc Paquette, Conrad Borchers, Zhanlan Wei, Ryan S. Baker, Amanda Barany, Yiqiu Zhou, and Jeffrey Ginger. 2025. Data Plus Theory Equals Codebook: Leveraging LLMs for Human-AI Codebook Development. OSF Preprints. https://doi.org/10.35542/osf.io/4wyqc_v1.',
    Title: 'Data Plus Theory Equals Codebook: Leveraging LLMs for Human-AI Codebook Development',
    Authors: 'Andres Felipe Zambrano; Jiayi Zhang; Jaclyn Ocumpaugh; Xiner Liu; Luc Paquette; Conrad Borchers; Zhanlan Wei; Ryan S. Baker; Amanda Barany; Yiqiu Zhou; Jeffrey Ginger',
    Year: 2025,
    Venue: 'OSF Preprints',
    'Publication type': 'preprint',
    'Peer-reviewed status': 'not peer reviewed; no archival venue verified',
    'Publication history notes': 'Version 1 registered on OSF in 2025; inspected OSF-hosted DOCX full text.',
    URL: 'https://osf.io/4wyqc/',
    DOI: '10.35542/osf.io/4wyqc_v1',
    'Citation count, source, and retrieval date': 'not collected; official OSF full text inspected 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'extends the authors’ prior SRL/AIED codebook-development work; no archival version identified',
    'Research objective': 'Test whether GPT-4o can support theory-informed qualitative codebook development and how varying the amount of theory supplied changes practical utility and theoretical alignment.',
    'Claimed qualitative methodology': 'human–AI, theory-driven qualitative codebook development across self-regulated learning and interest-development studies',
    'Actual operationalized methodology': 'Study 1 combined named SRL theories, 955 think-aloud utterances, GPT-4o-generated constructs/examples, and first/second-author consolidation. Study 2 generated 12 codebooks from four theory-context prompt conditions (three runs each), consolidated them, and had five coauthor experts score seven qualities.',
    'Inductive, deductive, or hybrid': 'hybrid: deductive theoretical frames with inductive operationalization and human refinement',
    Domain: 'learning sciences / educational data mining',
    'Dataset name': 'SRL think-aloud corpus from three intelligent tutoring systems; 2024 WHIMC middle-school camp interview corpus',
    'Public or restricted data': 'SRL data available by request through DataShop (project IDs 5371 and 5820); WHIMC interview data restricted; codebook artifacts shared through view-only OSF project',
    'Number of documents': '955 utterances in Study 1; 144 interview transcripts in Study 2',
    'Number of participants': '15 students in Study 1; 14 middle-school students in Study 2',
    'Approximate corpus size': '955 segmented utterances; 144 interview transcripts from a five-day, 15-hour camp',
    'Document length': 'Study 1 sessions lasted 45–60 minutes with up to 20 minutes of think-aloud; Study 2 transcript lengths not reported',
    Language: 'English',
    'Sensitive-data status': 'human-student educational data, including minors in Study 2; parental consent and participant assent are reported for the camp',
    'Model family': 'OpenAI GPT',
    'Exact model/version': 'gpt-4o-2024-08-06 in Study 1; gpt-4o-2024-11-20 in Study 2; temperature 0',
    'Prompting strategy': 'Theory- and data-grounded prompts; Study 2 compares no theory, theory named, full bibliographic references, and full theory papers, with three generations per condition.',
    'Fine-tuning or adaptation': 'none',
    'Single-agent or multi-agent': 'single LLM with repeated independent generations',
    'Agent roles': 'construct/codebook generator, definition/example proposer, and theory operationalizer',
    'Human role': 'Researchers selected theories/data, designed prompts, consolidated generations, removed/revised constructs, and evaluated codebooks; the final codebooks are human-refined rather than autonomous model outputs.',
    'Unit of analysis': 'utterance or interview transcript as evidence for theory-linked constructs; generated construct/codebook entry as evaluation object',
    'Generated outputs': 'construct lists, definitions, inclusion/exclusion guidance, examples, and condition-specific codebooks',
    'Evidence/provenance mechanism': 'Codebook constructs include examples and are grounded in supplied corpora/theory; an OSF artifact package is linked, though the full generation-to-source lineage and every refinement decision are not machine-auditable.',
    Baselines: 'four prompting conditions and human refinement; no independently built human-only codebook evaluated under the same seven-dimension rubric',
    'Number of runs or seeds': 'three runs per Study 2 condition (12 codebooks); temperature 0; Study 1 run accounting is not fully enumerated',
    'Automatic metrics': 'descriptive construct counts only',
    'Human-evaluation design': 'Five author evaluators scored consolidated Study 2 codebooks on usefulness, clarity, examples, concreteness, exhaustiveness, complementarity, and theoretical alignment.',
    'Number and expertise of evaluators': 'five coauthor learning-sciences researchers; first two authors also consolidated/refined outputs',
    'Inter-rater reliability': 'not reported for the seven-dimension ratings',
    'Statistical analysis': 'descriptive mean ratings; no inferential tests or uncertainty estimates',
    'Principal results': 'Study 1 produced an 11-construct human-refined SRL codebook without adding constructs beyond the model proposals. In Study 2, merely naming the theory scored highest on six of seven practical criteria, while supplying full papers scored highest on theoretical alignment (4.60 versus 3.60 for theory named) but lower on applicability; condition differences were not inferentially tested.',
    'Efficiency or cost results': 'no measured time, token, energy, or monetary cost',
    'Ethics and privacy treatment': 'Parental consent and participant assent are reported for the minor camp participants; direct identifiers are not described in prompts. Broader training-data and hallucination risks are discussed.',
    'Reproducibility resources': 'OSF artifact project https://osf.io/g3z4x/?view_only=1effdfc734c64f0db13bd59aed931ae6; model snapshots, temperature, conditions, and several data-access identifiers are reported.',
    'Author-reported limitations': 'Theories and datasets differ structurally; model pretraining may distort theory; general-purpose GPT-4o may not transfer; codebooks still need question-specific refinement and later coding validation.',
    'Additional validity concerns': 'Evaluators are unblinded coauthors, the evaluated objects were human-consolidated, no human-only baseline or formal IRR exists, and seven ordinal ratings are reported without uncertainty. “Naming theory” may benefit from model training-data familiarity and cannot isolate theory knowledge from leakage.',
    'Relationship to prior papers': 'Builds on Zambrano et al. automated-coding/code-refinement work, Barany et al. 2024 codebook development, and prior SRL data analyses; dependence should be acknowledged when counting distinct datasets.',
    'Relevance to the proposed ARR project': 'Directly motivates controlled context ablations, exact model/version logging, blinded external evaluation, a human-only codebook baseline, and immutable provenance from source excerpts through generated and human-refined codebooks.'
  }),
  record({
    'Paper ID': 'parfenova_et_al_2025_emergent_convergence',
    'Full citation': 'Parfenova, Angelina, Alexander Denzler, and Juergen Pfeffer. 2025. Emergent Convergence in Multi-Agent LLM Annotation. Proceedings of the 2025 Conference on Empirical Methods in Natural Language Processing Workshop on BlackboxNLP, 206–225. https://doi.org/10.18653/v1/2025.blackboxnlp-1.12.',
    Title: 'Emergent Convergence in Multi-Agent LLM Annotation',
    Authors: 'Angelina Parfenova; Alexander Denzler; Juergen Pfeffer',
    Year: 2025,
    Venue: 'BlackboxNLP 2025, pages 206–225',
    'Publication type': 'peer-reviewed workshop proceedings paper',
    'Peer-reviewed status': 'peer reviewed workshop paper in ACL Anthology proceedings',
    'Publication history notes': 'Archival ACL Anthology version; a matching arXiv record is part of the same publication family.',
    URL: 'https://aclanthology.org/2025.blackboxnlp-1.12/',
    DOI: '10.18653/v1/2025.blackboxnlp-1.12',
    'Citation count, source, and retrieval date': 'not collected; official ACL Anthology PDF inspected 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'ACL/arXiv publication family; one retained report',
    'Research objective': 'Characterize how discussion among heterogeneous LLM annotators changes code convergence, semantic diversity, influence, confidence, and representational structure.',
    'Claimed qualitative methodology': 'multi-agent qualitative annotation/coding experiment',
    'Actual operationalized methodology': 'Five LLMs independently produced short qualitative codes for 500 high-disagreement toxicity comments, then saw accumulated summaries of other agents’ prior outputs over 1–5 fixed-order rounds in 2-, 3-, and 5-model configurations and five prompt variants.',
    'Inductive, deductive, or hybrid': 'inductive short-code generation conditioned on evolving peer outputs',
    Domain: 'NLP annotation / online toxicity discourse',
    'Dataset name': 'Jigsaw Unintended Bias in Toxicity Classification high-disagreement subset',
    'Public or restricted data': 'public benchmark dataset; exact 500-item sample and complete outputs were not located in a repository',
    'Number of documents': '500 English comments',
    'Number of participants': 'not applicable; public online comments with original annotator labels',
    'Approximate corpus size': '7,500 multi-agent discussions and approximately 125,000 generated utterances across configurations',
    'Document length': 'comments were sampled with a minimum length of 100 words; full distribution not reported',
    Language: 'English',
    'Sensitive-data status': 'public toxicity comments may contain harmful or identity-related content; the paper treats them as public benchmark data',
    'Model family': 'Meta Llama, DeepSeek, Google Gemma, and Mistral',
    'Exact model/version': 'Llama 4 Maverick; Llama 3.3 70B; DeepSeek-R1 70B; Gemma and Mistral variants named without fully reproducible checkpoints/configuration in the inspected text',
    'Prompting strategy': 'five coding prompts; agents receive accumulated summaries of other models’ preceding outputs between fixed-order rounds',
    'Fine-tuning or adaptation': 'none reported',
    'Single-agent or multi-agent': 'multi-agent, with 2-, 3-, and 5-model groups',
    'Agent roles': 'peer qualitative coders whose prior-round summaries become context for subsequent coding',
    'Human role': 'Researchers selected the dataset/configurations/prompts and interpreted convergence; no human qualitative expert judged code quality or meaning preservation.',
    'Unit of analysis': 'comment-level generated code and model-round trajectory',
    'Generated outputs': 'short qualitative codes, round summaries, confidence language, convergence trajectories, and representation diagnostics',
    'Evidence/provenance mechanism': 'Outputs remain associated with comment/configuration/round in the experimental analysis, but no public machine-readable lineage package for the 125,000 utterances was verified.',
    Baselines: 'round-1 independent outputs, different group sizes, round depths, prompts, and model mixtures; no human-code or oracle-quality baseline',
    'Number of runs or seeds': '500 discussions per configuration, 7,500 discussions overall; generation seeds and repeat replications of identical configurations are not reported',
    'Automatic metrics': 'ROUGE-1/2/L, sentence-embedding cosine similarity, UMAP, TwoNN intrinsic dimensionality, TF-IDF self-consistency, lexical confidence, toxicity, and 190 ELFEN linguistic features',
    'Human-evaluation design': 'none',
    'Number and expertise of evaluators': 'none for code validity or interpretive quality',
    'Inter-rater reliability': 'not applicable; model-model similarity is not human inter-rater reliability',
    'Statistical analysis': 'descriptive trajectory and configuration comparisons; inferential uncertainty across comments/configurations is limited',
    'Principal results': 'Model outputs generally converge lexically and semantically while intrinsic dimensionality contracts. Peak final-round ROUGE-L reached 0.807 in a three-model/four-round Prompt-1 setting; intrinsic dimensionality dropped sharply in several group sizes. Influence shifted across models over rounds. The same convergence may represent semantic flattening rather than better codes.',
    'Efficiency or cost results': 'no monetary, latency, energy, or human-time evaluation',
    'Ethics and privacy treatment': 'Authors note use of an existing public dataset, no new human-subject collection, and risks from biased/toxic content; no detailed treatment of original commenters’ consent or downstream representational harm.',
    'Reproducibility resources': 'ACL paper and mathematical/experimental descriptions are public; no verified code/output repository and several exact model serving details are missing.',
    'Author-reported limitations': 'Convergence is not necessarily truth or quality; models may reinforce bias, collapse diversity, and depend on prompt/model composition.',
    'Additional validity concerns': 'All headline evidence is model-output similarity without human semantic adjudication; ROUGE and embedding compression reward homogenization. Fixed interaction order, accumulated summaries, incomplete checkpoint details, and no replicated seeds confound social influence with context accumulation.',
    'Relationship to prior papers': 'Distinct multi-agent annotation study; matching preprint/ACL records should count once.',
    'Relevance to the proposed ARR project': 'Strong warning that agent agreement is not validity. ARR evaluation should pair convergence with blinded human quality, minority/edge-case retention, source grounding, order randomization, and stability across seeds.'
  }),
  record({
    'Paper ID': 'zhang_et_al_2025_qualigpt_inductive_deductive',
    'Full citation': 'Zhang, He, Chuhao Wu, Jingyi Xie, Fiona Rubino, Sydney Graver, Jie Cai, ChanMin Kim, and John M. Carroll. 2025. Exploring Inductive and Deductive Qualitative Coding with AI: Investigating Inter-Rater Reliability between Large Language Model and Human Coders. Human-Computer Interaction & Emerging Technologies 195: 142–152. https://doi.org/10.54941/ahfe1006232.',
    Title: 'Exploring Inductive and Deductive Qualitative Coding with AI: Investigating Inter-Rater Reliability between Large Language Model and Human Coders',
    Authors: 'He Zhang; Chuhao Wu; Jingyi Xie; Fiona Rubino; Sydney Graver; Jie Cai; ChanMin Kim; John M. Carroll',
    Year: 2025,
    Venue: 'Human-Computer Interaction & Emerging Technologies, AHFE 2025, volume 195, pages 142–152',
    'Publication type': 'peer-reviewed conference proceedings paper',
    'Peer-reviewed status': 'peer reviewed proceedings paper',
    'Publication history notes': 'Official AHFE Open Access proceedings version inspected.',
    URL: 'https://doi.org/10.54941/ahfe1006232',
    DOI: '10.54941/ahfe1006232',
    'Citation count, source, and retrieval date': 'not collected; official proceedings PDF inspected 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'QualiGPT tool paper; distinct from later/related Penn State qualitative-analysis workflow papers but shares authors/tool lineage',
    'Research objective': 'Evaluate LLM support for inductive and deductive qualitative coding and introduce the QualiGPT API workflow.',
    'Claimed qualitative methodology': 'inductive and deductive qualitative coding with human–LLM intercoder-reliability comparison',
    'Actual operationalized methodology': 'From 1,000 public TwitchDev Discord posts, topic modeling selected two topics and 200 posts for two-RA open coding. Researchers consolidated 171 labels into a 54-label codebook, then two RAs and three independent GPT-4 runs coded another 200 posts; GPT-4o and Claude 3.5 were also tested.',
    'Inductive, deductive, or hybrid': 'both: inductive open labeling followed by deductive multi-label codebook application',
    Domain: 'HCI / Twitch developer-community discourse',
    'Dataset name': '1,000 TwitchDev public Discord posts',
    'Public or restricted data': 'source messages described as public; the analyzed dataset itself was not verified as released',
    'Number of documents': '1,000 total posts; 200 inductive and a separate 200 deductive evaluation entries',
    'Number of participants': 'unknown number of Discord users; two research assistants plus one senior researcher for human codebook work',
    'Approximate corpus size': '1,000 posts; 400 sampled evaluation entries',
    'Document length': 'single Discord entries; distribution not reported',
    Language: 'English is implied by prompts/examples but not explicitly stated',
    'Sensitive-data status': 'public community messages; authors say sensitive user data were excluded, but operational criteria and consent/ethics review are not reported',
    'Model family': 'OpenAI GPT and Anthropic Claude',
    'Exact model/version': 'GPT-4, GPT-4o, and Claude 3.5; exact snapshots not reported; default temperature 0.7',
    'Prompting strategy': 'role/task/background/data-format/output-format template; inductive prompts requested one code per entry and deductive prompts supplied the 54-label codebook; malformed outputs could be regenerated',
    'Fine-tuning or adaptation': 'none; API prompt customization only',
    'Single-agent or multi-agent': 'single model per run; model outputs are compared as coders',
    'Agent roles': 'open-code generator and deductive multi-label coder',
    'Human role': 'Two RAs independently open-coded, consolidated/refined a codebook with a senior researcher, deductively coded the evaluation set, selected prompt regenerations, and remained final validators.',
    'Unit of analysis': 'Discord post',
    'Generated outputs': 'open labels/themes, deductive multi-label assignments, codebook-support artifacts, and QualiGPT tables',
    'Evidence/provenance mechanism': 'QualiGPT stores original text beside assigned codes and indices; the paper does not provide a public immutable dataset/output package or a full trail of regenerated responses.',
    Baselines: 'two human RAs, GPT-4 repeated three times, GPT-4o, and Claude 3.5; no expert gold adjudication or held-out codebook-development split',
    'Number of runs or seeds': 'three independent GPT-4 deductive runs; one reported run each for GPT-4o and Claude 3.5; seeds not reported',
    'Automatic metrics': 'Cohen’s kappa for inductive human–GPT mapping; Fleiss’ kappa for deductive coder sets',
    'Human-evaluation design': 'Human labels and codebook serve as comparison; no blinded expert quality rating of model-discovered themes',
    'Number and expertise of evaluators': 'two research assistants and one senior researcher; domain/qualitative expertise not fully characterized',
    'Inter-rater reliability': 'Inductive human–GPT Cohen’s κ=.57; deductive human-human κ=.73; RA1+RA2+GPT-4 Fleiss κ=.44–.50 (mean .46); GPT-4 self-agreement κ=.87; RA1+RA2+GPT-4o κ=.38; RA1+RA2+Claude 3.5 κ=.42.',
    'Statistical analysis': 'descriptive kappa comparisons; no confidence intervals, significance tests, or prevalence-adjusted sensitivity analysis',
    'Principal results': 'GPT-4 showed moderate agreement with human open coding and lower agreement with humans than the two RAs achieved with each other in deductive coding. GPT-4 was internally consistent, but newer GPT-4o/Claude comparisons were lower. These results support assistance, not the article’s stronger implication of maintained contextual depth or standardized validity.',
    'Efficiency or cost results': 'Manual coding is described as hours/week, but no controlled time, latency, token, or monetary comparison is reported',
    'Ethics and privacy treatment': 'QualiGPT is framed as addressing privacy and sensitive user data were excluded; no IRB/consent decision, deidentification protocol, or platform-terms analysis is reported.',
    'Reproducibility resources': 'QualiGPT repository: https://github.com/KindOPSTAR/QualiGPT; exact data, model snapshots, complete prompts/outputs, and regeneration log were not verified as available.',
    'Author-reported limitations': 'Prompt engineering, domain-specific training, fabricated content, model evolution, and need for human oversight.',
    'Additional validity concerns': 'Open-code mapping for κ is underexplained; multi-label Fleiss κ assumptions are unclear; codebook creation and evaluation are not cleanly independent; temp=.7 plus output regeneration creates selection risk; no qualitative expert gold standard or confidence intervals.',
    'Relationship to prior papers': 'Shares QualiGPT/Penn State author and tool lineage; treat datasets/contributions separately but avoid calling each paper an independent system family.',
    'Relevance to the proposed ARR project': 'Motivates exact multi-label metric definitions, adjudicated mappings, fixed regeneration rules, prompt/model snapshots, split development/evaluation data, external experts, and confidence intervals rather than a single κ headline.'
  }),
  record({
    'Paper ID': 'nguyen_trung_nguyen_2026_nita',
    'Full citation': 'Nguyen-Trung, Kien, and Ngoc Lan Nguyen. 2026. Narrative-Integrated Thematic Analysis (NITA): How Can LLMs Support Theme Generation Without Coding? Qualitative Research in Psychology. https://doi.org/10.1080/14780887.2026.2638348. (2025 SSRN preprint: https://doi.org/10.2139/ssrn.5163884.)',
    Title: 'Narrative-Integrated Thematic Analysis (NITA): How Can LLMs Support Theme Generation Without Coding?',
    Authors: 'Kien Nguyen-Trung; Ngoc Lan Nguyen',
    Year: 2026,
    Venue: 'Qualitative Research in Psychology, online first',
    'Publication type': 'peer-reviewed journal article; publication family originated as a 2025 SSRN preprint',
    'Peer-reviewed status': 'peer reviewed current version',
    'Publication history notes': 'The screened 2025 record was SSRN DOI 10.2139/ssrn.5163884. It was superseded by the peer-reviewed open-access article published online 2026-03-06, DOI 10.1080/14780887.2026.2638348; extracted once as one publication family.',
    URL: 'https://www.tandfonline.com/doi/full/10.1080/14780887.2026.2638348',
    DOI: '10.1080/14780887.2026.2638348',
    'Citation count, source, and retrieval date': 'not collected; publisher full article/PDF text inspected 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': '2025 SSRN preprint to 2026 journal VOR; extends Nguyen-Trung 2025 GAITA using the same Down East dataset and analytic question but a noncoding workflow and the full corpus',
    'Research objective': 'Develop and illustrate NITA, a pragmatist, reflexive, human-led approach in which an LLM supports thematic analysis without segment-level coding.',
    'Claimed qualitative methodology': 'nonpositivist, noncoding thematic analysis integrating narrative, matrix, Framework Analysis, Iterative Thematic Inquiry, and the PERFECT reflexive procedure',
    'Actual operationalized methodology': 'Two researchers familiarized themselves with 11 public interviews, configured a custom ChatGPT GPT with ROLE/GUIDES instructions and uploaded transcripts, generated candidate themes repeatedly, built participant narratives, compared gender groups, cross-checked quotations, debated/revised themes, and authored a six-stage meta-narrative.',
    'Inductive, deductive, or hybrid': 'abductive/hybrid; iterative movement between prior beliefs, candidate themes, individual cases, group comparisons, and revised explanations',
    Domain: 'qualitative methodology / environmental and rural-community perceptions',
    'Dataset name': 'Environmental Change in Down East sample project',
    'Public or restricted data': 'public secondary sample data used with Lumivero permission',
    'Number of documents': '11 interview transcripts',
    'Number of participants': '11 interviewees from Carteret County, North Carolina',
    'Approximate corpus size': '20,832 words in the current article (one manuscript passage reports 20,420; this internal discrepancy should be preserved)',
    'Document length': 'approximately six pages or about 2,000 words per interview',
    Language: 'English',
    'Sensitive-data status': 'secondary public interview data; original interviews concern community, livelihoods, identity, and environmental change',
    'Model family': 'OpenAI GPT',
    'Exact model/version': 'GPT-4o through a custom ChatGPT “My GPTs” instance; exact snapshot, temperature, seed, and retrieval settings not reported',
    'Prompting strategy': 'ROLE and GUIDES system customization; PERFECT planning/reflexive log; stage-specific prompts for three-or-more candidate-theme runs, individual narratives and uncaptured themes, cross-gender matrices, theme naming, meta-narrative, and Mermaid map.',
    'Fine-tuning or adaptation': 'No weight tuning; custom GPT instructions and retrieval-augmented generation over 11 uploaded PDFs',
    'Single-agent or multi-agent': 'single customized LLM used by two human researchers',
    'Agent roles': 'candidate-theme suggester, narrative/matrix generator, quotation retriever, uncaptured-theme prompter, comparison assistant, and diagram-syntax generator',
    'Human role': 'Both researchers read the data, designed and updated PERFECT, checked quotations against transcripts, interpreted outputs through their positionalities, decided theme inclusion/naming/relationships, and retained analytic and representational authority.',
    'Unit of analysis': 'whole interview and individual/cross-case narrative rather than segmented coded unit',
    'Generated outputs': 'candidate themes, participant-level narrative matrices with quotations, possible missing themes, gender comparison tables, six final themes, a meta-narrative, and Mermaid syntax',
    'Evidence/provenance mechanism': 'Prompts/results are reproduced selectively and PERFECT is proposed as audit trail/reflexive diary; researchers explicitly cross-check source quotations, but no complete export of chats, retrieval hits, source spans, and human edits was verified.',
    Baselines: 'qualitative comparison with Nguyen-Trung 2025 GAITA on Section Q1 of the same 11 interviews; no independent human-only reanalysis of the full 20,832-word corpus',
    'Number of runs or seeds': 'candidate-theme prompt run at least three times; other prompts iterated, but full run counts and seeds are not reported',
    'Automatic metrics': 'none',
    'Human-evaluation design': 'Two author-researchers reflexively compare, cross-check, discuss, revise, and compare themes with the earlier GAITA theme list; no blinded external evaluators',
    'Number and expertise of evaluators': 'two qualitative researchers, one with prior experience analyzing this same dataset and the other initially new to it',
    'Inter-rater reliability': 'not calculated; interpretive disagreement and positionality are discussed rather than reduced to reliability',
    'Statistical analysis': 'none',
    'Principal results': 'Five themes broadly resembled the earlier coding-based GAITA analysis; GPT-4o repeatedly proposed a sixth “resistance to change/development” theme. The researchers initially disagreed, used positionality and case-level evidence to retain and refine it as “We don’t like unsustainable change,” then linked six themes in a human-authored meta-narrative. This is a worked methodological illustration, not an independent accuracy validation.',
    'Efficiency or cost results': 'no measured time, cognitive workload, API cost, tokens, or energy; no coding step is performed',
    'Ethics and privacy treatment': 'Uses secondary data with permission and explicitly discusses data rights, privacy/consent, bias, interpretive sufficiency, agency, IRB disclosure, local/secure tools, audit trails, and representational responsibility.',
    'Reproducibility resources': 'Key prompts, tables, screenshots, and workflow are in the open article; the public sample dataset is identified. Custom GPT/chat histories, complete PERFECT sheet, exact snapshot/settings, and machine-readable outputs are not verified as released.',
    'Author-reported limitations': 'NITA is not congruent with every epistemology or researcher, AI safeguards/law evolve, and researchers must retain intellectual leadership; the article offers a worked example rather than broad validation.',
    'Additional validity concerns': 'One author previously analyzed the same data, comparison reuses the same corpus/question, no independent human-only full-corpus baseline exists, and theme similarity is judged qualitatively. Internal corpus-size inconsistency (20,420 vs 20,832), opaque custom-GPT retrieval, and no stability quantification constrain reproducibility.',
    'Relationship to prior papers': 'Direct dependency on Nguyen-Trung 2025 GAITA and the same Lumivero/Duke Down East interviews; the 2025 SSRN and 2026 journal article are one report family.',
    'Relevance to the proposed ARR project': 'NITA materially strengthens the human-authority and reflexive-ledger design case, while exposing the need for versioned full chat/RAG provenance, independent assessors, blind comparisons, run stability, and explicit dependency-family reporting.'
  }),
  record({
    'Paper ID': 'wiebe_et_al_2025_hhitl_thematic_analysis',
    'Full citation': 'Wiebe, Joel P., Rubaina Khan, Samantha Burns, and James D. Slotta. 2025. Qualitative Research in the Age of LLMs: A Human-in-the-Loop Approach to Hybrid Thematic Analysis. Proceedings of the 19th International Conference of the Learning Sciences (ICLS 2025), 1123–1131. https://doi.org/10.22318/icls2025.322165.',
    Title: 'Qualitative Research in the Age of LLMs: A Human-in-the-Loop Approach to Hybrid Thematic Analysis',
    Authors: 'Joel P. Wiebe; Rubaina Khan; Samantha Burns; James D. Slotta',
    Year: 2025,
    Venue: 'Proceedings of the 19th International Conference of the Learning Sciences (ICLS 2025), pages 1123–1131',
    'Publication type': 'peer-reviewed conference proceedings paper',
    'Peer-reviewed status': 'peer reviewed proceedings paper',
    'Publication history notes': 'Official ISLS repository proceedings version inspected.',
    URL: 'https://repository.isls.org/handle/1/11227',
    DOI: '10.22318/icls2025.322165',
    'Citation count, source, and retrieval date': 'not collected; official ISLS full text inspected 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'HHitL-TA framework/tool demonstration; no duplicate publication family verified',
    'Research objective': 'Introduce a six-stage Hybrid Human-in-the-Loop Thematic Analysis framework and tool, then illustrate it on engineering-student motivation reflections grounded in Social Cognitive Career Theory.',
    'Claimed qualitative methodology': 'hybrid deductive–inductive human-in-the-loop thematic analysis grounded primarily in reflexive thematic analysis',
    'Actual operationalized methodology': 'A primary researcher established SCCT constructs, compared human/LLM coding on 39 documents, iteratively accepted/merged/rejected LLM codes on 40 documents, used Gemini 1.5 Pro to code 175 reflections and generate themes/magnitude scores/summaries, then humans reviewed, revised, triangulated with latent classes, and retained final synthesis.',
    'Inductive, deductive, or hybrid': 'hybrid: deductive SCCT dimensions with inductive codes/themes and human refinement',
    Domain: 'engineering education / learning sciences',
    'Dataset name': 'undergraduate engineering-design motivation reflections linked to SCCT latent-class profiles',
    'Public or restricted data': 'restricted student data; anonymized before model use; no dataset release',
    'Number of documents': '196 candidate reflections; 175 with latent-class membership probability above 90% analyzed; 39 in construct check and 40 in initial-code sample',
    'Number of participants': 'not explicitly separated from document count; 175 included student reflections',
    'Approximate corpus size': 'nearly 1,000 reflections existed in the broader project; 175 at the initial time point were analyzed; 2,622 extracts were coded',
    'Document length': 'not reported',
    Language: 'not explicitly reported',
    'Sensitive-data status': 'human-student reflections; records were anonymized and stored per participant before model use',
    'Model family': 'Google Gemini',
    'Exact model/version': 'Gemini 1.5 Pro via Vertex AI; exact checkpoint, temperature, seed, and safety settings not reported',
    'Prompting strategy': 'Stage-specific templates combining persona, data payload, research question, SCCT construct codebook, existing codes/themes, task instructions, and JSON schemas; full prompts are not reproduced in the paper.',
    'Fine-tuning or adaptation': 'none; progressive prompt priming and structured JSON/tool workflow',
    'Single-agent or multi-agent': 'single LLM in a staged workflow',
    'Agent roles': 'construct coder, inductive-code generator, full-corpus coder, emergent-code proposer, merge recommender, theme/magnitude/summary generator, and visualization-data producer',
    'Human role': 'Humans define theory/questions, familiarize with data, approve/reject/merge codes, revise instructions, review theme structures and magnitude/summaries, investigate discrepancies, author synthesis, and retain final interpretive control.',
    'Unit of analysis': 'student reflection, source extract, code, theme, participant/class profile',
    'Generated outputs': 'source-linked codes and justifications, confidence values, a 435-code refined codebook, 2,622 coded extracts, themes/maps, 1–7 magnitude scores, class summaries, and cross-case displays',
    'Evidence/provenance mechanism': 'Structured outputs retain excerpts/participant IDs and intermediate artifacts for human review; however, the paper does not release the complete run logs, prompts, human edits, or coded corpus.',
    Baselines: 'human–LLM construct coding on a 20% sample; latent-class analysis used for triangulation; no independent human thematic analysis of the full corpus',
    'Number of runs or seeds': 'iterative widening on samples and a verification run are described; complete run/seed accounting is not reported',
    'Automatic metrics': 'Cohen’s kappa for nine constructs; code frequency/diversity/magnitude and latent-class probabilities',
    'Human-evaluation design': 'Primary researcher reviews all key staged products; human and LLM independently code 39 documents for construct presence; no blinded external theme-quality panel',
    'Number and expertise of evaluators': 'primary researcher plus plural researchers at later review/synthesis stages; exact number, expertise, and workload by stage are not reported',
    'Inter-rater reliability': 'Cohen’s κ > .70 for each of the nine retained constructs on 39 documents; exact construct-level values are not provided',
    'Statistical analysis': 'descriptive code metrics and latent-class probabilities; no inferential validation of model-generated themes or magnitude scores',
    'Principal results': 'Two of 11 initial SCCT factors were dropped after human/LLM sample coding. On 40 reflections, human review merged 8 and rejected 68 generated codes, then accepted 31 new verification codes, yielding 202 initial codes. Full-corpus generation produced 308 proposed new codes, 31 accepted merges, a final 435-code set, and 2,622 extracts. The Class-A illustration shows how LLM-supported TA surfaced brief prior-experience/social-influence evidence that LCA deemphasized, but the final full five-profile report was still being authored.',
    'Efficiency or cost results': 'Scalability and efficiency are design motivations; no controlled human-time, API-cost, token, or energy measures',
    'Ethics and privacy treatment': 'Anonymization/confidentiality, human control, bias, privacy, IP, passive-researcher risk, and transparent reporting are discussed; formal IRB/consent status is not reported in the paper.',
    'Reproducibility resources': 'Tool repository: https://github.com/encorelab/ai-theme-analyser. The data, exact prompts/settings, run logs, final codebook, and evaluation outputs were not verified as public.',
    'Author-reported limitations': 'Need for full-dataset human verification at scale, ongoing risk of LLM error/context loss, and need for stronger reporting guidance and tool refinement.',
    'Additional validity concerns': 'The paper claims reflexive TA while operationalizing a large theory-bound codebook, IRR, prevalence metrics, latent classes, and 1–7 magnitude scores. Most model-produced codes/themes lack an independent full-corpus human baseline; model snapshot/settings, reviewer counts, and revision totals are incomplete; the final analysis is unfinished.',
    'Relationship to prior papers': 'Draws on SCCT/LCA work and Bano/related LLM-QDA frameworks but presents a distinct tool/framework and dataset.',
    'Relevance to the proposed ARR project': 'Valuable staged human-control architecture and source-extract structure, but ARR should pre-register methodology claims, capture every accept/reject/edit, validate magnitude/theme outputs independently, and separate RTA-compatible reflexivity from coding-reliability metrics.'
  }),
  record({
    'Paper ID': 'zhou_et_al_2025_llm_qualitative_nursing_scoping_review',
    'Full citation': 'Zhou, Tingting, Mengyao Xing, Yue Hu, Jun Liang, Qi Ren, Yeqin Yang, and Lei Ye. 2025. The Application of Large Language Models in Qualitative Nursing Research: A Scoping Review. Nursing Outlook 73(6): 102544. https://doi.org/10.1016/j.outlook.2025.102544.',
    Title: 'The Application of Large Language Models in Qualitative Nursing Research: A Scoping Review',
    Authors: 'Tingting Zhou; Mengyao Xing; Yue Hu; Jun Liang; Qi Ren; Yeqin Yang; Lei Ye',
    Year: 2025,
    Venue: 'Nursing Outlook 73(6): 102544',
    'Publication type': 'peer-reviewed scoping review',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'November–December 2025 issue; publisher full HTML inspected.',
    URL: 'https://www.sciencedirect.com/science/article/pii/S0029655425001976',
    DOI: '10.1016/j.outlook.2025.102544',
    'Citation count, source, and retrieval date': 'not collected; publisher full HTML inspected 2026-08-24',
    'Core or adjacent classification': 'adjacent',
    'Relationship/dependence family': 'secondary scoping review of 11 studies; constituent primary studies overlap the evidence base and must not be counted as independent new evaluations',
    'Research objective': 'Map LLM application scenarios, effects, evaluation methods, and challenges in qualitative nursing research.',
    'Claimed qualitative methodology': 'JBI-method scoping review reported with PRISMA-ScR',
    'Actual operationalized methodology': 'Authors searched 11 databases through April 2025, deduplicated 2,478 hits to 1,883, screened titles/abstracts and 37 full texts, and retained 11 studies; they descriptively synthesized task, effect, assessment, and challenge categories.',
    'Inductive, deductive, or hybrid': 'secondary evidence mapping; not a primary coding system',
    Domain: 'nursing / qualitative research methods',
    'Dataset name': '11-study qualitative-nursing/LLM scoping-review corpus',
    'Public or restricted data': 'published literature; protocol in Appendix S1; complete extraction data availability not verified',
    'Number of documents': '2,478 identified; 1,883 after duplicates; 37 full texts considered; 11 included studies',
    'Number of participants': 'not applicable at review level; constituent-study participant counts vary',
    'Approximate corpus size': '11 databases searched through April 2025',
    'Document length': 'published articles; not applicable',
    Language: 'language restrictions/translation procedure not fully visible in the inspected text',
    'Sensitive-data status': 'no new participant data; constituent studies may involve sensitive nursing/health narratives',
    'Model family': 'multiple LLMs across included studies',
    'Exact model/version': 'heterogeneous and incompletely reported across included studies',
    'Prompting strategy': 'heterogeneous across constituent studies; review does not operationalize its own LLM workflow',
    'Fine-tuning or adaptation': 'varies by included study',
    'Single-agent or multi-agent': 'varies by included study',
    'Agent roles': 'across studies: topic/theme generation, role-playing, interview-question generation, text analysis, and codebook work',
    'Human role': 'Reviewers screened/extracted/synthesized; human roles in primary studies vary and are summarized at aggregate level.',
    'Unit of analysis': 'included publication',
    'Generated outputs': 'evidence map of scenarios, effects, assessments, and challenges',
    'Evidence/provenance mechanism': 'PRISMA-ScR flow and study tables link findings to included studies, but the review-level aggregate cannot replace primary-study methods/results inspection.',
    Baselines: 'not applicable at review level; included studies use heterogeneous human comparisons',
    'Number of runs or seeds': 'not applicable',
    'Automatic metrics': 'descriptive review counts; constituent metrics include human-output similarity and efficiency',
    'Human-evaluation design': 'review screening/extraction; reviewer count and independent duplicate procedures require caution if not explicit in full tables/protocol',
    'Number and expertise of evaluators': 'seven-author review team; exact duplicate-screening/extraction assignments not fully reported in the accessible text',
    'Inter-rater reliability': 'not reported for review screening/extraction in the inspected sections',
    'Statistical analysis': 'descriptive scoping synthesis only',
    'Principal results': 'Eleven studies were retained from 2,478 records. LLMs were used for topic generation, role play, interview-question generation, and qualitative text analysis; outputs showed moderate-to-high thematic similarity and efficiency, but weaker theoretical-framework application, interview-question generation, and codebook development. The evidence was judged early-stage and heterogeneous.',
    'Efficiency or cost results': 'Review reports efficiency advantages in constituent studies but does not provide a standardized pooled effect or cost analysis',
    'Ethics and privacy treatment': 'No new participant collection; review discusses privacy, bias, technical constraints, and responsible nursing-research use; protocol and conflict/funding statements are reported.',
    'Reproducibility resources': 'Appendix S1 protocol and publisher study tables; no verified review repository with full searches, deduplication file, decisions, and extraction forms',
    'Author-reported limitations': 'Small, immature, heterogeneous literature; limited analysis depth, simulation accuracy, technical constraints, and evaluation tools',
    'Additional validity concerns': 'Only 11 studies and nursing-specific eligibility limit generalization; synthesis phrases such as “moderate-to-high similarity” combine non-equivalent tasks/metrics. Review findings should not be double-counted alongside the same primary studies.',
    'Relationship to prior papers': 'Secondary synthesis whose 11 constituent studies overlap several primary papers in this review.',
    'Relevance to the proposed ARR project': 'Useful adjacent map of nursing-specific tasks and gaps; reinforces standardized evaluation and theory-sensitive testing but should not alter ARR rankings as an independent system evaluation.'
  }),
  record({
    'Paper ID': 'than_et_al_2025_future_of_coding_llms',
    'Full citation': 'Than, Nga, Leanne Fan, Tina Law, Laura K. Nelson, and Leslie McCall. 2025. Updating “The Future of Coding”: Qualitative Coding with Generative Large Language Models. Sociological Methods & Research, online first. https://doi.org/10.1177/00491241251339188.',
    Title: 'Updating “The Future of Coding”: Qualitative Coding with Generative Large Language Models',
    Authors: 'Nga Than; Leanne Fan; Tina Law; Laura K. Nelson; Leslie McCall',
    Year: 2025,
    Venue: 'Sociological Methods & Research, online first, pages 1–40',
    'Publication type': 'peer-reviewed journal article',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': '2025 Sage journal version of record; author-hosted VOR inspected.',
    URL: 'https://doi.org/10.1177/00491241251339188',
    DOI: '10.1177/00491241251339188',
    'Citation count, source, and retrieval date': 'not collected; author-hosted VOR inspected 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'extends McCall 2013 human coding and Nelson et al. 2018 computational replication on the same newsweekly corpus; current LLM study is not an independent dataset',
    'Research objective': 'Test whether open and proprietary generative LLMs can reproduce two qualitative news-article classifications and derive a prompt/model comparison workflow for qualitative coders.',
    'Claimed qualitative methodology': 'iterative qualitative coding/classification with natural-language LLM prompts and interprompt/intermodel validation',
    'Actual operationalized methodology': 'Models classify 1,253 long newsweekly articles as relevant/irrelevant and 786 relevant articles for inequality, using zero-shot no-definition, researcher-definition, LLM-definition, and two-example few-shot prompts; predictions are scored against prior human labels and compared across prompts/models.',
    'Inductive, deductive, or hybrid': 'predominantly deductive classification from an established codebook, with iterative/LLM-generated definition construction',
    Domain: 'sociology / historical news media / economic inequality',
    'Dataset name': 'McCall/Nelson U.S. newsweekly inequality corpus',
    'Public or restricted data': 'article full texts are copyrighted; metadata, generated outputs, and replication/reproduction materials are on GitHub',
    'Number of documents': '1,253 articles for relevance; 786 relevant articles for inequality/few-shot tasks',
    'Number of participants': 'not applicable; more than six human research assistants created the original labels',
    'Approximate corpus size': '1,253 Time, Newsweek, and U.S. News & World Report articles from 1980–2012',
    'Document length': 'long-form articles; mean length is discussed, but the exact value was not extracted; texts were truncated when exceeding model windows',
    Language: 'English',
    'Sensitive-data status': 'copyrighted news text; no human-subject data',
    'Model family': 'Meta Llama, Google Gemma, and OpenAI GPT',
    'Exact model/version': 'Ollama-hosted prequantized Llama3 70B, Llama3.1 70B, Gemma2 27B, and proprietary GPT-4; exact GPT snapshot and some quantization tags are not clearly reported',
    'Prompting strategy': 'two-step binary schema; system/meta statements; zero-shot no definition, hand-condensed codebook definition, model-generated 7–10-bullet definition with human merge/deduplication, and two randomly selected examples for few-shot; output requires label plus one-sentence rationale',
    'Fine-tuning or adaptation': 'Main analyses use no tuning; supplementary Gemma2 and BERT fine-tuning tests use up to 1,000 labeled documents',
    'Single-agent or multi-agent': 'single model per classification; ensembles/majority votes are computed post hoc across prompts or models',
    'Agent roles': 'binary document classifier, definition summarizer, and one-sentence rationale generator',
    'Human role': 'Researchers built/condensed definitions, chose prompt structure/sequencing/examples, manually merged LLM definitions, interpreted natural-language outputs, and retained validation responsibility.',
    'Unit of analysis': 'whole newsweekly article',
    'Generated outputs': 'binary labels, one-sentence justifications, model-generated definitions, agreement matrices, and majority-vote labels',
    'Evidence/provenance mechanism': 'Outputs and replication code are public and rationales refer to document content; copyrighted texts are not released, and sentence rationales are not equivalent to verified source-span provenance.',
    Baselines: 'original human coding, prior supervised ML median F1s, four LLMs, definition/prompt variants, and majority votes',
    'Number of runs or seeds': 'temperature 0 and a seed set; one reported execution per model/prompt task plus prompt/model ensembles; full repeated identical-run stability is not reported',
    'Automatic metrics': 'weighted precision, recall, F1; interprompt/intermodel Fleiss’ kappa; majority-vote F1; supplemental fine-tuning curves',
    'Human-evaluation design': 'Predictions are scored against preexisting human labels from an original multi-RA project; no new blinded qualitative judgment of rationales or emergent insights',
    'Number and expertise of evaluators': 'original project used more than six undergraduate/graduate RAs; current authors include researchers from the original and replication studies',
    'Inter-rater reliability': 'Interprompt/intermodel Fleiss κ=.62–.88; original human-label reliability is discussed via prior publications rather than re-reported as a single comparable estimate',
    'Statistical analysis': 'weighted F1 comparisons and descriptive agreement; no confidence intervals or paired significance testing reported for most model differences',
    'Principal results': 'Zero-shot weighted F1 ranged .74–.83 for relevance and .70–.74 for inequality; few-shot F1 ranged .60–.75 and harmed some open models. Researcher definitions did not consistently beat no definition; LLM definitions marginally helped some models/tasks. GPT-4 was usually only .01–.03 above the best open model except few-shot. Majority voting raised the worst F1 from .59 to .75 but the best only from .83 to .84; full agreement covered 74%–91% of documents. Agreement can reflect shared bias, not validity.',
    'Efficiency or cost results': 'Each GPT-4 test cost approximately US$50–$70; open models avoid API charges but require hardware/electricity. No human-time experiment; authors state agreement triage may redirect rather than necessarily reduce human coding.',
    'Ethics and privacy treatment': 'Discusses proprietary model, environmental, bias, reproducibility, copyright, training-data contamination, and open-source tradeoffs; no human subjects.',
    'Reproducibility resources': 'https://github.com/lknelson/future-of-coding-revisited contains metadata, generated outputs, and replication/reproduction materials; supplemental appendices are online. Copyright prevents full-text redistribution.',
    'Author-reported limitations': 'Long/noisy English news familiar to model training; possible corpus contamination; truncation/context limits; prompt sensitivity; incomplete fine-tuning; transfer to unfamiliar domains uncertain.',
    'Additional validity concerns': 'This is supervised binary classification, not open-ended thematic interpretation; same corpus underlies the human and prior-ML baselines. Model snapshots/quantization details and repeated-run stability are incomplete; random few-shot examples are not replicated; most differences lack uncertainty.',
    'Relationship to prior papers': 'Direct longitudinal dependency on McCall 2013 and Nelson et al. 2018; those papers and this article form one dataset/evaluation family.',
    'Relevance to the proposed ARR project': 'Major evidence for open-vs-proprietary comparison, prompt/model ensembles, and cost reporting; ARR should add exact checkpoints, repeated samples, confidence intervals, provenance, and a separate open-ended interpretation benchmark.'
  }),
  record({
    'Paper ID': 'gustavsen_et_al_2025_generative_ai_qualitative_coding',
    'Full citation': 'Gustavsen, David, Holly M. Surbaugh, and Mark Emmons. 2025. Using Generative AI for Qualitative Coding. Library Trends 73(3): 213–242. https://doi.org/10.1353/lib.2025.a961193.',
    Title: 'Using Generative AI for Qualitative Coding',
    Authors: 'David Gustavsen; Holly M. Surbaugh; Mark Emmons',
    Year: 2025,
    Venue: 'Library Trends 73(3): 213–242',
    'Publication type': 'peer-reviewed journal article',
    'Peer-reviewed status': 'peer reviewed',
    'Publication history notes': 'February 2025 issue; Project MUSE version of record, CC BY 4.0.',
    URL: 'https://muse.jhu.edu/article/961193',
    DOI: '10.1353/lib.2025.a961193',
    'Citation count, source, and retrieval date': 'not collected; complete VOR text inspected through the publisher-rendered/CC BY full-text copy 2026-08-24',
    'Core or adjacent classification': 'core',
    'Relationship/dependence family': 'Reanalysis of the authors’ 2021–2024 graduate-student library study (Surbaugh et al. 2024); same interviews/human themes, distinct AI comparison report',
    'Research objective': 'Compare ChatGPT-4 first- and second-level qualitative coding with a prior human team’s analysis and assess credible roles for the model in academic-library research.',
    'Claimed qualitative methodology': 'descriptive/in-vivo first-level coding followed by second-level pattern coding and thematic comparison',
    'Actual operationalized methodology': 'Human baseline: five librarians coded 20 deidentified interviews over about 16 months, producing 898 codes, 19 categories, and five themes. AI study removed one reidentification-risk transcript; two researchers independently prompted ChatGPT-4 on 19 transcripts, combined 1,287 generated codes, ran two second-level procedures, and the three authors qualitatively scored theme/subtheme similarity.',
    'Inductive, deductive, or hybrid': 'inductive open/in-vivo and pattern coding, with prompt revisions informed by the human process but without giving ChatGPT the final human themes',
    Domain: 'academic libraries / graduate-student lived experiences',
    'Dataset name': 'University of New Mexico graduate-student critical-incident interview corpus',
    'Public or restricted data': 'restricted institutional interview data; not released',
    'Number of documents': '20 original transcripts; 19 sent to ChatGPT after one high-reidentification-risk transcript was excluded',
    'Number of participants': '20 graduate students originally; 19 in the AI analysis',
    'Approximate corpus size': '19 deidentified semistructured interview transcripts; ChatGPT generated 1,287 first-level codes (568 and 719 from two workflows)',
    'Document length': 'second workflow split transcripts into 2,000–4,000-word segments; total words not reported',
    Language: 'English',
    'Sensitive-data status': 'institutional human-subject interviews containing intersecting identities, programs, research topics, unionization, finances, and other potentially identifying context',
    'Model family': 'OpenAI GPT',
    'Exact model/version': 'ChatGPT 4; ChatGPT 4o appeared only as the study ended and was not evaluated; exact snapshot/settings not reported',
    'Prompting strategy': 'Two parallel workflows: whole-transcript qualitative-researcher persona with iterative requests for more codes, and a custom academic-librarian GPT over 2,000–4,000-word chunks with a formatting example; second-level prompts grouped all 1,287 codes or batches of 100, then requested categories, themes, subthemes, inference, and relationships.',
    'Fine-tuning or adaptation': 'No weight tuning; one custom GPT configured with instructions/example spreadsheet',
    'Single-agent or multi-agent': 'single chatbot used through two human-operated workflows',
    'Agent roles': 'descriptive/in-vivo coder, pattern coder, category/theme generator, inference prompter, quote retriever, and failed graphic generator',
    'Human role': 'Humans deidentified data twice, removed a risky transcript, engineered/repeated prompts, combined outputs, selected the richer AI theme set, compared it with the prior analysis, interpreted discrepancies, and retained primary second-level judgment.',
    'Unit of analysis': 'meaningful sentence/paragraph segment, first-level code, category/subtheme, and theme',
    'Generated outputs': '1,287 first-level codes with quotations, categories/subthemes, five final themes, similarity table, and attempted thematic chart',
    'Evidence/provenance mechanism': 'Generated codes were paired with quotes and transcripts were known to evaluators; however, ChatGPT sometimes lost structure or claimed nonexistent downloads, saturation/completeness was unverifiable, and no durable chat/output package was released.',
    Baselines: 'prior five-librarian human analysis; two distinct ChatGPT first-/second-level workflows; no alternative model',
    'Number of runs or seeds': 'many iterative prompts per transcript and two main workflows; exact run count, seed, temperature, and rerun stability not reported',
    'Automatic metrics': 'none; author-created ordinal similarity rubric 0–3 is based on human judgment',
    'Human-evaluation design': 'Three authors compared human theme descriptions with AI subthemes using a 0–3 rubric, checked displaced matches, and catalogued ideas missing on each side; not blinded, and no independent external evaluator',
    'Number and expertise of evaluators': 'three current librarian-researcher authors; two participated in the original human study, while the third was initially shielded from its final findings',
    'Inter-rater reliability': 'No coefficient for the current 0–3 comparison; original team used shared coding, pair review, audit, and consensus',
    'Statistical analysis': 'descriptive counts and qualitative comparison; no inferential analysis',
    'Principal results': 'ChatGPT generated 1,287 first-level codes versus 898 human codes and produced five themes with moderate surface alignment. It was strong on concrete actions but missed/flattened emotion, context, trust, teaching/employee roles, equity/basic-needs issues, and—despite librarian persona and direct questions—the library itself. Two human themes had no AI equivalent; several AI subthemes had no human equivalent. Authors advise first-level assistance only and reject the model as primary second-level analyst.',
    'Efficiency or cost results': 'ChatGPT first-level workflow took about four hours versus months of human work; an optimized second-level model took under one hour versus just over a year around human work schedules. Authors explicitly state credible collaborative second-level use does not eliminate human time.',
    'Ethics and privacy treatment': 'Original consent allowed reuse but did not explicitly authorize LLM use; the UNM IRB allowed the follow-up. Authors performed a second deidentification pass and excluded one participant at reidentification risk, while critically noting that such exclusion can silence marginalized voices.',
    'Reproducibility resources': 'Full CC BY article includes substantial prompts and appendices, but transcripts, complete chats/outputs, custom GPT configuration, and exact model settings are not public.',
    'Author-reported limitations': 'One higher-education domain likely familiar to ChatGPT; one transcript removed; coding only; prompt dependence; ChatGPT-4 only; other models/tools may differ.',
    'Additional validity concerns': 'Evaluators/authors overlap the baseline team; the AI theme set was selected after seeing two workflows; first-level “substantial similarity” is assessed only on a subset without formal scoring; no complete-output audit or run stability; massive time differences exclude prompt development, verification, and the original team’s context-building benefits.',
    'Relationship to prior papers': 'Direct reanalysis/dependency on Surbaugh et al. 2024 and the same UNM corpus; should not count as an independent human dataset family.',
    'Relevance to the proposed ARR project': 'Materially strengthens the case for staged task allocation: LLM first-pass coding may save time, but interpretive second-level synthesis needs domain experts. ARR should test contextual/theme omissions, marginalized-voice retention, blinded assessors, complete source lineage, and verification-adjusted time.'
  }),
];

const S = (score, rationale) => ({ score, rationale });
const quality_scores = [
  quality('cook_et_al_2025_ai_qda_promises_pitfalls', 'Artificial Intelligence to Support Qualitative Data Analysis: Promises, Approaches, Pitfalls', 'core', {
    [dimensions[0]]: S(2, 'The three activities and the authors’ deliberately broad QDA definition are explicit.'),
    [dimensions[1]]: S(2, 'Three differently sized narrative datasets reveal several important failure modes.'),
    [dimensions[2]]: S(1, 'Prompt evolution is in a supplement, but snapshot/settings and run accounting are incomplete.'),
    [dimensions[3]]: S(0, 'No independently generated task-matched human reference analysis.'),
    [dimensions[4]]: S(1, 'Expert inspection is concrete but informal, unblinded, and unscored.'),
    [dimensions[5]]: S(0, 'No automatic validity metric for the case experiment.'),
    [dimensions[6]]: S(2, 'The article strongly protects human meaning-making, reflexivity, and edge cases.'),
    [dimensions[7]]: S(1, 'Concrete errors are source-checked, but no complete output-to-span package is public.'),
    [dimensions[8]]: S(1, 'Instability across reruns is observed but not systematically quantified.'),
    [dimensions[9]]: S(2, 'Privacy, consent, security, workforce, fraud, and human control receive substantive treatment.'),
    [dimensions[10]]: S(1, 'Supplements and one public dataset exist; settings, outputs, and code are incomplete.'),
    [dimensions[11]]: S(2, 'Negative conclusions are appropriately cautious and self-critical.')
  }),
  quality('zambrano_et_al_2025_data_theory_codebook', 'Data Plus Theory Equals Codebook: Leveraging LLMs for Human-AI Codebook Development', 'core', {
    [dimensions[0]]: S(2, 'The theory-to-codebook workflow and human refinement are clear.'),
    [dimensions[1]]: S(2, 'Two educational datasets support theory- and context-sensitive comparison.'),
    [dimensions[2]]: S(2, 'Exact snapshots, temperature, four prompt conditions, and repeat count are reported.'),
    [dimensions[3]]: S(1, 'Prompt conditions are useful, but no human-only codebook baseline is evaluated equivalently.'),
    [dimensions[4]]: S(1, 'Five knowledgeable evaluators score seven criteria, but are unblinded coauthors.'),
    [dimensions[5]]: S(0, 'No automatic validity measure.'),
    [dimensions[6]]: S(1, 'Human refinement is central, but evaluator plurality/independence is limited.'),
    [dimensions[7]]: S(2, 'Examples and artifact files provide meaningful grounding.'),
    [dimensions[8]]: S(1, 'Three runs per condition help, without stability statistics.'),
    [dimensions[9]]: S(1, 'Minor consent/assent is reported; model-data governance remains sparse.'),
    [dimensions[10]]: S(2, 'OSF artifacts, snapshots, temperature, and several data identifiers are available.'),
    [dimensions[11]]: S(1, 'Conclusions mostly support assistance, but evaluator dependence and uncertainty are underplayed.')
  }),
  quality('parfenova_et_al_2025_emergent_convergence', 'Emergent Convergence in Multi-Agent LLM Annotation', 'core', {
    [dimensions[0]]: S(1, 'The task is clear, but “qualitative code” is operationalized mainly as short model text.'),
    [dimensions[1]]: S(2, 'Five hundred difficult high-disagreement comments offer a strong stress test.'),
    [dimensions[2]]: S(1, 'Configurations are extensive; exact checkpoints/serving details remain incomplete.'),
    [dimensions[3]]: S(1, 'Round/group/prompt controls exist, but no human quality baseline.'),
    [dimensions[4]]: S(0, 'No human evaluation of code validity.'),
    [dimensions[5]]: S(1, 'Metrics characterize convergence but cannot validate meaning or quality.'),
    [dimensions[6]]: S(0, 'The system tends toward convergence and does not assess lost minority interpretations.'),
    [dimensions[7]]: S(1, 'Comment/configuration/round associations exist, but the output package is unavailable.'),
    [dimensions[8]]: S(1, 'Many configurations are compared without replicated identical seeds.'),
    [dimensions[9]]: S(1, 'Toxicity/bias concerns are acknowledged, with limited original-data ethics treatment.'),
    [dimensions[10]]: S(0, 'No verified code/output repository and incomplete checkpoints.'),
    [dimensions[11]]: S(1, 'The paper warns that convergence can flatten semantics, but some analysis still treats convergence as desirable.')
  }),
  quality('zhang_et_al_2025_qualigpt_inductive_deductive', 'Exploring Inductive and Deductive Qualitative Coding with AI: Investigating Inter-Rater Reliability between Large Language Model and Human Coders', 'core', {
    [dimensions[0]]: S(1, 'Inductive/deductive stages are named, but open-code mapping and multi-label κ procedures are underexplained.'),
    [dimensions[1]]: S(1, 'Public Discord posts are realistic, while topic-based selection and no release limit representativeness.'),
    [dimensions[2]]: S(1, 'Prompt template and temperature are given; snapshots and regeneration logs are absent.'),
    [dimensions[3]]: S(1, 'Human and model comparisons exist without an independent expert gold standard.'),
    [dimensions[4]]: S(1, 'Two RAs and a senior researcher contribute, but expertise/blinding are unclear.'),
    [dimensions[5]]: S(1, 'Kappa is relevant, but multi-label/open-code mappings and uncertainty are insufficient.'),
    [dimensions[6]]: S(0, 'Agreement-centered evaluation does not analyze alternative valid interpretations.'),
    [dimensions[7]]: S(1, 'Text/code indices exist, but data and regeneration choices are not auditable.'),
    [dimensions[8]]: S(1, 'Three GPT-4 runs quantify self-agreement, without seeds or broader stability design.'),
    [dimensions[9]]: S(0, 'Public-data/privacy claims lack IRB, consent, or a concrete deidentification protocol.'),
    [dimensions[10]]: S(2, 'QualiGPT code is public, although data and exact run artifacts are not.'),
    [dimensions[11]]: S(1, 'Assistance claims fit, but contextual-depth and standardization language overreaches.')
  }),
  quality('nguyen_trung_nguyen_2026_nita', 'Narrative-Integrated Thematic Analysis (NITA): How Can LLMs Support Theme Generation Without Coding?', 'core', {
    [dimensions[0]]: S(2, 'The six-stage noncoding, abductive, human-led method is thoroughly specified.'),
    [dimensions[1]]: S(1, 'Eleven public interviews suit a worked example but not broad validation.'),
    [dimensions[2]]: S(1, 'Prompts/configuration are rich; exact snapshot, settings, RAG behavior, and chats are missing.'),
    [dimensions[3]]: S(1, 'Earlier GAITA is a useful dependent comparison, not an independent full-corpus baseline.'),
    [dimensions[4]]: S(1, 'Two author-researchers deeply inspect outputs but are not independent/blinded.'),
    [dimensions[5]]: S(0, 'No automatic validity metric.'),
    [dimensions[6]]: S(2, 'Positional disagreement and interpretive authority are explicitly preserved.'),
    [dimensions[7]]: S(2, 'Quotations are cross-checked and PERFECT provides a strong audit concept.'),
    [dimensions[8]]: S(1, 'At least three candidate-theme runs, but no quantitative stability/accounting.'),
    [dimensions[9]]: S(2, 'Substantive lifecycle ethics and mitigation framework plus public secondary-data statement.'),
    [dimensions[10]]: S(1, 'Open article and public data exist; full logs, PERFECT sheet, and settings do not.'),
    [dimensions[11]]: S(2, 'Claims are framed as an illustrative, optional method rather than validated superiority.')
  }),
  quality('wiebe_et_al_2025_hhitl_thematic_analysis', 'Qualitative Research in the Age of LLMs: A Human-in-the-Loop Approach to Hybrid Thematic Analysis', 'core', {
    [dimensions[0]]: S(1, 'The stages are clear, but the claimed RTA grounding conflicts with codebook/IRR/quantification practices.'),
    [dimensions[1]]: S(2, 'A substantial student-reflection corpus supports workflow demonstration.'),
    [dimensions[2]]: S(1, 'Tool and structured workflow are described; exact prompts/settings/logs are incomplete.'),
    [dimensions[3]]: S(1, 'Construct-level human comparison and LCA triangulation exist, without full human TA baseline.'),
    [dimensions[4]]: S(1, 'Strong staged review but incomplete reviewer counts and no independent theme panel.'),
    [dimensions[5]]: S(0, 'Kappa/metrics do not validate generated themes or magnitude scores.'),
    [dimensions[6]]: S(2, 'Human revisions and discrepancy investigation are designed into every interpretive stage.'),
    [dimensions[7]]: S(2, 'Extracts, IDs, justifications, and structured artifacts support traceability.'),
    [dimensions[8]]: S(0, 'No systematic rerun/seed stability evaluation.'),
    [dimensions[9]]: S(1, 'Anonymization and risks are discussed; formal approval/consent detail is absent.'),
    [dimensions[10]]: S(1, 'Tool code is public; prompts, data, logs, and final artifacts are not.'),
    [dimensions[11]]: S(1, 'Human-led framing is cautious, but rigor/scalability claims exceed incomplete validation.')
  }),
  quality('zhou_et_al_2025_llm_qualitative_nursing_scoping_review', 'The Application of Large Language Models in Qualitative Nursing Research: A Scoping Review', 'adjacent', {
    [dimensions[0]]: S(2, 'JBI scoping-review and PRISMA-ScR framing are clear.'),
    [dimensions[1]]: S(2, 'Eleven nursing-specific studies answer the mapping question, though the evidence is small.'),
    [dimensions[2]]: S(1, 'Database scope and flow are visible; complete searches/decisions/extractions are not public.'),
    [dimensions[3]]: S(1, 'The review compares heterogeneous studies rather than matched systems.'),
    [dimensions[4]]: S(1, 'Reviewer team exists, but duplicate procedures/assignments are incompletely reported.'),
    [dimensions[5]]: S(1, 'Review counts are valid descriptively; constituent similarity measures are not harmonized.'),
    [dimensions[6]]: S(1, 'Qualitative depth/theory concerns are noted, but study-level plurality is compressed.'),
    [dimensions[7]]: S(1, 'Tables link claims to studies, without a public extraction dataset.'),
    [dimensions[8]]: S(0, 'Not applicable at review level and not synthesized systematically.'),
    [dimensions[9]]: S(2, 'Privacy, bias, clinical context, and responsible nursing use receive substantive attention.'),
    [dimensions[10]]: S(1, 'Protocol/appendices exist, but no complete reproducibility package was verified.'),
    [dimensions[11]]: S(1, 'Early-stage conclusion is cautious, while aggregate “similarity” language remains broad.')
  }),
  quality('than_et_al_2025_future_of_coding_llms', 'Updating “The Future of Coding”: Qualitative Coding with Generative Large Language Models', 'core', {
    [dimensions[0]]: S(2, 'The classification schemas, definitions, prompt variants, and workflow are clear.'),
    [dimensions[1]]: S(2, 'A large, difficult, long-document human-coded corpus supports the stated classification task.'),
    [dimensions[2]]: S(1, 'Prompts/code are strong, but exact GPT snapshot and some model/quantization details are incomplete.'),
    [dimensions[3]]: S(2, 'Human labels, prior supervised ML, four LLMs, prompt conditions, and ensembles are compared.'),
    [dimensions[4]]: S(1, 'Human reference is substantial but inherited, with no current rationale/theme assessment.'),
    [dimensions[5]]: S(2, 'Weighted F1 and agreement metrics fit fixed labels, with caveats about uncertainty/prevalence.'),
    [dimensions[6]]: S(1, 'Variation is used diagnostically, but the task ultimately collapses to binary labels.'),
    [dimensions[7]]: S(2, 'Outputs and replication materials are public and rationales are document-linked.'),
    [dimensions[8]]: S(1, 'Prompt/model variation and seed/temperature controls help; identical-run replication is absent.'),
    [dimensions[9]]: S(2, 'Copyright, proprietary models, bias, environmental cost, and contamination are discussed.'),
    [dimensions[10]]: S(2, 'Extensive GitHub and supplemental materials are available; copyrighted texts cannot be shared.'),
    [dimensions[11]]: S(2, 'Authors repeatedly caution that agreement is not validity and delimit transfer.')
  }),
  quality('gustavsen_et_al_2025_generative_ai_qualitative_coding', 'Using Generative AI for Qualitative Coding', 'core', {
    [dimensions[0]]: S(2, 'Human and AI first-/second-level workflows are described in unusually concrete detail.'),
    [dimensions[1]]: S(2, 'Nineteen authentic interviews and a mature human analysis suit the comparison.'),
    [dimensions[2]]: S(1, 'Prompts and quirks are detailed; exact snapshot/settings and complete chat logs are absent.'),
    [dimensions[3]]: S(1, 'Prior human analysis is strong but author-overlapping, selected, and not task-matched in effort.'),
    [dimensions[4]]: S(1, 'Three informed authors compare themes; evaluation is unblinded and nonindependent.'),
    [dimensions[5]]: S(0, 'No validated automatic metric; 0–3 similarity is subjective.'),
    [dimensions[6]]: S(2, 'The analysis documents model omissions, alternative framings, context, affect, and marginalization risk.'),
    [dimensions[7]]: S(1, 'Codes carry quotes, but completeness/provenance and outputs cannot be independently audited.'),
    [dimensions[8]]: S(0, 'Many ad hoc iterations but no controlled stability evaluation.'),
    [dimensions[9]]: S(2, 'IRB consultation, second deidentification, and reidentification/marginalization tradeoff are explicit.'),
    [dimensions[10]]: S(0, 'No data, full outputs, custom GPT configuration, or exact version.'),
    [dimensions[11]]: S(2, 'Authors appropriately reject standalone second-level analysis despite dramatic speed.')
  })
];

const full_text_decisions = [
  ['TA-0541', 'include_core', 'Official Oxford Academic full HTML inspected; direct three-dataset ChatGPT QDA experiment plus scoping review.'],
  ['TA-0609', 'include_core', 'Official OSF DOCX inspected; direct theory-grounded LLM codebook-development evaluation.'],
  ['TA-0627', 'include_core', 'Official ACL Anthology PDF inspected; direct multi-agent qualitative-code convergence study.'],
  ['TA-0649', 'include_core', 'Official AHFE PDF inspected; direct inductive/deductive human–LLM coding comparison.'],
  ['TA-0771', 'include_core', '2025 SSRN identity resolved to peer-reviewed 2026 publisher VOR; one NITA publication family.'],
  ['TA-0796', 'include_core', 'Official ISLS repository PDF inspected; direct hybrid human-in-loop thematic-analysis workflow.'],
  ['TA-0844', 'include_adjacent', 'Publisher full HTML inspected; secondary scoping review rather than a primary system evaluation.'],
  ['TA-0872', 'include_core', 'Author-hosted journal VOR inspected; direct model/prompt classification against prior human coding.'],
  ['TA-0874', 'include_core', 'CC BY Project MUSE VOR text inspected via complete full-text copy; direct human–ChatGPT coding/theme comparison.']
].map(([screen_id, decision, reason]) => ({ screen_id, decision, reason, full_text_inspected: true }));

const output = {
  metadata: {
    title: '2025 database-candidate full-text assessment batch 06: recovered nominal nonretrievals',
    generated_utc: new Date().toISOString(),
    source_screen: 'research/screening_2025_resolution.json',
    screen_ids: full_text_decisions.map((item) => item.screen_id),
    retrieved_count: 9,
    assessed_count: 9,
    include_core_count: 8,
    include_adjacent_count: 1,
    exclude_count: 0,
    merge_status: 'candidate-only; do not merge until parent review',
    version_note: 'TA-0771 is extracted once under its current 2026 peer-reviewed VOR, with the screened 2025 SSRN identity preserved as publication history. All nine records were in the nominal nonretrieval set but were recovered through official or author-hosted full-text endpoints.',
    extraction_columns: columns,
    extraction_column_count: columns.length,
    quality_dimensions: dimensions,
    quality_scoring: prior.metadata.quality_scoring
  },
  full_text_decisions,
  evidence_records,
  quality_scores
};

if (evidence_records.length !== 9 || quality_scores.length !== 9) throw new Error('batch counts');
if (evidence_records.some((item) => Object.keys(item).length !== 52)) throw new Error('52-field failure');
if (quality_scores.some((item) => Object.keys(item['Dimension scores']).length !== 12)) throw new Error('12-dimension failure');

fs.writeFileSync(new URL('./screening_2025_database_fulltext_batch06.json', import.meta.url), `${JSON.stringify(output, null, 2)}\n`);
