import fs from 'node:fs';

const prior = JSON.parse(fs.readFileSync(new URL('./screening_2025_database_fulltext_batch03.json', import.meta.url), 'utf8'));
const columns = prior.metadata.extraction_columns;
const dimensions = prior.metadata.quality_dimensions;

const fieldMap = [
  ['Paper ID', 'id'],
  ['Full citation', 'citation'],
  ['Title', 'title'],
  ['Authors', 'authors'],
  ['Year', 'year'],
  ['Venue', 'venue'],
  ['Publication type', 'publication_type'],
  ['Peer-reviewed status', 'peer_reviewed'],
  ['Publication history notes', 'history'],
  ['URL', 'url'],
  ['DOI', 'doi'],
  ['Citation count, source, and retrieval date', 'citation_count'],
  ['Core or adjacent classification', 'classification'],
  ['Relationship/dependence family', 'family'],
  ['Research objective', 'objective'],
  ['Claimed qualitative methodology', 'claimed_method'],
  ['Actual operationalized methodology', 'actual_method'],
  ['Inductive, deductive, or hybrid', 'inductive_deductive'],
  ['Domain', 'domain'],
  ['Dataset name', 'dataset'],
  ['Public or restricted data', 'data_access'],
  ['Number of documents', 'documents'],
  ['Number of participants', 'participants'],
  ['Approximate corpus size', 'corpus'],
  ['Document length', 'document_length'],
  ['Language', 'language'],
  ['Sensitive-data status', 'sensitive'],
  ['Model family', 'model_family'],
  ['Exact model/version', 'model_version'],
  ['Prompting strategy', 'prompting'],
  ['Fine-tuning or adaptation', 'adaptation'],
  ['Single-agent or multi-agent', 'agent_type'],
  ['Agent roles', 'agent_roles'],
  ['Human role', 'human_role'],
  ['Unit of analysis', 'unit'],
  ['Generated outputs', 'outputs'],
  ['Evidence/provenance mechanism', 'provenance'],
  ['Baselines', 'baselines'],
  ['Number of runs or seeds', 'runs'],
  ['Automatic metrics', 'metrics'],
  ['Human-evaluation design', 'human_evaluation'],
  ['Number and expertise of evaluators', 'evaluators'],
  ['Inter-rater reliability', 'irr'],
  ['Statistical analysis', 'statistics'],
  ['Principal results', 'results'],
  ['Efficiency or cost results', 'efficiency'],
  ['Ethics and privacy treatment', 'ethics'],
  ['Reproducibility resources', 'resources'],
  ['Author-reported limitations', 'limitations'],
  ['Additional validity concerns', 'concerns'],
  ['Relationship to prior papers', 'prior_relationship'],
  ['Relevance to the proposed ARR project', 'arr_relevance'],
];

if (fieldMap.length !== 52 || columns.length !== 52 || fieldMap.some(([column], index) => column !== columns[index])) {
  throw new Error('52-field schema drift');
}

function evidence(values) {
  const missing = fieldMap.filter(([, alias]) => !(alias in values));
  const extras = Object.keys(values).filter((alias) => !fieldMap.some(([, mapped]) => mapped === alias));
  if (missing.length || extras.length) {
    throw new Error(`${values.id || 'unknown'} evidence schema error; missing=${missing.map(([, a]) => a)} extras=${extras}`);
  }
  return Object.fromEntries(fieldMap.map(([column, alias]) => [column, values[alias]]));
}

function quality({id, title, classification, scores, rationales, caution}) {
  if (scores.length !== 12 || rationales.length !== 12 || dimensions.length !== 12) {
    throw new Error(`${id} quality schema error`);
  }
  const dimensionScores = Object.fromEntries(dimensions.map((dimension, index) => [dimension, {
    score: scores[index],
    rationale: rationales[index],
  }]));
  return {
    'Paper ID': id,
    Title: title,
    'Core or adjacent classification': classification,
    'Dimension scores': dimensionScores,
    Total: scores.reduce((sum, score) => sum + score, 0),
    'Interpretation caution': caution || 'Audit aid only; totals are not study rankings and every dimension must be read with its evidence.',
  };
}

const values = [
  {
    id: 'zhang_et_al_2025_ai_followup_interviews',
    citation: 'Zhang, He, Yueyan Liu, Xin Guan, Jie Cai, and John M. Carroll. 2025. Harnessing the Power of AI in Qualitative Research: Role Assignment, Engagement, and User Perceptions of AI-Generated Follow-Up Questions in Semi-Structured Interviews. arXiv:2509.12709v1.',
    title: 'Harnessing the Power of AI in Qualitative Research: Role Assignment, Engagement, and User Perceptions of AI-Generated Follow-Up Questions in Semi-Structured Interviews',
    authors: 'He Zhang; Yueyan Liu; Xin Guan; Jie Cai; John M. Carroll',
    year: 2025,
    venue: 'arXiv:2509.12709v1',
    publication_type: 'preprint / ACM-format manuscript',
    peer_reviewed: 'not peer reviewed; no archival venue identified in the inspected version',
    history: 'arXiv v1 posted 2025-09-16. The manuscript contains a 2026 ACM reference block but only placeholder Conference\'17, ISBN and DOI fields; that block is not evidence of a 2026 archival publication.',
    url: 'https://arxiv.org/abs/2509.12709',
    doi: '10.48550/arXiv.2509.12709',
    citation_count: 'not collected; official arXiv full text inspected 2026-08-24',
    classification: 'adjacent',
    family: 'AI-generated follow-up-question / qualitative data-collection assistance; no related archival version verified',
    objective: 'Examine how real-time LLM-generated follow-up questions affect interviewer experience, role allocation, perceived question usefulness, trust, timing, control and agency in semi-structured interviews.',
    claimed_method: 'AI-driven Wizard-of-Oz study plus inductive thematic analysis of participant reflections',
    actual_method: 'Seventeen recruited participants acted as lead interviewers; one researcher played an interviewee (Oz), while a second researcher entered Oz responses into a fresh GPT-4o conversation, selected when to intervene under three insertion patterns, and voiced the generated questions. Researchers then elicited pre- and post-disclosure reflections and conducted consensus-based human thematic coding.',
    inductive_deductive: 'inductive analysis of interviewers\' reflections; the LLM task is generative data-collection support rather than qualitative analysis',
    domain: 'human-computer interaction / qualitative interviewing methods',
    dataset: '17 AI-driven Wizard-of-Oz semi-structured interview and reflection sessions on participant-selected topics',
    data_access: 'restricted human-subject recordings and transcripts; no public dataset reported',
    documents: '17 session transcripts/recordings',
    participants: '17 lead-interviewer participants (ages 21–35; 10 women and 7 men), plus two researcher confederate roles',
    corpus: '17 sessions lasting 15–30 minutes each; exact transcript word or turn count not reported',
    document_length: '15–30 minutes per interview session',
    language: 'not explicitly reported in the full text',
    sensitive: 'human-subject interview recordings; topics varied by participant; recordings were transcribed, anonymized and stripped of identifiers',
    model_family: 'OpenAI GPT',
    model_version: 'GPT-4o in ChatGPT; snapshot/date, temperature and other configuration not reported',
    prompting: 'A fresh conversation per session instructed GPT-4o to act as a qualitative co-interviewer and generate one to three relevant follow-ups from each Oz response; exact prompt text was not reproduced.',
    adaptation: 'none reported',
    agent_type: 'single LLM behind a human Wizard intermediary',
    agent_roles: 'real-time follow-up-question generator',
    human_role: 'The recruited participant led the interview; Oz supplied answers; the Wizard controlled which AI questions were voiced and their timing; researchers disclosed AI involvement afterward and performed all qualitative analysis.',
    unit: 'interview session and participant reflection; individual generated follow-up questions are the intervention',
    outputs: 'one-to-three-question suggestions, participant reflections, qualitative codes, two overarching findings and a human–AI interviewing design framework',
    provenance: 'Participant quotations are labeled in the results, but the paper does not provide a complete question-to-source-turn-to-participant-judgment audit trail or generated-question set.',
    baselines: 'no human-only or alternative-model control; three nonrandomized Wizard insertion patterns were explored',
    runs: 'one fresh ChatGPT conversation for each of 17 sessions; stochastic reruns, seeds and repeated-condition trials not reported',
    metrics: 'none for question quality or model performance',
    human_evaluation: 'Subjective interviewer reflections before and after disclosure; three experienced researchers independently open-coded a transcript subset, followed by four-member consensus meetings.',
    evaluators: '17 participants with varying qualitative-method experience; three initial coders and a four-person author team; no independent blinded question-quality panel',
    irr: 'not calculated by design; disagreements were resolved to consensus',
    statistics: 'qualitative synthesis only; recruitment was stopped at author-judged theoretical saturation without a quantitative saturation trace',
    results: 'Participants often valued topical, deepening and connecting questions and described cognitive/emotional support, but timing was a recurrent weak point. They wanted human gatekeeping, consent and control; disclosure did not uniformly change perceived question quality.',
    efficiency: 'no measured time, workload or cost comparison',
    ethics: 'Participants received study, recording, confidentiality, withdrawal and compensation information and gave informed consent; secure videoconferencing and anonymization are reported. An institutional review-board approval or exemption identifier is not reported.',
    resources: 'no verified code, prompt or data repository; the inspected manuscript has placeholder publication links',
    limitations: 'The paper discusses context dependence, timing, trust, consent, hallucination and limitations of direct AI interviewing, but does not provide a conventional study-limitations section establishing transfer boundaries.',
    concerns: 'The Wizard\'s selection, delivery and timing confound the model with skilled human mediation; participant-selected topics and no control condition preclude causal claims about interview depth. Saturation at 17 is asserted without a trace, and no objective assessment establishes question quality or downstream data quality.',
    prior_relationship: 'Conceptually adjacent to AI interviewing and qualitative-analysis systems cited in the paper; no duplicate publication family identified.',
    arr_relevance: 'Useful for a human-gatekeeping and provenance requirement at the data-collection boundary, but it does not evaluate automated coding or thematic analysis and should not support claims about analytic accuracy.',
  },
  {
    id: 'parkington_et_al_2025_human_vs_llm_mental_health',
    citation: 'Parkington, Karisa, Bazen G. Teferra, Marianne Rouleau-Tang, Argyrios Perivolaris, Alice Rueda, Adam Dubrowski, Bill Kapralos, Reza Samavi, Andrew Greenshaw, Yanbo Zhang, Bo Cao, Yuqi Wu, Sirisha Rambhatla, Sridhar Krishnan, and Venkat Bhat. 2025. Human vs. LLM-Based Thematic Analysis for Digital Mental Health Research: Proof-of-Concept Comparative Study. arXiv:2507.08002v1.',
    title: 'Human vs. LLM-Based Thematic Analysis for Digital Mental Health Research: Proof-of-Concept Comparative Study',
    authors: 'Karisa Parkington; Bazen G. Teferra; Marianne Rouleau-Tang; Argyrios Perivolaris; Alice Rueda; Adam Dubrowski; Bill Kapralos; Reza Samavi; Andrew Greenshaw; Yanbo Zhang; Bo Cao; Yuqi Wu; Sirisha Rambhatla; Sridhar Krishnan; Venkat Bhat',
    year: 2025,
    venue: 'arXiv:2507.08002v1',
    publication_type: 'preprint',
    peer_reviewed: 'not peer reviewed in the inspected version',
    history: 'arXiv v1; IEEE-formatted manuscript with no verified journal or conference publication metadata',
    url: 'https://arxiv.org/abs/2507.08002',
    doi: '10.48550/arXiv.2507.08002',
    citation_count: 'not collected; official arXiv full text inspected 2026-08-24',
    classification: 'core',
    family: 'DHMI-S digital mental-health trial qualitative-analysis family (trial NCT05923398)',
    objective: 'Directly compare human reflexive thematic analysis with out-of-the-box and Braun–Clarke knowledge-base GPT-4o workflows on code development, saturation, excerpt extraction/application, themes, labor and cost.',
    claimed_method: 'reflexive thematic analysis using deductive parent and inductive child codes, with two LLM analogues',
    actual_method: 'A human expert reviewed 99 transcripts to construct and operationalize a hierarchical codebook; two humans independently coded a random 20-transcript subset. GPT-4o separately processed all 99 transcripts in five-transcript batches under RISEN zero-shot prompts, once without and once with a Braun–Clarke knowledge base/RAG, then extracted and coded excerpts for the same 20 transcripts and synthesized themes.',
    inductive_deductive: 'hybrid: five research questions structure deductive parent codes while child codes emerge inductively',
    domain: 'digital mental health / health-care worker stress / VR intervention',
    dataset: 'DHMI-S virtual-reality debrief semi-structured interviews',
    data_access: 'restricted clinical-trial transcripts; not publicly deposited',
    documents: '99 semi-structured interview transcripts; 20 used for detailed excerpt/code comparison',
    participants: '99 health-care-worker interview participants implied by one transcript per participant; the detailed comparison uses 20',
    corpus: '99 transcripts; 428 human excerpts, 417 out-of-the-box excerpts and 251 knowledge-base excerpts in the 20-transcript subset',
    document_length: 'transcript-level lengths not reported; human excerpts ranged 3–364 words, out-of-the-box 3–78 and knowledge-base 5–63',
    language: 'not explicitly reported; manuscript and prompts are in English',
    sensitive: 'mental-health and moral-distress trial interviews; deidentified and stripped of personally identifiable information before LLM input',
    model_family: 'OpenAI GPT',
    model_version: 'GPT-4o accessed in August 2024; exact snapshot not reported',
    prompting: 'Four-step zero-shot RISEN prompts (Role, Instructions, Steps, End Goal, Narrowing), processing interviews individually then consolidating in batches of five; Supplementary 1 contains prompts.',
    adaptation: 'Knowledge-base condition uses retrieval-augmented access to Braun and Clarke\'s thematic-analysis framework; no weight fine-tuning',
    agent_type: 'single-model sequential pipelines in two configurations',
    agent_roles: 'code developer/reducer, excerpt extractor and code applier, then theme synthesizer',
    human_role: 'A qualitative expert led the full human analysis; a second researcher contributed to code development; two humans independently coded the 20-transcript subset; one postdoctoral researcher designed prompts, executed and organized both LLM analyses.',
    unit: 'transcript for code development; excerpt for code application; code collections for theme synthesis',
    outputs: 'parent/child codebooks, saturation points, source excerpts with assigned codes and overarching themes',
    provenance: 'The study audits source-excerpt overlap and quote fidelity, including summaries and interviewer-only errors, but complete outputs and transcript mappings are not public.',
    baselines: 'traditional human Dedoose analysis, out-of-the-box GPT-4o and knowledge-base/RAG GPT-4o',
    runs: 'one end-to-end analysis per LLM configuration is apparent; seeds, reruns and order randomization are not reported',
    metrics: 'code/theme counts, saturation transcript count, excerpt-count and length distributions, exact/partial overlap, missed/unique excerpts, multi-code rates, labor hours and cost',
    human_evaluation: 'Direct human baseline with double-coding on 20 transcripts; conceptual code/theme mapping was conducted by the research team but not independently blinded.',
    evaluators: 'one lead qualitative expert, another code-development contributor, two human coders familiar with the schema, and one postdoctoral LLM operator; exact credentials for every comparison judgment are not reported',
    irr: 'Cohen\'s kappa = 0.84 between the two human coders on the 20-transcript subset; this is not human–LLM agreement',
    statistics: 'descriptive counts, ranges, means, percentages and overlap mappings; no uncertainty intervals or significance tests',
    results: 'Humans produced 7 parent/65 child codes and 9 themes; both LLMs produced 10 parent/22 child codes and 6 themes. Both missed 190/428 human excerpts; out-of-the-box overlapped 238/428 (56%) and knowledge-base 124/428 (29%). Knowledge-base outputs included 68/251 (27%) interpretive summaries instead of quotes. Humans multi-coded more often (38% versus 23% and 8%) and one-third of human themes were absent from both LLMs.',
    efficiency: 'Human work was reported as about 110 hours, CAD $3,537 labor plus $74.24 Dedoose; LLM work required about 40 researcher hours, CAD $1,260 labor plus $12.10 API cost. Review labor remains substantial and the comparison excludes downstream correction costs.',
    ethics: 'The source trial received ethical approval in April 2023 and is registered as NCT05923398. Transcripts were anonymized through an AI-assisted plus manual transcription workflow, and no PII was sent to the LLM.',
    resources: 'Supplementary 1 contains RISEN prompts and Supplementary 2 cost details; code, model snapshot, complete outputs and restricted transcripts are not available',
    limitations: 'One GPT family, one health-care-professional corpus, limited patient generalizability, model/prompt dependence, privacy risk for future patient use, training-data bias, output variability and environmental cost',
    concerns: 'The abstract grammatically links “strong inter-rater reliability (κ=.84)” to the out-of-the-box LLM, but κ=.84 is explicitly the human–human baseline. Faster apparent saturation reflects smaller, coarser codebooks and should not be interpreted as superior analytical completeness. Single runs leave stability unknown.',
    prior_relationship: 'Uses qualitative data from the DHMI-S trial and compares against a pre-existing human analysis; not a duplicate of other LLM-thematic-analysis papers.',
    arr_relevance: 'Strong evidence for quote-level recall/fidelity auditing, granularity and multi-code metrics, direct labor accounting and a human-first baseline. It materially argues against saturation speed or theme-count overlap as sufficient quality evidence.',
  },
  {
    id: 'nam_et_al_2025_idealign',
    citation: 'Nam, Hyunji, Lucia Langlois, James Malamut, Mei Tan, and Dorottya Demszky. 2025. IDEAlign: Comparing Large Language Models to Human Experts in Open-ended Interpretive Annotations. arXiv:2509.02855v1.',
    title: 'IDEAlign: Comparing Large Language Models to Human Experts in Open-ended Interpretive Annotations',
    authors: 'Hyunji Nam; Lucia Langlois; James Malamut; Mei Tan; Dorottya Demszky',
    year: 2025,
    venue: 'arXiv:2509.02855v1',
    publication_type: 'preprint',
    peer_reviewed: 'not peer reviewed in the inspected version',
    history: 'arXiv v1 posted 2025-09-02; no archival version identified',
    url: 'https://arxiv.org/abs/2509.02855',
    doi: '10.48550/arXiv.2509.02855',
    citation_count: 'not collected; official arXiv full text inspected 2026-08-24',
    classification: 'adjacent',
    family: 'IDEAlign open-ended interpretive-annotation evaluation framework',
    objective: 'Develop and validate a scalable expert benchmark for idea-level similarity among open-ended human and LLM annotations, and test lexical, embedding, topic-model and LLM-judge metrics against it.',
    claimed_method: 'expert evaluation of open-ended interpretive annotations, presented as relevant to thematic analysis and educational feedback',
    actual_method: 'Experts choose the odd annotation in repeated triplets; aggregate co-selection yields pairwise similarity scores. Automated metrics rank the same pairs, and their Spearman correlations with expert rankings are evaluated on math-reasoning annotations and essay feedback. No codebook or theme generation is performed.',
    inductive_deductive: 'neither; comparative evaluation of free-text interpretive outputs under task-specific criteria',
    domain: 'education / classroom reasoning and writing feedback',
    dataset: 'four deidentified mathematics-classroom transcripts and 18 open-source student essays with expert and LLM annotations',
    data_access: 'GitHub shares full math annotations and consent-permitted feedback subsets; some feedback is restricted by original consent',
    documents: '4 classroom transcripts and 18 essays',
    participants: '11 math annotation authors, 10 additional math similarity judges, 32 ELA feedback providers from prior work and 7 ELA similarity judges; source student counts are not fully reported here',
    corpus: 'math transcripts contain 300–600 lines each; 640 math triplet judgments and 458 feedback judgments; 18 essays',
    document_length: 'math annotations average 139.38 words, maximum 556; source transcript/essay token lengths otherwise not summarized',
    language: 'English',
    sensitive: 'deidentified classroom data involving students, teachers and guardians; essay feedback shared only where consent permits',
    model_family: 'OpenAI GPT, Anthropic Claude, Google Gemini and DeepSeek; 16 embedding models plus topic models',
    model_version: 'annotation generators include ChatGPT, Claude 3.5 Sonnet, Gemini 2.5 Pro and DeepSeek-V2.5; judges include GPT-4.1, GPT-4o-mini, Claude 4 Sonnet and Claude 3.5 Sonnet',
    prompting: 'Binary, continuous and IDEAlign pick-the-odd-one-out prompts with explicit content-not-style criteria; full templates are provided in the appendix',
    adaptation: 'no fine-tuning; PCA post-processing, BERTopic/UMAP/HDBSCAN and MALLET-LDA hyperparameter variants were evaluated',
    agent_type: 'single-model judges evaluated independently',
    agent_roles: 'annotation generator in source datasets and similarity judge in the benchmark',
    human_role: 'Expert educators generated interpretive annotations, labeled triplets, defined domain-relevant similarity criteria and served as the gold ranking; authors designed aggregation and perturbation tests.',
    unit: 'triplet judgment and resulting annotation-pair similarity ranking',
    outputs: 'expert pairwise similarity scores, automated similarity rankings, correlations, style-perturbation sensitivity and bootstrap sample-size guidance',
    provenance: 'Every similarity judgment is tied to three annotations of the same source item; task IDs, annotations, metadata and expert mappings are shared to the extent consent allows.',
    baselines: 'BLEU, 16 embedding models with/without PCA, BERTopic, MALLET-LDA, binary/continuous LLM judges and a bootstrapped human-evaluation oracle',
    runs: '10 sampled responses per pairwise LLM-judge comparison; 100 bootstrap runs for sample-size/stability analysis; two LLM-generated annotations per model in the math source task',
    metrics: 'Spearman rank correlation, bootstrap human-oracle correlation, percentage change under style perturbation and sample-size stability',
    human_evaluation: 'Domain experts labeled randomized triplets through a web interface using explicit idea-level criteria; math and ELA tasks had separate expert panels.',
    evaluators: '10 math educators for 640 triplets and 7 ELA teachers for 458 judgments; ELA judges had 5–6 or at least 8 years of teaching experience and were compensated $50/hour',
    irr: 'No conventional kappa reported; bootstrapped human-evaluation oracle correlations were 0.906 for feedback and 0.812 for reasoning.',
    statistics: 'Spearman correlations, 100-run bootstrap curves and perturbation comparisons',
    results: 'Best GPT-4.1 IDEAlign correlations were .618 (feedback) and .683 (reasoning), versus best vector results .489/.491 and human oracle .906/.812. Triplet prompting improved alignment 9–30%. Style-only edits inflated embedding similarities by up to 82%, versus +5% for GPT-4.1 and −2.03% for Sonnet 4. Stable rankings required roughly 300 feedback and 600 reasoning judgments.',
    efficiency: 'Expert labeling is explicitly recognized as costly; judges were paid $50/hour. No complete dollar comparison with automated metrics is reported.',
    ethics: 'Math classroom data were collected under IRB #75294 with teacher, student and guardian consent; judges saw only deidentified data and were compensated. Feedback sharing follows prior consent limitations.',
    resources: 'code, prompts, annotation data, metadata and task mappings: https://github.com/EduNLP/IDEAlign',
    limitations: 'Only two educational tasks; similarity criteria must be defined with domain experts and can change by task; expert data are costly; LLM judges still lack domain expertise and broader-domain validation is needed',
    concerns: 'The framework validates similarity-to-expert judgments, not the truth or qualitative adequacy of an annotation. Aggregating plurality into one scalar ranking can conceal substantively different expert perspectives, and the same experts do not judge every possible domain.',
    prior_relationship: 'Builds on previously collected math-transcript annotations and essay-feedback data; this paper contributes the evaluation benchmark rather than a new thematic-analysis system.',
    arr_relevance: 'A high-value adjacent foundation for idea-level human evaluation, metric validation, perturbation testing and sample-size planning. It supports triplet expert judgments as an alternative to lexical similarity, while requiring separate source-grounding and plurality analyses.',
  },
  {
    id: 'castellanos_et_al_2025_thematic_summarization',
    citation: 'Castellanos, Arturo, Haoqiang Jiang, Paulo Gomes, Debra Vander Meer, and Alfred Castillo. 2025. Large Language Models for Thematic Summarization in Qualitative Health Care Research: Comparative Analysis of Model and Human Performance. JMIR AI 4:e64447. https://doi.org/10.2196/64447.',
    title: 'Large Language Models for Thematic Summarization in Qualitative Health Care Research: Comparative Analysis of Model and Human Performance',
    authors: 'Arturo Castellanos; Haoqiang Jiang; Paulo Gomes; Debra Vander Meer; Alfred Castillo',
    year: 2025,
    venue: 'JMIR AI 4:e64447',
    publication_type: 'journal article',
    peer_reviewed: 'peer reviewed',
    history: 'published 2025-04-04; PubMed PMID 40611510 and open full text inspected',
    url: 'https://doi.org/10.2196/64447',
    doi: '10.2196/64447',
    citation_count: 'not collected; publisher/PMC full text inspected 2026-08-24',
    classification: 'core',
    family: 'nurse-forum LDA analysis family; extends the authors\' 2023 JMIR Nursing study DOI 10.2196/40676',
    objective: 'Test whether LLMs can scale the interpretation and labeling of LDA topics from a health-care forum and compare human and model themes.',
    claimed_method: 'inductive semantic thematic analysis/thematic summarization layered on topic modeling',
    actual_method: 'LDA produced 310 topics from preprocessed nurse-forum posts. Two humans labeled each topic after reading its top 10 posts and derived 58 subthemes. GPT-3.5 generated themes/subthemes from the same topic samples; two authors placed human–LLM comparisons on a novel seven-category scale. GPT-4 then judged alignment, convergence, coherence and complementarity of the human and GPT-3.5 themes.',
    inductive_deductive: 'claimed inductive; operationally constrained by LDA clusters, top-post selection and fixed comparison criteria',
    domain: 'health-care / nurses\' online discussion during COVID-19',
    dataset: 'public Nurse Forum posts aggregated over 28 two-week periods, March 2020–April 2021',
    data_access: 'source described as public and anonymized; analyzed corpus and mappings not deposited with the paper',
    documents: 'number of forum posts not reported; 310 LDA topic clusters were analyzed through their top 10 posts',
    participants: 'number and identity of forum contributors not reported',
    corpus: '28 biweekly periods; 310 topics; up to 3,100 topic-post presentations before possible repeated posts; 58 human subthemes',
    document_length: 'short-form forum posts; lengths not reported',
    language: 'English implied but not explicitly reported',
    sensitive: 'publicly accessible health-worker forum discourse; authors describe posts as anonymized',
    model_family: 'OpenAI GPT',
    model_version: 'GPT-3.5 for theme generation and GPT-4 for comparison; exact model snapshots not reported',
    prompting: 'Structured system/user messages ask for themes and subthemes; GPT-4 receives both human and model themes and four comparison criteria. Multimedia Appendix 1 provides prompt details, but main-text temperature and seed values are not stated.',
    adaptation: 'none reported',
    agent_type: 'sequential two-model pipeline',
    agent_roles: 'GPT-3.5 theme/subtheme generator; GPT-4 evaluator of alignment, convergence, coherence and complementarity',
    human_role: 'Two coders label topics, resolve disagreements and derive subthemes; two authors independently classify human–LLM agreement and adjudicate; humans compare GPT-4 judgments with their classifications.',
    unit: 'LDA topic represented by its top 10 posts',
    outputs: 'human themes, GPT themes/subthemes, seven-category comparison labels and four GPT-4 evaluation attributes',
    provenance: 'Top posts ground each topic, and selected examples reveal one-post subthemes; complete post–theme provenance and the corpus are unavailable.',
    baselines: 'two-human topic labels and subthemes versus GPT-3.5; human comparison categories versus GPT-4 self-evaluation',
    runs: 'one reported generation/evaluation per topic; seed is said to be specified but its value, reruns and order tests are not reported',
    metrics: 'LDA coherence; raw human agreement percentages; ad hoc seven-category percentage; GPT-4 binary alignment/convergence/coherence/complementarity',
    human_evaluation: 'Two authors independently classify 310 human–LLM pairs and resolve disagreement, but no pre-adjudication reliability coefficient is reported for the seven-category scale.',
    evaluators: 'two human topic coders and two author comparators; expertise is not characterized in detail; GPT-4 also judges outputs from GPT-3.5',
    irr: 'Human theme labels: 68% initial agreement, 94% after a second round, remaining 18/310 resolved jointly. Reported 79.7% is not an inter-rater coefficient.',
    statistics: 'descriptive counts and percentages; no uncertainty intervals or chance-corrected agreement for the main comparison',
    results: 'Authors classify 247/310 (79.7%) as agreement, comprising 95 taxonomic matches, 101 subtheme matches and 51 cases where the LLM diverged but humans judged the topic low-coherence. GPT-4 overaccepted coherence: 49/51 human-low-coherence cases and 29/30 overly broad cases; it also marked 87% of the overly broad set complementary.',
    efficiency: 'automation/scalability is asserted but no measured time, labor or cost is reported',
    ethics: 'Authors deemed IRB review unnecessary because the study used publicly available anonymized forum posts; contributor expectations and quotation-searchability are not discussed.',
    resources: 'Multimedia Appendix 1 contains prompts and modeling/comparison details; no data or executable code package reported',
    limitations: 'single forum, one short-form English context, GPT-3.5/GPT-4 only, simple prompts and no long-form evaluation',
    concerns: 'Methods state 15/310 (16.5%) low-coherence topics, whereas Table 2/results correctly use 51/310. The 79.7% “reliability” category includes divergent LLM themes when humans found the input cluster incoherent, so it is not ordinary agreement. GPT-4 evaluates another OpenAI model and force-fits coherence/complementarity from isolated posts, undermining independence.',
    prior_relationship: 'Uses the nurse-forum corpus and LDA pipeline reported in the authors\' 2023 JMIR Nursing article; the LLM interpretation layer is the new contribution.',
    arr_relevance: 'Provides a warning case for evaluator independence, clear denominators and category semantics. An ARR system should not allow a model-generated broad theme or a low-quality source cluster to count as “agreement” without human source-grounded review.',
  },
  {
    id: 'ornelas_et_al_2025_llm_assisted_ta_workshop',
    citation: 'Ornelas, Tatiane, Allysson Allex Araújo, Júlia Araújo, Marina Araújo, Bianca Trinkenreich, and Marcos Kalinowski. 2025. LLM-Assisted Thematic Analysis: Opportunities, Limitations, and Recommendations. arXiv:2511.14528v1. Artifact: https://doi.org/10.5281/zenodo.17443995.',
    title: 'LLM-Assisted Thematic Analysis: Opportunities, Limitations, and Recommendations',
    authors: 'Tatiane Ornelas; Allysson Allex Araújo; Júlia Araújo; Marina Araújo; Bianca Trinkenreich; Marcos Kalinowski',
    year: 2025,
    venue: 'arXiv:2511.14528v1',
    publication_type: 'preprint / workshop-reflection manuscript',
    peer_reviewed: 'not peer reviewed in the inspected version',
    history: 'arXiv v1 posted 2025-11-18; reports an ISERN 2025 workshop and cites a separate Zenodo artifact',
    url: 'https://arxiv.org/abs/2511.14528',
    doi: '10.48550/arXiv.2511.14528; artifact DOI 10.5281/zenodo.17443995',
    citation_count: 'not collected; official arXiv full text inspected 2026-08-24',
    classification: 'core',
    family: 'ISERN 2025 LLM-assisted thematic-analysis workshop and Zenodo artifact; illustrative example comes from an ongoing separate interview study',
    objective: 'Elicit experienced software-engineering researchers\' views on opportunities, limitations and safeguards for LLM-assisted open coding, theme generation and theme review, and present a five-phase/seven-step collaboration process.',
    claimed_method: 'structured reflective workshop and LLM-assisted thematic analysis following Braun and Clarke',
    actual_method: 'Twenty-five ISERN participants worked in five groups for 30 minutes on color-coded A2 canvases after a process demonstration. Authors transcribed each post-it, organized it by phase/category and descriptively grouped recurring ideas. A separate illustrative example shows GPT-4 coding authentic excerpts and humans validating codes/themes, but it does not report a performance evaluation.',
    inductive_deductive: 'workshop synthesis is structured deductively by three phases and three color categories, with descriptive inductive grouping within cells; illustrative coding is presented as inductive',
    domain: 'empirical software engineering / qualitative research methodology',
    dataset: 'five ISERN workshop canvases plus a small authentic excerpt illustration from an ongoing study of software engineers\' interpersonal/reflection abilities',
    data_access: 'workshop materials and consolidated spreadsheet are associated with Zenodo DOI 10.5281/zenodo.17443995; underlying interview corpus is not public or fully described',
    documents: '5 completed A2 canvases; number of post-its and underlying interview documents not reported',
    participants: '25 workshop participants; participant count for the illustrative ongoing interview study not reported',
    corpus: 'five group canvases and an unspecified subset of authentic interview excerpts; no word/post-it total',
    document_length: '60-minute workshop with 30-minute group-canvas phase; interview excerpt lengths vary and are not summarized',
    language: 'English',
    sensitive: 'workshop reflections and anonymized interview excerpts labeled by participant IDs; ethics/privacy procedures are not reported',
    model_family: 'OpenAI GPT',
    model_version: 'GPT-4; exact snapshot, access date and configuration not reported',
    prompting: 'Modular prompts specify research context, data source, task, quality criteria and tabular output for open codes, candidate themes and redundant-code review; exact complete prompts are not reproduced in the paper',
    adaptation: 'no fine-tuning or RAG in the illustrative example',
    agent_type: 'single LLM used sequentially across human-validation gates',
    agent_roles: 'open coder, theme grouper and redundancy reviewer',
    human_role: 'Researchers familiarize themselves with all data, review every generated code, validate/refine themes, reject harmful consolidations and write the report; workshop participants provide methodological reflections.',
    unit: 'workshop post-it for the empirical study; quote/code/theme for the illustrative workflow',
    outputs: 'opportunity/risk/recommendation groupings; code-description-quote tables; candidate themes; semantic consolidation proposals; a seven-step human–LLM workflow',
    provenance: 'Illustrative tables retain quote and participant identifiers through code/theme stages; workshop post-its are in an artifact, but paper results do not report item counts by finding.',
    baselines: 'no model-performance baseline; participants recommend manual coding and multi-model comparison as safeguards',
    runs: 'not reported for GPT-4; one 60-minute workshop with five simultaneous groups',
    metrics: 'none; the workshop synthesis explicitly does not quantify consensus or model performance',
    human_evaluation: 'Senior empirical-software-engineering researchers discuss a conceptual workflow; this is expert reflection, not evaluation of actual model outputs. Authors validate the separate example internally.',
    evaluators: '25 ISERN researchers described as experienced/senior; exact demographics and expertise distribution not reported',
    irr: 'not reported',
    statistics: 'structured descriptive synthesis only',
    results: 'Participants saw efficiency, scale and alternative taxonomies, but emphasized loss of familiarization/context, instability, bias, overproduction and review burden. Safeguards included manual engagement, human validation, multiple models, documented prompts/versions/interventions and prompt literacy.',
    efficiency: 'participants perceived potential time savings; no measured time or cost',
    ethics: 'no ethics approval, consent process or privacy protocol is reported for the workshop or illustrative interview excerpts',
    resources: 'Zenodo artifact DOI 10.5281/zenodo.17443995 with workshop materials/consolidated spreadsheet; no executable system, exact model snapshot or complete underlying interview corpus',
    limitations: 'single situated workshop with a focused group of senior empirical-SE researchers; not statistically generalizable and not a model-performance study',
    concerns: 'The “concrete example” lacks corpus size, model configuration, reruns and outcome measures and should not be treated as empirical evidence that the workflow preserves interpretive depth. Workshop expectations about efficiency and model behavior are perceptions, not observed effects.',
    prior_relationship: 'The example is drawn from an ongoing author study and may later form a separate publication family; this record should not be merged with that future empirical report without exact-family review.',
    arr_relevance: 'Supports governance requirements—human familiarization, validation gates, traceable quotes and intervention logs—but supplies no comparative accuracy or stability evidence for ARR ranking.',
  },
  {
    id: 'oksanen_et_al_2025_llmcode',
    citation: 'Oksanen, Joel, Andrés Lucero, and Perttu Hämäläinen. 2025. LLMCode: Evaluating and Enhancing Researcher-AI Alignment in Qualitative Analysis. arXiv:2504.16671v1.',
    title: 'LLMCode: Evaluating and Enhancing Researcher-AI Alignment in Qualitative Analysis',
    authors: 'Joel Oksanen; Andrés Lucero; Perttu Hämäläinen',
    year: 2025,
    venue: 'arXiv:2504.16671v1',
    publication_type: 'preprint / ACM-format manuscript',
    peer_reviewed: 'not peer reviewed; manuscript says “submitted to ACM”',
    history: 'arXiv v1; inspected manuscript has anonymous-review GitHub placeholder and placeholder ACM DOI 10.1145/nnnnnnn.nnnnnnn, so no archival publication is established',
    url: 'https://arxiv.org/abs/2504.16671',
    doi: '10.48550/arXiv.2504.16671',
    citation_count: 'not collected; official arXiv full text inspected 2026-08-24',
    classification: 'core',
    family: 'LLMCode toolkit and two associated designer studies',
    objective: 'Develop IoU and modified Hausdorff distance measures for human–LLM coding alignment, evaluate GPT-4o in-context learning of individual coding perspectives, and study reciprocal influence during interactive refinement.',
    claimed_method: 'inductive qualitative coding in research-for-design plus reflexive thematic analysis of user feedback',
    actual_method: 'LLMCode sequentially generates span highlights and open codes while accumulating a codebook. Study 1 has 19 game-design students manually code up to 200 Reddit texts, then uses their annotations as examples/baselines. Study 2 has seven designers manually code data and perform two further example/prompt iterations against the same validation annotations. Logs are quantified with IoU/MHD and the first author reflexively analyzes surveys and 428 minutes of think-aloud data.',
    inductive_deductive: 'nominally inductive generation; as examples accumulate, performance increasingly reflects deductive reuse of a stabilizing codebook',
    domain: 'research for design / HCI / game-design research',
    dataset: '19 participant-created Reddit research corpora and seven designer datasets (three user-provided, four using transcripts from three service-design interviews)',
    data_access: 'source Reddit data and participant annotations are not deposited in the anonymous manuscript; some Study 2 data were participant-owned/restricted',
    documents: 'Study 1 participants each manually annotated up to 200 texts; Study 2 document counts vary and are not fully reported',
    participants: '19 master\'s game-design students plus 7 designers (26 total)',
    corpus: 'Study 1 manual subsets range from 12 to 283 texts per participant in Table 2, with 6–68 codes; Study 2 produced 428 minutes of think-aloud data, 149 quotations and 63 codes',
    document_length: 'Study 1 Reddit texts; Study 2 sessions about 90 minutes; source-text lengths not reported',
    language: 'not explicitly reported; manuscript and quoted material are in English',
    sensitive: 'participant-provided and online discussion data; the paper tells participants to bring data only when permitted but reports no formal privacy/ethics protocol',
    model_family: 'OpenAI GPT plus OpenAI embeddings',
    model_version: 'GPT-4o and text-embedding-3-large; snapshots, temperature and other inference settings not reported',
    prompting: 'Sequential inductive coding with Markdown span annotations, accumulating codebook and few-shot positive/negative examples; users can edit instructions and examples; full inductive prompt appears in the appendix',
    adaptation: 'in-context learning only; no weight fine-tuning',
    agent_type: 'single-model interactive tool',
    agent_roles: 'span highlighter/open coder, code-description generator and broader-theme grouper',
    human_role: 'Humans manually create the baseline, select examples, change prompt instructions, visually compare annotations and may revise their own codes in response to the model; researchers analyze logs and participant reflections.',
    unit: 'text span/highlight and attached open code; participant-level code sets and example-set iterations',
    outputs: 'highlighted source spans, open codes/codebook, broader themes, IoU/MHD alignment scores and interaction logs',
    provenance: 'Generated annotations are anchored to verbatim text spans and discrepancy checks try to reconstruct altered source text; the interface displays model and human spans side by side.',
    baselines: 'participant manual annotations; randomly sampled example sets matched in size to human selections for Study 2',
    runs: 'Study 1 learning curves on 11 eligible participant datasets and extrapolation on 8; Study 2 uses three human-curated iterations and five random example sets per iteration; stochastic model reruns/seeds are not reported',
    metrics: 'span Intersection over Union; embedding-based modified Hausdorff distance between code sets; Pearson correlation; code-discovery rate',
    human_evaluation: '26 user-study participants provide manual annotations, surveys and think-aloud feedback; model outputs are compared to each participant\'s changing personal baseline rather than an independent gold interpretation.',
    evaluators: '19 game-design students with varied analysis experience and 7 designers; first author conducts reflexive thematic analysis, with no second analytic evaluator reported',
    irr: 'not applicable to individualized reflexive coding; no reliability statistic for the first-author thematic analysis',
    statistics: 'learning curves with least-squares asymptotic fit, Pearson r=.53 for example-to-target versus model-to-human code distance, metric trajectories and five-sample random baselines; uncertainty/significance tests are limited',
    results: 'More examples improved mean IoU and reduced MHD, but gains largely tracked code reuse and codebook stabilization. When target codes were unlike examples, model–human distance worsened (Pearson r=.53). Human-curated iteration improved later IoU relative to random selection, while users also changed their own coding after seeing model output.',
    efficiency: 'efficiency/scale benefits are asserted; no end-to-end time or cost comparison is reported',
    ethics: 'voluntary/unincentivized Study 1 and recruitment details are reported; the manuscript does not report IRB/ethics approval, consent language, data-governance protocol or a formal privacy analysis',
    resources: 'appendix prompt and detailed interface/method; GitHub is described as open source but the anonymous manuscript replaces the URL with “<link omitted for anonymous review>”',
    limitations: 'in-context learning mainly captures surface/codebook reuse; user difficulty understanding examples; risk of overfitting; Study 2 lacks a separate test set; researcher coding shifts during iteration',
    concerns: 'Study 2 optimizes against and visually exposes the same validation annotations without a held-out test set. Because users revise their own baseline after seeing model outputs, improved alignment can reflect human anchoring rather than model learning. MHD is model-dependent semantic proximity, not interpretive validity.',
    prior_relationship: 'Builds on the authors\' prior LLM coding workflow and related Research-for-Design studies; no duplicate archival version verified.',
    arr_relevance: 'Strong support for quote-span provenance, held-out testing and monitoring human-baseline drift. IoU/MHD can diagnose alignment but should be secondary to plural, blind, source-grounded human assessment.',
  },
  {
    id: 'jain_et_al_2026_multi_llm_dual_reliability',
    citation: 'Jain, Nilesh, Hyungil Suh, Seyi Adeyinka, Leor Roseman, and Aza Allsop. 2026. Multi-LLM Thematic Analysis with Dual Reliability Metrics: Combining Cohen\'s Kappa and Semantic Similarity for Qualitative Research Validation. arXiv:2512.20352v2.',
    title: 'Multi-LLM Thematic Analysis with Dual Reliability Metrics: Combining Cohen\'s Kappa and Semantic Similarity for Qualitative Research Validation',
    authors: 'Nilesh Jain; Hyungil Suh; Seyi Adeyinka; Leor Roseman; Aza Allsop',
    year: 2026,
    venue: 'arXiv:2512.20352v2',
    publication_type: 'preprint / open-source system paper',
    peer_reviewed: 'not peer reviewed',
    history: 'The database record is dated 2025 from arXiv identifier 2512.20352, but the inspected current v2 is dated 2026-02-14 and the manuscript itself 2026-02-17. Treat as a 2026 publication-family handoff, not distinct 2025 evidence.',
    url: 'https://arxiv.org/abs/2512.20352',
    doi: '10.48550/arXiv.2512.20352',
    citation_count: 'not collected; official arXiv v2 full text inspected 2026-08-24',
    classification: 'core',
    family: 'LLM-Thematic-Analysis-Tool / arXiv:2512.20352 version family; current evidence version is 2026',
    objective: 'Provide a browser-based multi-run/multi-provider thematic-analysis tool that quantifies run stability through pairwise kappa, semantic similarity and consensus themes.',
    claimed_method: 'multi-perspective LLM thematic analysis with ensemble validation and dual reliability metrics',
    actual_method: 'Gemini 2.5 Pro, GPT-4o and Claude 3.5 Sonnet each analyze one ketamine-art-therapy interview six times under a JSON theme prompt. Theme descriptions are embedded, clustered above cosine .70 and counted across runs; pairwise theme presence/absence kappa and average cosine similarity are summarized, with no human interpretation baseline.',
    inductive_deductive: 'inductive theme generation constrained by prompt-requested domains and a fixed consensus/clustering procedure',
    domain: 'psychedelic-assisted psychotherapy / art therapy',
    dataset: 'one semi-structured ketamine art-therapy therapist interview',
    data_access: 'full transcript is public in the project GitHub repository',
    documents: '1 transcript',
    participants: '1 therapist',
    corpus: '28,377 characters and 173 lines',
    document_length: '28,377 characters / 173 lines',
    language: 'English',
    sensitive: 'clinical/practice interview about therapy; public transcript, but consent/publication-governance details are not reported beyond thanking the therapist',
    model_family: 'Google Gemini, OpenAI GPT and Anthropic Claude',
    model_version: 'Gemini 2.5 Pro, GPT-4o and Claude 3.5 Sonnet; provider snapshots and API dates not reported',
    prompting: 'Custom JSON prompt requests core themes, therapist methodology, client experiences, future outlook, supporting quotes and a {seed} run identifier; temperature .7 and six numeric seed values are reported',
    adaptation: 'none; all-MiniLM-L6-v2 embeddings are run locally for similarity/clustering',
    agent_type: 'single-agent repetitions within each model, then cross-model comparison; not a deliberative multi-agent system',
    agent_roles: 'independent theme generator and deterministic consensus aggregator',
    human_role: 'Authors select the corpus, prompt, threshold and metrics and interpret outputs; no human thematic analysis or independent theme-validity judgment is used.',
    unit: 'generated theme description and its presence/absence across runs',
    outputs: 'themes with supporting quotes, pairwise kappa/cosine matrices, consensus theme clusters and frequency labels',
    provenance: 'Prompt requests supporting quotes and the transcript/output examples are public, but reported aggregate metrics are not linked to a human-validated source-to-theme audit.',
    baselines: 'three LLM families compared with one another; no manual coder, established codebook or external-validity baseline',
    runs: '6 per model (18 total) with reported values 42, 123, 456, 789, 1011 and 1213 at temperature .7',
    metrics: 'pairwise Cohen\'s kappa on theme presence/absence, all-MiniLM-L6-v2 cosine similarity, >=.70 semantic clustering, >=50% consensus frequency and Pearson correlation between kappa and cosine',
    human_evaluation: 'none for theme correctness, completeness, depth, cultural validity or source fidelity',
    evaluators: 'authors only; one therapist supplied the dataset but is not reported as an output evaluator',
    irr: 'No human IRR. Mean inter-run kappa is reported as .907 Gemini, .853 GPT-4o and .842 Claude; these are model self-consistency statistics.',
    statistics: '15 pairwise comparisons per model, mean/range summaries, Pearson r=.97 between kappa and cosine; no confidence intervals or held-out validation',
    results: 'Gemini produced 6 consensus themes, GPT-4o 5 and Claude 4; only 1–2 themes per model reached 5/6 runs. Reported kappa/cosine were .907/95.3%, .853/92.6% and .842/92.1%, respectively; cross-model theme overlap is described as 60–70%.',
    efficiency: 'claims $0.15–$0.20 per transcript versus $20–$40 human coding and table estimates of $3–$6 versus $400–$800 for 20 documents; derivation and equivalent synthesis/review labor are not empirically demonstrated',
    ethics: 'local preprocessing and API-key handling are described, but raw transcripts are sent to providers at analysis initiation. Consent, IRB status, data license and clinical privacy review for the public therapist transcript are not reported.',
    resources: 'code, live app, transcript and examples: https://github.com/NileshArnaiya/LLM-Thematic-Analysis-Tool and https://azalab-llm-tool.vercel.app/',
    limitations: 'single dataset; cultural/domain bounds; prompt dependence; inability to perform reflexivity or ethical judgment; need for human oversight and future human comparison',
    concerns: 'High internal consistency is not external validity. Kappa requires a stable item/category universe, but theme equivalence is first induced by an embedding threshold; this makes the chance-corrected interpretation unclear. Putting {seed} in a prompt is not proof that every provider honors a stochastic seed. Claims of rigorous validation and human-comparable reliability exceed one transcript with no human baseline.',
    prior_relationship: 'Current v2 belongs in the 2026 stream; exact-title/version deduplication is required before master merge.',
    arr_relevance: 'Useful implementation for repeated-run instability and consensus displays, but a negative example for treating self-consistency as validity. ARR should pair such runs with blind human source-grounded evaluation and preserve minority interpretations.',
  },
  {
    id: 'wen_et_al_2025_neo_grounded_theory',
    citation: 'Wen, Shuide, Beier Ku, Teng Wang, Mingyang Zou, and Yang Yang. 2025. Neo-Grounded Theory: A Methodological Innovation Integrating High-Dimensional Vector Clustering and Multi-Agent Collaboration for Qualitative Research. arXiv:2509.25244v1.',
    title: 'Neo-Grounded Theory: A Methodological Innovation Integrating High-Dimensional Vector Clustering and Multi-Agent Collaboration for Qualitative Research',
    authors: 'Shuide Wen; Beier Ku; Teng Wang; Mingyang Zou; Yang Yang',
    year: 2025,
    venue: 'arXiv:2509.25244v1',
    publication_type: 'preprint',
    peer_reviewed: 'not peer reviewed',
    history: 'arXiv v1; no journal/conference version, DOI or code archive identified',
    url: 'https://arxiv.org/abs/2509.25244',
    doi: '10.48550/arXiv.2509.25244',
    citation_count: 'not collected; official arXiv full text inspected 2026-08-24',
    classification: 'core',
    family: 'visually impaired gamers dataset previously analyzed in Yue et al. (2024); NGT is a new claimed method on the same corpus',
    objective: 'Propose Neo-Grounded Theory, combining vector clustering, parallel LLM coding agents and human prompt refinement, and compare it with traditional grounded-theory and ChatGPT-4 Turbo analyses.',
    claimed_method: 'grounded theory / Neo-Grounded Theory with computational emergence, distributed cognition and augmented theoretical sensitivity',
    actual_method: 'Eight Chinese interview transcripts are segmented, embedded with text-embedding-3-small, hierarchically clustered and distributed across 8–12 concurrent coding agents for open/axial/selective coding and integration. One automated and one expert-prompt-refined NGT output are compared with a previously/manual baseline and ChatGPT-4 Turbo. Three LLMs, rather than human experts, assign quality scores.',
    inductive_deductive: 'claimed inductive grounded theory; clustering thresholds, staged prompts and expert-refined tension/contradiction instructions impose substantial structure',
    domain: 'disability, gaming, well-being and social participation',
    dataset: 'eight semi-structured interviews with visually impaired gamers, originally collected February–March 2022',
    data_access: 'restricted secondary interview data; no transcript deposit reported',
    documents: '8 transcripts',
    participants: '8 visually impaired gamers, ages 18–41',
    corpus: 'about 40,000 Chinese characters',
    document_length: '60–90 minutes per interview',
    language: 'Chinese',
    sensitive: 'disability and well-being interviews; deidentified secondary data',
    model_family: 'OpenAI GPT/embeddings and unspecified NGT coding LLM agents; Claude and DeepSeek used as evaluators',
    model_version: 'ChatGPT-4 Turbo “current as of January 2024”; text-embedding-3-small; evaluator labels ChatGPT-5.0, Claude Opus 4.1 and DeepSeek V3.1; exact NGT agent model and snapshots are not reported',
    prompting: 'Three-stage coding prompts, semantic-cluster distribution and JSON output; Exp. 2 adds expert instructions to focus on tensions, contradictions and divergent pathways. Only brief example prompts are shown.',
    adaptation: 'no reported weight tuning; human prompt refinement and fixed clustering threshold',
    agent_type: 'multi-agent',
    agent_roles: 'parallel cluster-level open/axial/selective coders and cross-cluster theory integrator; exact role prompts and model assignments not reported',
    human_role: 'Two researchers provide the claimed manual baseline; an expert reviews Exp. 1 and refines Exp. 2 prompts; original participants perform unspecified member checking where possible; a methodologist reviews an unspecified audit subset.',
    unit: '50–200-word semantic segment, cluster, code, subtheme and theoretical framework',
    outputs: '268–289 open codes, 42–56 subthemes, 7–9 main themes, theoretical diagrams, quality scores and cost/time estimates',
    provenance: 'Authors claim complete audit trails and source grounding, but no trail, transcript-to-code map, full prompts, outputs or code is supplied for inspection.',
    baselines: 'traditional manual NVivo grounded theory, ChatGPT-4 Turbo, automated NGT Exp. 1 and human-refined NGT Exp. 2',
    runs: 'one reported output per condition; no stochastic reruns, seeds, order tests or threshold ablation',
    metrics: 'processing time, cost, code/theme counts, claimed Jaccard and semantic alignment, coverage/redundancy, LLM-scored six-dimension quality and Krippendorff alpha among three LLM evaluators',
    human_evaluation: 'The main quality table explicitly replaces human experts with three LLM judges. Elsewhere the paper claims multiple human experts, member checking and a methodologist audit but supplies no counts, judgments or results.',
    evaluators: 'three LLM judges for reported quality scores; vague/unquantified human experts, participants and methodologist for other checks',
    irr: 'LLM-evaluator Krippendorff alpha=.91; manual baseline claims h > .85 (apparently a typesetting error for kappa) without denominator or calculation details',
    statistics: 'descriptive single-run comparisons; no uncertainty or inferential testing',
    results: 'Reported total times are 504 hours manual, 24 hours ChatGPT, .5 hours automated NGT and 3 hours human-refined NGT. LLM judges score NGT Exp. 2 .904 versus manual .883. Reported manual–NGT Jaccard is 75.4% and semantic alignment 83%; NGT Exp. 2 produces 268 codes, 52 subthemes and 9 themes.',
    efficiency: 'Results table reports $12,800 manual, $425 ChatGPT and $95 NGT (99.3% reduction), while the abstract reports a 95.8% reduction and later prose says 96%; assumptions include $50/hour and projected sublinear/logarithmic scaling without empirical scale tests.',
    ethics: 'Source approval is reported as Renmin University School of Journalism and Communication #20220028, with secondary-analysis consent and 50 RMB compensation; deidentification, encryption/access/deletion controls and respectful framing are described.',
    resources: 'no code, data, complete prompts, audit trail or output package reported',
    limitations: 'single domain, Chinese-only, modest 40,000-character corpus, theoretical-evaluation subjectivity, loss of metaphor/narrative/cultural nuance and technical gatekeeping',
    concerns: 'The reported primary quality advantage is an LLM-as-judge self-evaluation with no human outcome table. Methods contradict themselves about whether human experts evaluated outputs. Cost-reduction percentages conflict; clustering is “fixed at .52” but later sensitivity is described for .80–.90; logarithmic scaling is asserted from one corpus. The paper does not identify the core NGT coding model or enable reproduction.',
    prior_relationship: 'Reuses the Yue et al. visually impaired gamer corpus and its manual/ChatGPT analyses; dependency should be recorded rather than counted as an independent dataset replication.',
    arr_relevance: 'A low-confidence cautionary case: it motivates agent audit trails and human refinement, but its headline quality, novelty, speed and cost claims should not inform ARR ranking without reproducible runs, human-blind evaluation and dependency adjustment.',
  },
  {
    id: 'cevik_abu_zidan_2025_efast_llm_thematic_analysis',
    citation: 'Cevik, Arif Alper, and Fikri M. Abu-Zidan. 2025. Online Extended Focused Assessment with Sonography for Trauma (EFAST) Course Enhanced Knowledge and Perceived Confidence Among Medical Trainees During the COVID-19 Pandemic Disaster. World Journal of Emergency Surgery 20:30. https://doi.org/10.1186/s13017-025-00604-8.',
    title: 'Online extended focused assessment with sonography for trauma (EFAST) course enhanced knowledge and perceived confidence among medical trainees during the COVID-19 pandemic disaster',
    authors: 'Arif Alper Cevik; Fikri M. Abu-Zidan',
    year: 2025,
    venue: 'World Journal of Emergency Surgery 20:30',
    publication_type: 'journal article',
    peer_reviewed: 'peer reviewed',
    history: 'received 2024-10-23, accepted 2025-03-31, published 2025-04-09; PMCID PMC11980233, PMID 40205423',
    url: 'https://doi.org/10.1186/s13017-025-00604-8',
    doi: '10.1186/s13017-025-00604-8',
    citation_count: 'not collected; publisher/PMC full text inspected 2026-08-24',
    classification: 'core',
    family: 'applied EFAST-course evaluation; LLM analysis is one secondary qualitative component',
    objective: 'Evaluate an online EFAST course\'s effects on knowledge and perceived confidence; use ChatGPT/Custom-GPT and NotebookLM to assist analysis of open-ended course feedback.',
    claimed_method: 'Braun and Clarke six-step inductive thematic analysis with human, Custom-GPT and NotebookLM “triangulation”',
    actual_method: 'Authors cleaned/anonymized 220 post-course comments, uploaded CSV data to ChatGPT-4o, converted them to PDF, configured a Custom-GPT around Braun–Clarke steps, and uploaded the PDF to Custom-GPT and NotebookLM. The paper reports 14 codes and three themes but no system-specific outputs, comparison procedure or adjudication trace.',
    inductive_deductive: 'claimed inductive; Custom-GPT is configured with a predefined six-step methodological frame',
    domain: 'medical education / emergency ultrasound',
    dataset: 'open-ended post-course EFAST feedback from a global online course',
    data_access: 'not available; data-availability statement says no datasets were generated or analyzed, contradicting the reported survey dataset',
    documents: '220 written feedback responses',
    participants: '220 feedback respondents among 938 exit-survey completers; 1,758 enrolled and 1,515 started',
    corpus: '220 comments; 14 codes and 3 themes',
    document_length: 'short open-ended survey responses; lengths not reported',
    language: 'course and feedback appear to be English; language is not explicitly reported for the comments',
    sensitive: 'anonymized educational survey responses; user IDs were removed after pre/post matching',
    model_family: 'OpenAI GPT and Google NotebookLM',
    model_version: 'ChatGPT-4o, a study-specific Custom-GPT, and NotebookLM; snapshots/access dates not reported',
    prompting: 'Custom-GPT objectives and Braun–Clarke steps were configured, but exact instructions, prompts and output constraints are not supplied',
    adaptation: 'Custom-GPT configuration only; no weight fine-tuning reported',
    agent_type: 'two independent tools plus human input, described as triangulation rather than an integrated multi-agent workflow',
    agent_roles: 'data-format converter, inductive thematic coder and emergent-theme assistant',
    human_role: 'Two authors jointly analyzed data, established the Custom-GPT objective/method and compared human input with two model tools; division of coding, validation and adjudication labor is not described.',
    unit: 'one written course-feedback response',
    outputs: '14 codes and three themes: Content Delivery and Engagement, Technical and Structural Improvements, and Positive Learning Experience',
    provenance: 'Results include selected participant quotations labeled only by country, but no complete comment–code–theme table or tool-specific provenance.',
    baselines: 'claimed comparison among human manual input, Custom-GPT and NotebookLM; no separate outputs or concordance results are reported',
    runs: 'not reported',
    metrics: 'none for qualitative/LLM analysis; quantitative course outcomes use Wilcoxon tests and Cohen\'s d but do not evaluate the LLM method',
    human_evaluation: 'authors jointly interpret and report final themes; there is no blinded assessment of model outputs',
    evaluators: 'two authors; qualitative-method expertise and separate coding roles not reported',
    irr: 'not reported',
    statistics: 'no qualitative-analysis statistics; 220/938 (23.5%) exit-survey respondents supplied comments',
    results: 'The LLM-assisted analysis yields 14 codes and three broad themes about engagement, technical/structural improvements and positive experience. No evidence distinguishes which tool generated or changed any code/theme, or whether triangulation improved accuracy.',
    efficiency: 'paper asserts improved processing efficiency but reports no qualitative-analysis time, cost or human-review burden',
    ethics: 'UAE University deemed the education evaluation exempt (ERS_2020_6130); surveys were optional, identifiers removed and database access restricted',
    resources: 'no prompts, code, model settings, comments or audit outputs; the data-availability statement is internally inaccurate',
    limitations: 'authors note only 23.5% supplied feedback and possible response bias, but do not discuss LLM-specific validity, instability, privacy or model dependence',
    concerns: 'The triangulation and “increased analytical accuracy” claims are unsupported because model-specific outputs, human comparison and disagreements are absent. Broad positive themes can reflect response/self-selection bias. Upload pathway and provider data governance are not described. “No datasets ... analyzed” is false on the face of the methods.',
    prior_relationship: 'No related LLM-method publication identified; primary contribution is course evaluation rather than qualitative-computing methodology.',
    arr_relevance: 'An applied reporting-failure case showing why ARR should require exact prompts/models, separate system outputs, human adjudication, full provenance and truthful data availability before an LLM-assisted thematic analysis is auditable.',
  },
  {
    id: 'liu_et_al_2025_qualitative_coding_gpt4',
    citation: 'Liu, Xiner, Andres Felipe Zambrano, Ryan S. Baker, Amanda Barany, Jaclyn Ocumpaugh, Jiayi Zhang, Maciej Pankiewicz, Nidhi Nasiar, and Zhanlan Wei. 2025. Qualitative Coding with GPT-4: Where It Works Better. Journal of Learning Analytics 12(1):169–185. https://doi.org/10.18608/jla.2025.8575.',
    title: 'Qualitative Coding with GPT-4: Where it Works Better',
    authors: 'Xiner Liu; Andres Felipe Zambrano; Ryan S. Baker; Amanda Barany; Jaclyn Ocumpaugh; Jiayi Zhang; Maciej Pankiewicz; Nidhi Nasiar; Zhanlan Wei',
    year: 2025,
    venue: 'Journal of Learning Analytics 12(1):169–185',
    publication_type: 'journal article',
    peer_reviewed: 'peer reviewed',
    history: 'submitted 2024-07-27, accepted 2025-02-11 and published 2025-03-17',
    url: 'https://doi.org/10.18608/jla.2025.8575',
    doi: '10.18608/jla.2025.8575',
    citation_count: 'not collected; official journal full text inspected 2026-08-24',
    classification: 'core',
    family: 'Three educational-dataset study drawing codebooks/data from Barany et al. (2024), Yi et al. (2020), Pinto et al. (2023) and Zambrano et al. (2024)',
    objective: 'Determine which zero-shot, few-shot, context and embedding strategies best reproduce human qualitative codes across constructs with different clarity, concreteness, objectivity, granularity and specificity.',
    claimed_method: 'automated qualitative coding with GPT-4 across three educational datasets',
    actual_method: 'Researchers begin with previously or newly inductively developed codebooks, resolve human disagreements to one reference label per unit, then run separate binary 0/1 GPT-4 classifiers for each predefined construct. The evaluation is supervised/deductive multi-label classification, not emergent thematic interpretation.',
    inductive_deductive: 'hybrid upstream codebook development; the evaluated GPT task is deductive binary code application',
    domain: 'education: Grade 9 math tutoring, middle-school astronomy/Minecraft observations and university introductory programming',
    dataset: 'Saga Algebra I tutoring transcripts; WHIMC observations; RunCode C# debugging submissions',
    data_access: 'Study 3 raw deidentified data and coded versions are linked for sharing; Studies 1–2 are not deposited in the paper',
    documents: '4 tutoring transcripts; 200 WHIMC observations evaluated; 44,448 RunCode submissions in the source corpus, with the exact evaluated conditional-statement subset not reported',
    participants: '6 ninth-grade tutoring students, 76 WHIMC learners and 169 RunCode students; human coder counts are two in Studies 1–2 and underreported for Study 3',
    corpus: 'Study 1: 990 instructor lines; Study 2: 200 observations; Study 3: source corpus 44,448 submissions over 146 tasks, evaluation-subset denominator not reported',
    document_length: 'Study 1 has four 60-minute sessions; Study 2 observations are short posts; Study 3 submissions often exceed 50 code lines but only changed lines are sent',
    language: 'English natural-language data; C# source code from a Polish course',
    sensitive: 'deidentified education data involving minors and university students; Study 3 sharing is described as deidentified',
    model_family: 'OpenAI GPT and OpenAI embeddings',
    model_version: 'gpt-4-turbo-2024-04-09 and text-embedding-3-small',
    prompting: 'Temperature 0, default remaining parameters; construct definition for zero-shot, annotated positive examples for few-shot, positive/negative examples for programming, and study/three-line context for tutoring. Prompts were iteratively tuned on separate validation data; a .60 embedding threshold was selected on 100 WHIMC lines.',
    adaptation: 'no weight fine-tuning; iterative prompt engineering and example selection',
    agent_type: 'single-model binary classifier run independently for each construct',
    agent_roles: 'deductive code applier; embedding similarity is used for one continuing-discussion construct',
    human_role: 'Researchers develop/refine codebooks, double-code and adjudicate reference labels, tune prompts and examples, rate construct properties and inspect errors.',
    unit: 'tutor utterance line, student observation, or changed lines between consecutive code submissions',
    outputs: 'binary label per construct/unit, kappa/precision/recall, construct-property ratings and method recommendations',
    provenance: 'Each prediction maps to a source unit and code; error examples are quoted, but complete predictions/prompts and most source data are not public.',
    baselines: 'human adjudicated labels; zero-shot versus several few-shot/context strategies and one embedding method',
    runs: 'Study 1 and Study 2 coding were run three times and averaged; Study 3 repetition count is not explicitly reported; random seeds are not reported',
    metrics: 'Cohen\'s kappa, precision, recall, construct frequency, Cronbach alpha for a questionable property-rating aggregation and Spearman correlations',
    human_evaluation: 'Two researchers independently code/adjudicate Studies 1–2; eleven qualitative researchers rate ten Study 1 constructs. Study 3 human-reference construction is not described with equal detail.',
    evaluators: 'two coders in Study 1, two in Study 2, eleven construct-property raters; Study 3 coder number/expertise underreported',
    irr: 'Study 1 human–human kappa .24–.87 by construct; Study 2 .73–.97; Study 3 .32–1.00. Disagreements were adjudicated before human–GPT evaluation.',
    statistics: 'per-construct kappa/precision/recall averaged over runs; Spearman correlations on only ten Study 1 constructs; Cronbach alpha .75–.93 across unlike rating dimensions',
    results: 'At least one prompting approach reached kappa >=.70 for 25/34 constructs. Context helped temporally dependent tutoring codes; few-shot examples sometimes overgeneralized; embedding performed best for continuing discussion (kappa .93). GPT struggled when humans disagreed and on less concrete/context-dependent constructs.',
    efficiency: 'API workflow is described as more efficient than chat copy/paste, but no measured time or cost is reported',
    ethics: 'No IRB, consent, data-use approval or privacy-governance statement is reported despite deidentified data from minors and students',
    resources: 'paper prints representative prompts and links Study 3 deidentified raw/coded data; executable code, complete predictions and Studies 1–2 data are not reported',
    limitations: 'binary one-construct-at-a-time design; prompt-method effectiveness varies; few-shot overgeneralization; context can add noise; need other LLMs, multi-code prompts and more complex constructs',
    concerns: 'Prompt/example/context choices were iteratively optimized, but validation/test denominators and leakage controls are incompletely reported; the embedding threshold used half of Study 2 data. The narrative prints Questioning zero-shot kappa as −.91 while Table 2 and discussion support +.91. Adjudicated single ground truth suppresses legitimate interpretive plurality, and Cronbach alpha is misapplied to six distinct construct-property dimensions.',
    prior_relationship: 'Study 1 directly reuses a GPT-refined codebook from Barany et al. (2024); Studies 2–3 refine earlier codebooks. Dependency-adjusted synthesis should not count these as three independent model-development replications.',
    arr_relevance: 'Material evidence for construct-stratified evaluation, exact model snapshots, repeated runs and context ablations. It favors source-level kappa/precision/recall for deductive coding, while highlighting leakage, plurality and denominator requirements for ARR.',
  },
];

const evidenceRecords = values.map(evidence);

const q = [
  quality({
    id: values[0].id, title: values[0].title, classification: values[0].classification,
    scores: [2, 1, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1],
    rationales: [
      'Wizard-of-Oz roles and human thematic process are clear.',
      'Seventeen realistic sessions support user-experience claims, not downstream interview-quality claims.',
      'GPT-4o is named, but exact prompt, snapshot and settings are missing.',
      'No human-only or alternative-system control.',
      'Participant reflections are rich but subjective and confounded by the Wizard.',
      'No automatic quality metric.',
      'Consensus analysis and participant differences preserve some plurality.',
      'Labeled quotations ground findings, but the generated-question audit trail is incomplete.',
      'No reruns or controlled repeated conditions.',
      'Consent/anonymization are reported; institutional review status is absent.',
      'No verified prompt, code or data package.',
      'Human-gatekeeping conclusions are cautious; efficiency/depth implications exceed the design.',
    ],
  }),
  quality({
    id: values[1].id, title: values[1].title, classification: values[1].classification,
    scores: [2, 2, 1, 2, 2, 1, 2, 2, 0, 2, 1, 1],
    rationales: [
      'Human and both LLM analysis steps are explicit.',
      'Ninety-nine real interviews with a common 20-transcript comparison are appropriate.',
      'Prompts are supplementary, but snapshot, seeds and run count are missing.',
      'A detailed human baseline and two model configurations are compared.',
      'Double human coding and quote-level comparison are substantial.',
      'Counts/overlap are informative but do not fully measure interpretive validity.',
      'Differences in granularity and absent themes are preserved rather than collapsed.',
      'Quote fidelity, omissions and summaries are directly audited.',
      'Only one apparent run per configuration.',
      'Trial approval, registration, anonymization and no-PII input are reported.',
      'Prompts/cost supplement exists; code, outputs and data are unavailable.',
      'Hybrid recommendation is proportionate, but abstract kappa wording and saturation claims overstate.',
    ],
  }),
  quality({
    id: values[2].id, title: values[2].title, classification: values[2].classification,
    scores: [1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1],
    rationales: [
      'It evaluates interpretive annotations rather than performing thematic analysis.',
      'Two authentic education tasks and substantial expert judgments fit the metric question.',
      'Models, prompts, aggregation and perturbations are detailed.',
      'Broad lexical, vector, topic, LLM-judge and human-oracle baselines.',
      'Domain experts label randomized triplets at meaningful scale.',
      'Metrics are validated against expert rankings and stress-tested for style confounds.',
      'Relative judgments recognize legitimate free-text variation.',
      'Task/annotation mappings and consent-permitted data are shared.',
      'Ten samples, 100 bootstraps and sample-size curves assess stability.',
      'IRB, consent, deidentification and compensation are explicit.',
      'Code, prompts and substantial data are open.',
      'Claims are mostly bounded, but domain transfer and scalar aggregation need caution.',
    ],
  }),
  quality({
    id: values[3].id, title: values[3].title, classification: values[3].classification,
    scores: [1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0],
    rationales: [
      'The LDA-to-theme workflow is described but conflates topic labeling with inductive thematic analysis.',
      'Real posts are relevant, but corpus size is missing and only top-ten posts represent each topic.',
      'Model families/prompts are partial; snapshots and actual seed/temperature values are absent.',
      'Independent human labeling provides a useful baseline.',
      'Two authors compare outputs, but the GPT-4 self-judge weakens independence.',
      'The ad hoc 79.7% category is not a valid reliability coefficient and bundles divergence as agreement.',
      'Some differing abstraction levels are retained, but outputs are forced into a single scale.',
      'Examples expose thin one-post support; full mappings are unavailable.',
      'No reruns or order/seed sensitivity tests.',
      'Public-data rationale is given, but contextual privacy is not examined.',
      'Prompt appendix exists; data and code do not.',
      'Automation/reliability claims exceed the internally inconsistent, self-evaluated evidence.',
    ],
  }),
  quality({
    id: values[4].id, title: values[4].title, classification: values[4].classification,
    scores: [2, 1, 1, 0, 1, 0, 2, 1, 0, 0, 2, 2],
    rationales: [
      'The seven-step conceptual process and workshop synthesis are clear.',
      'A single workshop answers perception questions; the illustrative empirical corpus is underdescribed.',
      'Prompt modules are described but exact model/configuration and runs are absent.',
      'No empirical model baseline.',
      'Experienced researchers provide reflections, not output-quality judgments.',
      'No model-performance metrics.',
      'Interpretive agency, divergent taxonomies and human validation are central.',
      'Example tables retain quotations/participants; workshop finding counts are absent.',
      'No stability experiment.',
      'No ethics/consent/privacy reporting.',
      'A dedicated Zenodo artifact shares workshop materials.',
      'Authors clearly limit the workshop and reject model-replacement claims.',
    ],
  }),
  quality({
    id: values[5].id, title: values[5].title, classification: values[5].classification,
    scores: [2, 2, 1, 1, 2, 1, 2, 1, 1, 0, 1, 2],
    rationales: [
      'The coding workflow and distinction between surface reuse and induction are unusually explicit.',
      'Two realistic studies with individualized human annotations fit alignment questions.',
      'Prompt is appended, but snapshot/configuration and public code URL are incomplete.',
      'Manual and random-selection baselines help, though no external interpretation baseline exists.',
      'Twenty-six users, logs and think-aloud data provide substantial human evidence.',
      'IoU/MHD diagnose alignment, not interpretive validity, and MHD is embedding-dependent.',
      'Personal lenses and reciprocal influence are directly analyzed.',
      'Span anchoring is strong, but data/output artifacts are not public.',
      'Random baselines and iterations are present; stochastic reruns and a test set are absent.',
      'No formal ethics/privacy reporting.',
      'Appendix prompt and detailed interface exist; anonymous repository link is unavailable.',
      'Conclusions explicitly acknowledge surface-level learning, baseline shift and overfitting.',
    ],
  }),
  quality({
    id: values[6].id, title: values[6].title, classification: values[6].classification,
    scores: [1, 1, 2, 0, 0, 1, 1, 2, 2, 0, 2, 0],
    rationales: [
      'Theme-generation steps are described, but reliability is equated with repeatability.',
      'One public transcript is insufficient for broad validation claims.',
      'Architecture, temperature, seeds, thresholds and code are detailed, though snapshots are absent.',
      'No human or external-validity baseline.',
      'No human evaluation of thematic quality.',
      'Cosine supports stability; kappa item construction and interpretive labels are not validated.',
      'Moderate-frequency themes are retained for review, but no human plurality is sampled.',
      'Supporting quotes and the transcript are available.',
      'Six runs per model directly test apparent stability.',
      'Consent/IRB/data-license and provider privacy are underreported.',
      'Open code, app and transcript.',
      '“Rigorous validation” and human-comparable reliability claims exceed internal consistency evidence.',
    ],
  }),
  quality({
    id: values[7].id, title: values[7].title, classification: values[7].classification,
    scores: [1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 0, 0],
    rationales: [
      'The pipeline is verbose, but core agent/model details and grounded-theory fidelity are unclear.',
      'Eight real interviews fit a proof of concept but not scaling/generalization claims.',
      'Embeddings/clustering are named; prompts, exact coding model, code and outputs are absent.',
      'Manual and ChatGPT comparators exist but appear partly inherited and are not reproducibly reconstructed.',
      'Headline quality is judged by LLMs; vague human checks are unreported.',
      'Single-run percentages and LLM scores lack validated definitions and uncertainty.',
      'The paper acknowledges culture/metaphor limits but optimizes toward one framework.',
      'Traceability is asserted without inspectable mappings.',
      'No reruns or threshold/order robustness despite strong reproducibility claims.',
      'Source approval, consent and data-protection steps are detailed.',
      'No data, prompts, code or audit trail.',
      'Quality, scaling, novelty and cost conclusions are disproportionate and internally inconsistent.',
    ],
  }),
  quality({
    id: values[8].id, title: values[8].title, classification: values[8].classification,
    scores: [1, 2, 1, 1, 0, 0, 0, 1, 0, 2, 0, 0],
    rationales: [
      'The tools and nominal six-step method are named, but the actual coding/adjudication procedure is opaque.',
      'Two hundred twenty real comments are adequate for the applied question.',
      'Models are named; prompts, settings and tool-specific outputs are absent.',
      'A three-way “triangulation” is claimed but never reported separately.',
      'No independent or blinded assessment of model output.',
      'No qualitative/LLM performance metric.',
      'Three broad final themes conceal alternative readings and system differences.',
      'Selected quotations ground themes, but complete provenance is absent.',
      'No reruns or stability checks.',
      'Exemption identifier, optional participation and deidentification are reported.',
      'No data, prompt, code or audit resource; data statement is inaccurate.',
      'Claims of increased accuracy/efficiency are unsupported by comparative evidence.',
    ],
  }),
  quality({
    id: values[9].id, title: values[9].title, classification: values[9].classification,
    scores: [2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 1, 1],
    rationales: [
      'The evaluated task is clearly identified as deductive binary code application.',
      'Three authentic educational datasets span text and source code.',
      'Exact GPT snapshot, temperature, prompts and tuning strategy are described.',
      'Human labels and multiple prompting/embedding baselines are compared.',
      'Double coding, adjudication, property raters and detailed error analysis are strong, though Study 3 is underreported.',
      'Kappa/precision/recall are appropriate for the fixed-label task.',
      'Adjudication collapses legitimate interpretive plurality to one label.',
      'Predictions map to source units and error cases are shown.',
      'Study 1–2 use three runs; Study 3 run reporting is incomplete.',
      'No ethics, consent or governance report for student/minor data.',
      'Prompts and Study 3 data are partly available; code and other data are not.',
      'Construct-specific conclusions are supported, but co-researcher/trustworthiness language is broader than the binary task.',
    ],
  }),
];

const decisions = [
  ['TA-0670', 'include_adjacent', values[0].id, 'Full text evaluates LLM-generated follow-up questions during qualitative data collection, not LLM analysis; retained as adjacent governance and human-gatekeeping evidence.'],
  ['TA-0682', 'include_core', values[1].id, 'Full text directly compares human, out-of-the-box and knowledge-base GPT-4o thematic-analysis workflows on 99 interviews.'],
  ['TA-0686', 'include_adjacent', values[2].id, 'Full text validates expert-aligned evaluation of open-ended interpretive annotations; no actual codebook/theme generation, so adjacent.'],
  ['TA-0729', 'include_core', values[3].id, 'Peer-reviewed full text directly compares human and GPT thematic interpretation of 310 LDA topics, retained with self-judge and arithmetic cautions.'],
  ['TA-0735', 'include_core', values[4].id, 'Full text presents and illustrates a substantive human–LLM thematic-analysis process and an empirical expert workshop, though not a performance evaluation.'],
  ['TA-0743', 'include_core', values[5].id, 'Full text evaluates an open-source LLM coding workflow, alignment metrics and human–AI iteration across two designer studies.'],
  ['TA-0767', 'include_core', values[6].id, 'Current full text directly evaluates repeated-run LLM thematic analysis; version inspection resolves the evidence record to the 2026 arXiv v2 family rather than distinct 2025 evidence.'],
  ['TA-0772', 'include_core', values[7].id, 'Full text directly proposes and evaluates multi-agent grounded-theory analysis, retained despite severe reproducibility and evaluation-validity concerns.'],
  ['TA-0776', 'include_core', values[8].id, 'Peer-reviewed applied study uses ChatGPT-4o, Custom-GPT and NotebookLM as thematic analysts; retained as a low-transparency use case under the methodological-incongruence rule.'],
  ['TA-0791', 'include_core', values[9].id, 'Peer-reviewed full text directly evaluates exact-version GPT-4 qualitative code application across three educational datasets.'],
].map(([screen_id, full_text_decision, paper_id, reason]) => ({screen_id, full_text_decision, paper_id, reason}));

const out = {
  metadata: {
    title: '2025 database-candidate full-text assessment batch 04',
    generated_utc: '2026-08-25T05:35:00Z',
    source_screen: 'research/screening_2025_resolution.json',
    screen_ids: decisions.map((decision) => decision.screen_id),
    retrieved_count: decisions.length,
    assessed_count: decisions.length,
    include_core_count: decisions.filter((decision) => decision.full_text_decision === 'include_core').length,
    include_adjacent_count: decisions.filter((decision) => decision.full_text_decision === 'include_adjacent').length,
    exclude_count: decisions.filter((decision) => decision.full_text_decision === 'exclude').length,
    merge_status: 'candidate-only; do not merge until parent review',
    version_note: 'TA-0767 is extracted once as the current 2026 arXiv v2 family despite its 2025 database/arXiv identifier. TA-0670 has a 2025 arXiv v1 but only an unverified placeholder 2026 ACM reference block. No placeholder DOI is treated as real.',
    extraction_columns: columns,
    extraction_column_count: columns.length,
    quality_dimensions: dimensions,
    quality_scoring: prior.metadata.quality_scoring,
  },
  screening_decisions: decisions,
  evidence_records: evidenceRecords,
  quality_scores: q,
};

for (const record of out.evidence_records) {
  if (Object.keys(record).length !== 52) throw new Error(`${record['Paper ID']} does not have 52 fields`);
}
for (const score of out.quality_scores) {
  if (Object.keys(score['Dimension scores']).length !== 12) throw new Error(`${score['Paper ID']} does not have 12 dimensions`);
  const recomputed = Object.values(score['Dimension scores']).reduce((sum, item) => sum + item.score, 0);
  if (recomputed !== score.Total) throw new Error(`${score['Paper ID']} total mismatch`);
}

fs.writeFileSync(new URL('./screening_2025_database_fulltext_batch04.json', import.meta.url), `${JSON.stringify(out, null, 2)}\n`);
